$axure.loadCurrentPage({
  "url":"向好友付款.html",
  "generationDate":new Date(1398151329916.37),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a18e3fae828943a7a44cae14c98efcca",
    "type":"Axure:Page",
    "name":"向好友付款",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f3a5727f3a7c48c8bfc173f8eae0b2ed",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":208},
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f91f728f54c54b1bad618be3e234b585",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":208},
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u0.png"}},
{
          "id":"bd7de4d6ae764c4bb662460d8a298952",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":132,
              "y":329},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"707a70122cdb4213993212ef56e174f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":132,
                  "y":329},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u2.png"}},
{
          "id":"2d705a5ada6245b2ad3ccc286749d5aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":132,
              "y":847},
            "size":{
              "width":92,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c4f956ec0e54d53b7856d6e80ba94d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":132,
                  "y":847},
                "size":{
                  "width":92,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u4.png"}},
{
          "id":"6a96f75e32984d548215b5c747174235",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":239,
              "y":847},
            "size":{
              "width":90,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67e8d35df6f9449592a2ff09a2f17ac6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":239,
                  "y":847},
                "size":{
                  "width":90,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u6.png"}},
{
          "id":"2df0637035a04fb39ecd6cc44b3dbac5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":344,
              "y":847},
            "size":{
              "width":90,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c2e4067d4894376a927492d6181e686",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":847},
                "size":{
                  "width":90,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u6.png"}},
{
          "id":"4f43ae6558c04ec7b0f21ec103e5f2ab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":129,
              "y":349},
            "size":{
              "width":108,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e75a714320f84c57a58290879411a957",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":129,
                  "y":349},
                "size":{
                  "width":108,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u12.png"}},
{
          "id":"1f9abf0ea875481a839e578811706953",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":236,
              "y":349},
            "size":{
              "width":99,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2ba56c6c89de468b94dcaf8f5de5cdc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":236,
                  "y":349},
                "size":{
                  "width":99,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u22.png"}},
{
          "id":"92960cbc0c0f42a4ab4eec99dc046136",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":334,
              "y":349},
            "size":{
              "width":108,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c48b2740bc5f458bb4de1bc27db288fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":334,
                  "y":349},
                "size":{
                  "width":108,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u12.png"}},
{
          "id":"f3382da4f3ee499ab984be08bb193f20",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":574,
              "y":394},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4140657d26f46989ec0afa23f2575ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":574,
                  "y":394},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/核对手势密码/u35.png"}},
{
          "id":"e8b5b64a766b4f4280d47947407164cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":140,
              "y":717},
            "size":{
              "width":189,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f412aad8289416ca60857a5bde0defb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":140,
                  "y":717},
                "size":{
                  "width":189,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当面支付/u20.png"}},
{
          "id":"36d882598eaf458bba5d9fec86b0d77b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":329,
              "y":717},
            "size":{
              "width":108,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfd69fc7e0464c2694b8d28405f24c65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":329,
                  "y":717},
                "size":{
                  "width":108,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当面支付/u22.jpg"}},
{
          "id":"5ad2346eaa71491d9a7889c061230bb8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":585},
            "size":{
              "width":284,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"228e34181d0142a88893446fdad868f6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":146,
                  "y":585},
                "size":{
                  "width":284,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当面支付/u24.png"}},
{
          "id":"b33caf1f4b774933b8f7e94e23c1954e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":572},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4493524c6bd14c98bd5111d0e95605bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":572},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当面支付/u26.png"}},
{
          "id":"0d35a0a89ddd490c81cdddf00c71b750",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":147,
              "y":482},
            "size":{
              "width":283,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3182e27e3b6041e494f7bdf2d124a988",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":147,
                  "y":482},
                "size":{
                  "width":283,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当面支付/u28.png"}},
{
          "id":"eb58f698bfc543ec949383e05c60ef41",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":525},
            "size":{
              "width":124,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4fcd3a00dce54b339ae85f94136875a5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":230,
              "y":404},
            "size":{
              "width":200,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1cd7e18d63e40d7ade783fd888dbabe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":230,
                  "y":404},
                "size":{
                  "width":200,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当面支付/u33.png"}},
{
          "id":"ffce432a237a41d4aa5da6be0a1a84cb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":404},
            "size":{
              "width":74,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c57bf4d1c3064de58695b3827ccbb601",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":146,
                  "y":404},
                "size":{
                  "width":74,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当面支付/u35.png"}},
{
          "id":"0fcea13bd6f04d888e2c26aa3267481f",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":306,
              "y":525},
            "size":{
              "width":124,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"90acd3d5ff1c47ec8da4e0ecf4c7f80f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":575},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c84f6c77cee9404d87cdf59019f34293",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":575},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当面支付/u38.png"}},
{
          "id":"7fb53f5963c242daa65c68c4ddd344e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":144,
              "y":455},
            "size":{
              "width":141,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7152c266eee46eeb029923d455e509a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":144,
                  "y":455},
                "size":{
                  "width":141,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"78ff7b4f1a9c4bff814548fc47494c4f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"12px",
            "fontWeight":"400",
            "location":{
              "x":296,
              "y":455},
            "size":{
              "width":139,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64b693a52c56474e85e4227cbce1ccca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"12px",
                "fontWeight":"400",
                "location":{
                  "x":296,
                  "y":455},
                "size":{
                  "width":139,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "f3a5727f3a7c48c8bfc173f8eae0b2ed":{
      "scriptId":"u0"},
    "f91f728f54c54b1bad618be3e234b585":{
      "scriptId":"u1"},
    "bd7de4d6ae764c4bb662460d8a298952":{
      "scriptId":"u2"},
    "707a70122cdb4213993212ef56e174f2":{
      "scriptId":"u3"},
    "2d705a5ada6245b2ad3ccc286749d5aa":{
      "scriptId":"u4"},
    "1c4f956ec0e54d53b7856d6e80ba94d7":{
      "scriptId":"u5"},
    "6a96f75e32984d548215b5c747174235":{
      "scriptId":"u6"},
    "67e8d35df6f9449592a2ff09a2f17ac6":{
      "scriptId":"u7"},
    "2df0637035a04fb39ecd6cc44b3dbac5":{
      "scriptId":"u8"},
    "7c2e4067d4894376a927492d6181e686":{
      "scriptId":"u9"},
    "4f43ae6558c04ec7b0f21ec103e5f2ab":{
      "scriptId":"u10"},
    "e75a714320f84c57a58290879411a957":{
      "scriptId":"u11"},
    "1f9abf0ea875481a839e578811706953":{
      "scriptId":"u12"},
    "2ba56c6c89de468b94dcaf8f5de5cdc8":{
      "scriptId":"u13"},
    "92960cbc0c0f42a4ab4eec99dc046136":{
      "scriptId":"u14"},
    "c48b2740bc5f458bb4de1bc27db288fa":{
      "scriptId":"u15"},
    "f3382da4f3ee499ab984be08bb193f20":{
      "scriptId":"u16"},
    "f4140657d26f46989ec0afa23f2575ff":{
      "scriptId":"u17"},
    "e8b5b64a766b4f4280d47947407164cc":{
      "scriptId":"u18"},
    "3f412aad8289416ca60857a5bde0defb":{
      "scriptId":"u19"},
    "36d882598eaf458bba5d9fec86b0d77b":{
      "scriptId":"u20"},
    "dfd69fc7e0464c2694b8d28405f24c65":{
      "scriptId":"u21"},
    "5ad2346eaa71491d9a7889c061230bb8":{
      "scriptId":"u22"},
    "228e34181d0142a88893446fdad868f6":{
      "scriptId":"u23"},
    "b33caf1f4b774933b8f7e94e23c1954e":{
      "scriptId":"u24"},
    "4493524c6bd14c98bd5111d0e95605bd":{
      "scriptId":"u25"},
    "0d35a0a89ddd490c81cdddf00c71b750":{
      "scriptId":"u26"},
    "3182e27e3b6041e494f7bdf2d124a988":{
      "scriptId":"u27"},
    "eb58f698bfc543ec949383e05c60ef41":{
      "scriptId":"u28"},
    "4fcd3a00dce54b339ae85f94136875a5":{
      "scriptId":"u29"},
    "e1cd7e18d63e40d7ade783fd888dbabe":{
      "scriptId":"u30"},
    "ffce432a237a41d4aa5da6be0a1a84cb":{
      "scriptId":"u31"},
    "c57bf4d1c3064de58695b3827ccbb601":{
      "scriptId":"u32"},
    "0fcea13bd6f04d888e2c26aa3267481f":{
      "scriptId":"u33"},
    "90acd3d5ff1c47ec8da4e0ecf4c7f80f":{
      "scriptId":"u34"},
    "c84f6c77cee9404d87cdf59019f34293":{
      "scriptId":"u35"},
    "7fb53f5963c242daa65c68c4ddd344e3":{
      "scriptId":"u36"},
    "f7152c266eee46eeb029923d455e509a":{
      "scriptId":"u37"},
    "78ff7b4f1a9c4bff814548fc47494c4f":{
      "scriptId":"u38"},
    "64b693a52c56474e85e4227cbce1ccca":{
      "scriptId":"u39"}}});