$axure.loadCurrentPage({
  "url":"结果通知页.html",
  "generationDate":new Date(1415177480812.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9283a44f26ab4e40969bd3bc177323f9",
    "type":"Axure:Page",
    "name":"结果通知页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f7e2e402291c4b29a223aeb955f26087",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "size":{
              "width":660,
              "height":1160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6b7e9ab4b1a45c6a64600ab785bfad4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "size":{
                  "width":660,
                  "height":1160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u0.png"}},
{
          "id":"8dbbfb8e0c7c42d1a47803fa5bf83861",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3778f633c3264430b2bc9bd7c50f8618",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u2.png"}},
{
          "id":"e2645df89f9d495fadd4ad99ec29d788",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":20},
            "size":{
              "width":640,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"03ab5dab21f049a28e2708d71727530f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":20},
                "size":{
                  "width":640,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/业务页背景/u4.png"}},
{
          "id":"579ee23bfb0545a7b118be39210eb59c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":217,
              "y":72},
            "size":{
              "width":193,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c030a5d5fdff481a86519072d7a77ae2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":217,
                  "y":72},
                "size":{
                  "width":193,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"656305ac0e5e43e98b4f0e90fff67fbc",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":23,
              "y":140},
            "size":{
              "width":607,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/业务页背景/u10_line.png"}},
{
          "id":"81589fce37c3486dbdb4721c91985b55",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":36,
              "y":194},
            "size":{
              "width":253,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5567791e34cb43b7ac33516850da4619",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"36px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000CC,
                  "opacity":1},
                "location":{
                  "x":36,
                  "y":194},
                "size":{
                  "width":253,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4973da596ec14e4bb656bd4265a24e0e",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":36,
              "y":270},
            "size":{
              "width":594,
              "height":270}},
          "adaptiveStyles":{
}},
{
          "id":"b7f3dc26f05a4511a41a53a3fa73f878",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":118,
              "y":434},
            "size":{
              "width":382,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"88a62b0200a945b2a44e877599a0e8d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":118,
                  "y":434},
                "size":{
                  "width":382,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd4f8f7eaf2d48faa74d6d9b5355b128",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "location":{
              "x":118,
              "y":487},
            "size":{
              "width":452,
              "height":33}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"477776bc41e845d89e4d57e8ab61f606",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "location":{
                  "x":118,
                  "y":487},
                "size":{
                  "width":452,
                  "height":33}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"50b492cfb6054be2bf1757e9cbbe5aa7",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"30px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":159,
              "y":600},
            "size":{
              "width":300,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 首页面",
                      "target":{
                        "targetType":"page",
                        "url":"首页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "f7e2e402291c4b29a223aeb955f26087":{
      "scriptId":"u0"},
    "c6b7e9ab4b1a45c6a64600ab785bfad4":{
      "scriptId":"u1"},
    "8dbbfb8e0c7c42d1a47803fa5bf83861":{
      "scriptId":"u2"},
    "3778f633c3264430b2bc9bd7c50f8618":{
      "scriptId":"u3"},
    "e2645df89f9d495fadd4ad99ec29d788":{
      "scriptId":"u4"},
    "03ab5dab21f049a28e2708d71727530f":{
      "scriptId":"u5"},
    "579ee23bfb0545a7b118be39210eb59c":{
      "scriptId":"u6"},
    "c030a5d5fdff481a86519072d7a77ae2":{
      "scriptId":"u7"},
    "656305ac0e5e43e98b4f0e90fff67fbc":{
      "scriptId":"u8"},
    "81589fce37c3486dbdb4721c91985b55":{
      "scriptId":"u9"},
    "5567791e34cb43b7ac33516850da4619":{
      "scriptId":"u10"},
    "4973da596ec14e4bb656bd4265a24e0e":{
      "scriptId":"u11"},
    "b7f3dc26f05a4511a41a53a3fa73f878":{
      "scriptId":"u12"},
    "88a62b0200a945b2a44e877599a0e8d6":{
      "scriptId":"u13"},
    "cd4f8f7eaf2d48faa74d6d9b5355b128":{
      "scriptId":"u14"},
    "477776bc41e845d89e4d57e8ab61f606":{
      "scriptId":"u15"},
    "50b492cfb6054be2bf1757e9cbbe5aa7":{
      "scriptId":"u16"}}});