$axure.loadCurrentPage({
  "url":"优惠卡支付.html",
  "generationDate":new Date(1411108789890.63),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2fd5eb40eba946448322c71456aae437",
    "type":"Axure:Page",
    "name":"优惠卡支付",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7fa7c7aaaa6f473699203e72e2190345",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":20},
            "size":{
              "width":390,
              "height":744},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fafc31537a36468cb4f62eb9369507f4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":20},
                "size":{
                  "width":390,
                  "height":744},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝订单支付/u0.png"}},
{
          "id":"4735c5973d934f00b36cdfed7fa5cd55",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":163},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9ec53bc56f54f1899d2eb31f5e4a329",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":163},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝订单支付/u2.png"}},
{
          "id":"c3544d81eac54947983346b88a4d9eaa",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"center",
            "location":{
              "x":143,
              "y":186},
            "size":{
              "width":164,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9eb3e2d7bba547bd9d173d20102c766f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "location":{
                  "x":143,
                  "y":186},
                "size":{
                  "width":164,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0afc1f708e114725bc0731365245aede",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":70,
              "y":240},
            "size":{
              "width":310,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47735c7f8d87401fa3c7a602f7597181",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":70,
                  "y":240},
                "size":{
                  "width":310,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝订单支付/u6.png"}},
{
          "id":"ac8cf390aab44b2a9dc4a36aae2e59b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":90,
              "y":560},
            "size":{
              "width":260,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a639d93522204779ba67cdd7c11b4704",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":90,
                  "y":560},
                "size":{
                  "width":260,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 手机验证",
                      "target":{
                        "targetType":"page",
                        "url":"手机验证.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/通付宝订单支付/u8.png"}},
{
          "id":"6b31b5db23594642831e411984c57a62",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":70,
              "y":330},
            "size":{
              "width":310,
              "height":81}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"635069ad109949478fdf002be215ee98",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":70,
                  "y":330},
                "size":{
                  "width":310,
                  "height":81}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝订单支付/u10.png"}},
{
          "id":"2724d87a4857439bb8e06cbbf613b4c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":70,
              "y":411},
            "size":{
              "width":310,
              "height":129}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b221a0bbf6a4d759f4d75fca7780bae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":70,
                  "y":411},
                "size":{
                  "width":310,
                  "height":129}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝订单支付/u16.png"}},
{
          "id":"ea86f0c9ebb94b9085cd7a651046f8bd",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":80,
              "y":450},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d632d3cf15934b12ab47fb843aef023b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":80,
                  "y":450},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"d39406196dec41eb969a5681bb7e82b8",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":80,
              "y":476},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86483f6025fa4b71a76141aa4295972a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":80,
                  "y":476},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"fffdfb6fb35e41c09019b9267b2f3465",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":80,
              "y":502},
            "size":{
              "width":110,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b498ca51e7a45088204e038efab65b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":80,
                  "y":502},
                "size":{
                  "width":110,
                  "height":16}},
              "adaptiveStyles":{
}}]}]}},
  "masters":{
},
  "objectPaths":{
    "7fa7c7aaaa6f473699203e72e2190345":{
      "scriptId":"u0"},
    "fafc31537a36468cb4f62eb9369507f4":{
      "scriptId":"u1"},
    "4735c5973d934f00b36cdfed7fa5cd55":{
      "scriptId":"u2"},
    "d9ec53bc56f54f1899d2eb31f5e4a329":{
      "scriptId":"u3"},
    "c3544d81eac54947983346b88a4d9eaa":{
      "scriptId":"u4"},
    "9eb3e2d7bba547bd9d173d20102c766f":{
      "scriptId":"u5"},
    "0afc1f708e114725bc0731365245aede":{
      "scriptId":"u6"},
    "47735c7f8d87401fa3c7a602f7597181":{
      "scriptId":"u7"},
    "ac8cf390aab44b2a9dc4a36aae2e59b6":{
      "scriptId":"u8"},
    "a639d93522204779ba67cdd7c11b4704":{
      "scriptId":"u9"},
    "6b31b5db23594642831e411984c57a62":{
      "scriptId":"u10"},
    "635069ad109949478fdf002be215ee98":{
      "scriptId":"u11"},
    "2724d87a4857439bb8e06cbbf613b4c4":{
      "scriptId":"u12"},
    "6b221a0bbf6a4d759f4d75fca7780bae":{
      "scriptId":"u13"},
    "ea86f0c9ebb94b9085cd7a651046f8bd":{
      "scriptId":"u14"},
    "d632d3cf15934b12ab47fb843aef023b":{
      "scriptId":"u15"},
    "d39406196dec41eb969a5681bb7e82b8":{
      "scriptId":"u16"},
    "86483f6025fa4b71a76141aa4295972a":{
      "scriptId":"u17"},
    "fffdfb6fb35e41c09019b9267b2f3465":{
      "scriptId":"u18"},
    "3b498ca51e7a45088204e038efab65b7":{
      "scriptId":"u19"}}});