$axure.loadCurrentPage({
  "url":"汇通卡输入.html",
  "generationDate":new Date(1397786910928.31),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ee6050a2d06a421980513ab601e7fe9f",
    "type":"Axure:Page",
    "name":"汇通卡输入",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"70c927696abb4d25b3037e7ece479ada",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":-550,
              "y":-320},
            "size":{
              "width":2000,
              "height":1333},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"202c50c87d134459a1674b3cead2c853",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":-550,
                  "y":-320},
                "size":{
                  "width":2000,
                  "height":1333},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/汇通卡输入/u0.png"}},
{
          "id":"c8be38a3460e4d1fbf2516031bf45d36",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCFFFF},
            "location":{
              "x":294,
              "y":92},
            "size":{
              "width":369,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFE4E4E4}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce9f5d67fedf4ef8a8b28ca3c4835da1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCFFFF},
                "location":{
                  "x":294,
                  "y":92},
                "size":{
                  "width":369,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/汇通卡输入/u2.png"}},
{
          "id":"d865ccac4efb48dc87b09463056c2a71",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":436,
              "y":107},
            "size":{
              "width":124,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"510f4a0b1a7c4b74bd21f00b3a2a9884",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":436,
                  "y":107},
                "size":{
                  "width":124,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6626bed4fd654cd2a30eb1ded286ba78",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":296,
              "y":144},
            "size":{
              "width":369,
              "height":578},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48c14a4f993b48b0aab6fca1b32d7613",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":296,
                  "y":144},
                "size":{
                  "width":369,
                  "height":578},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/汇通卡输入/u6.png"}},
{
          "id":"e7103b346c03436fba5af1af55f61aa7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":102},
            "size":{
              "width":65,
              "height":32},
            "borderWidth":"-1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b519ca8f328449b38a2dcc80d3790813",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":309,
                  "y":102},
                "size":{
                  "width":65,
                  "height":32},
                "borderWidth":"-1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/汇通卡输入/u8.png"}},
{
          "id":"53a9b78de99847ffa1133db042c6fc03",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":110},
            "size":{
              "width":44,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd56b824ee90491ca9b488bba874cf73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":110},
                "size":{
                  "width":44,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1309a37c0a454d1089647bc3f8bbf839",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":162},
            "size":{
              "width":329,
              "height":56},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44a1731fe8074067b526f2b5761e1bb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":309,
                  "y":162},
                "size":{
                  "width":329,
                  "height":56},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/汇通卡输入/u12.png"}},
{
          "id":"a0639d4b0c014bf1b670279e5f9a7597",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":330,
              "y":182},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78fe2f7d7fd74035912e80815aa262c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":330,
                  "y":182},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0697d489dcb74720b5b080efa702d8f3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":309,
              "y":254},
            "size":{
              "width":329,
              "height":335},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de3cdd9c72c440f9ad3dfe5fe0202479",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":309,
                  "y":254},
                "size":{
                  "width":329,
                  "height":335},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 汇通卡兑现成功 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"汇通卡兑现成功.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/汇通卡输入/u16.png"}},
{
          "id":"ec3b703313014e92869ffb0a952dbd1e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":380,
              "y":354},
            "size":{
              "width":250,
              "height":26}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04caee674c1540e3bf9ff74251210ebd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":380,
                  "y":354},
                "size":{
                  "width":250,
                  "height":26}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/汇通卡输入/u18.png"}},
{
          "id":"0e7468f9d15848c6bac024ee4864c5a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":386,
              "y":359},
            "size":{
              "width":150,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9acceb5c921a45fbb9b3dd955d28947f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":386,
                  "y":359},
                "size":{
                  "width":150,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"87a987de1d62466eb0b387619bcf3cc9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":600,
              "y":179},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66888bb92fb54a968fb2110a256eb02d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":600,
                  "y":179},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机充值首页/u12.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "70c927696abb4d25b3037e7ece479ada":{
      "scriptId":"u0"},
    "202c50c87d134459a1674b3cead2c853":{
      "scriptId":"u1"},
    "c8be38a3460e4d1fbf2516031bf45d36":{
      "scriptId":"u2"},
    "ce9f5d67fedf4ef8a8b28ca3c4835da1":{
      "scriptId":"u3"},
    "d865ccac4efb48dc87b09463056c2a71":{
      "scriptId":"u4"},
    "510f4a0b1a7c4b74bd21f00b3a2a9884":{
      "scriptId":"u5"},
    "6626bed4fd654cd2a30eb1ded286ba78":{
      "scriptId":"u6"},
    "48c14a4f993b48b0aab6fca1b32d7613":{
      "scriptId":"u7"},
    "e7103b346c03436fba5af1af55f61aa7":{
      "scriptId":"u8"},
    "b519ca8f328449b38a2dcc80d3790813":{
      "scriptId":"u9"},
    "53a9b78de99847ffa1133db042c6fc03":{
      "scriptId":"u10"},
    "dd56b824ee90491ca9b488bba874cf73":{
      "scriptId":"u11"},
    "1309a37c0a454d1089647bc3f8bbf839":{
      "scriptId":"u12"},
    "44a1731fe8074067b526f2b5761e1bb7":{
      "scriptId":"u13"},
    "a0639d4b0c014bf1b670279e5f9a7597":{
      "scriptId":"u14"},
    "78fe2f7d7fd74035912e80815aa262c8":{
      "scriptId":"u15"},
    "0697d489dcb74720b5b080efa702d8f3":{
      "scriptId":"u16"},
    "de3cdd9c72c440f9ad3dfe5fe0202479":{
      "scriptId":"u17"},
    "ec3b703313014e92869ffb0a952dbd1e":{
      "scriptId":"u18"},
    "04caee674c1540e3bf9ff74251210ebd":{
      "scriptId":"u19"},
    "0e7468f9d15848c6bac024ee4864c5a4":{
      "scriptId":"u20"},
    "9acceb5c921a45fbb9b3dd955d28947f":{
      "scriptId":"u21"},
    "87a987de1d62466eb0b387619bcf3cc9":{
      "scriptId":"u22"},
    "66888bb92fb54a968fb2110a256eb02d":{
      "scriptId":"u23"}}});