$axure.loadCurrentPage({
  "url":"通付宝代理商（效果页面）（新app）.html",
  "generationDate":new Date(1399184857862.72),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"e4a99d3069d54278b64b54e4fb4fc550",
    "type":"Axure:Page",
    "name":"通付宝代理商（效果页面）（新APP）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fa162df229f74101ab436379724c8afa",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":-10},
            "size":{
              "width":380,
              "height":744},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fa77934a9f8494bad168b22bdb82a26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":-10},
                "size":{
                  "width":380,
                  "height":744},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（效果页面）（新app）/u0.png"}},
{
          "id":"221561f271914a4baa729045baaec6fc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":31,
              "y":142},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b73e2bacda4499dbac374a331fb783b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":31,
                  "y":142},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（效果页面）（新app）/u2.png"}},
{
          "id":"838b4d42932b4eb59eb54425f6313644",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":127},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"78401bebe42c4309b13f53ea328cf758",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":127},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u2.png"}},
{
          "id":"13e40c0c1cb540678f97f19f4b36e2b4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":42,
              "y":198},
            "size":{
              "width":121,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c4ebcc911ec401bb3557e5cbd2ca97d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":42,
                  "y":198},
                "size":{
                  "width":121,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9597db932b6d4ff48ca859647113fdf1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"48px",
            "fontWeight":"700",
            "location":{
              "x":40,
              "y":233},
            "size":{
              "width":300,
              "height":117}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"da5c6b6e8ffa4ce9b16b4205811b5196",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"48px",
                "fontWeight":"700",
                "location":{
                  "x":40,
                  "y":233},
                "size":{
                  "width":300,
                  "height":117}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（效果页面）（新app）/u8.png"}},
{
          "id":"b1f2d5e42d7644e79bd552b0efaefb19",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "location":{
              "x":54,
              "y":372},
            "size":{
              "width":206,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4dca6c54dd694159b794f8973d73c818",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":54,
                  "y":372},
                "size":{
                  "width":206,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"adbfb6fdbe5f4af1a45d172b58c1f1eb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":540},
            "size":{
              "width":140,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3be8e196ea2f4e08b9e2e72d223d0253",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":540},
                "size":{
                  "width":140,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（效果页面）（新app）/u12.png"}},
{
          "id":"afa854c79ec14dd28e759501910fb902",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":540},
            "size":{
              "width":140,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b00fa9ea13cf40fca0fef67cce0d8480",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":540},
                "size":{
                  "width":140,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（效果页面）（新app）/u12.png"}},
{
          "id":"e4d4697b4f3d419e99a0b0ba4aec21b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":490},
            "size":{
              "width":202,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a272b89a9b294b8d8dc9337bd4b63900",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":490},
                "size":{
                  "width":202,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（效果页面）（新app）/u16.png"}},
{
          "id":"ffe973fd407749c3b1361c030cc4954b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "location":{
              "x":132,
              "y":147},
            "size":{
              "width":98,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e79bf135ea994d3191752f2d3181c9bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":132,
                  "y":147},
                "size":{
                  "width":98,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01c2498c71934765a2361bafcafbf99d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontSize":"16px",
            "location":{
              "x":240,
              "y":160},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"96ab9a5a0cca479bade919892c21b2ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"16px",
                "location":{
                  "x":240,
                  "y":160},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b0cad45d16a14fccbe4f5ba2a93ef10a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":40,
              "y":420},
            "size":{
              "width":241,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"355f5e5e4dc94e739ce98d5aeaced5b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":40,
                  "y":420},
                "size":{
                  "width":241,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（效果页面）（新app）/u22.png"}},
{
          "id":"80780987daab4ce598c06ac6b5f5ca3e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":167,
              "y":326},
            "size":{
              "width":173,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2836df82294b423891127d7337c8dc5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":167,
                  "y":326},
                "size":{
                  "width":173,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"18b0917804b94b1b9a67cd3b80a92047",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":490},
            "size":{
              "width":70,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0efc61c3decc443195b787c8c3d5214c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":490},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 代理商订货 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"代理商订货.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/通付宝代理商（效果页面）（新app）/u26.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "fa162df229f74101ab436379724c8afa":{
      "scriptId":"u0"},
    "2fa77934a9f8494bad168b22bdb82a26":{
      "scriptId":"u1"},
    "221561f271914a4baa729045baaec6fc":{
      "scriptId":"u2"},
    "3b73e2bacda4499dbac374a331fb783b":{
      "scriptId":"u3"},
    "838b4d42932b4eb59eb54425f6313644":{
      "scriptId":"u4"},
    "78401bebe42c4309b13f53ea328cf758":{
      "scriptId":"u5"},
    "13e40c0c1cb540678f97f19f4b36e2b4":{
      "scriptId":"u6"},
    "0c4ebcc911ec401bb3557e5cbd2ca97d":{
      "scriptId":"u7"},
    "9597db932b6d4ff48ca859647113fdf1":{
      "scriptId":"u8"},
    "da5c6b6e8ffa4ce9b16b4205811b5196":{
      "scriptId":"u9"},
    "b1f2d5e42d7644e79bd552b0efaefb19":{
      "scriptId":"u10"},
    "4dca6c54dd694159b794f8973d73c818":{
      "scriptId":"u11"},
    "adbfb6fdbe5f4af1a45d172b58c1f1eb":{
      "scriptId":"u12"},
    "3be8e196ea2f4e08b9e2e72d223d0253":{
      "scriptId":"u13"},
    "afa854c79ec14dd28e759501910fb902":{
      "scriptId":"u14"},
    "b00fa9ea13cf40fca0fef67cce0d8480":{
      "scriptId":"u15"},
    "e4d4697b4f3d419e99a0b0ba4aec21b5":{
      "scriptId":"u16"},
    "a272b89a9b294b8d8dc9337bd4b63900":{
      "scriptId":"u17"},
    "ffe973fd407749c3b1361c030cc4954b":{
      "scriptId":"u18"},
    "e79bf135ea994d3191752f2d3181c9bd":{
      "scriptId":"u19"},
    "01c2498c71934765a2361bafcafbf99d":{
      "scriptId":"u20"},
    "96ab9a5a0cca479bade919892c21b2ca":{
      "scriptId":"u21"},
    "b0cad45d16a14fccbe4f5ba2a93ef10a":{
      "scriptId":"u22"},
    "355f5e5e4dc94e739ce98d5aeaced5b8":{
      "scriptId":"u23"},
    "80780987daab4ce598c06ac6b5f5ca3e":{
      "scriptId":"u24"},
    "2836df82294b423891127d7337c8dc5f":{
      "scriptId":"u25"},
    "18b0917804b94b1b9a67cd3b80a92047":{
      "scriptId":"u26"},
    "0efc61c3decc443195b787c8c3d5214c":{
      "scriptId":"u27"}}});