$axure.loadCurrentPage({
  "url":"银行卡列表页.html",
  "generationDate":new Date(1415177480156.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4462ba1b5e144a1ebf959af4038301d4",
    "type":"Axure:Page",
    "name":"银行卡列表页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d9eaaf20a16f48468d5642c958660409",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "size":{
              "width":660,
              "height":1160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d63fd04842fa4378bc5795518758e957",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "size":{
                  "width":660,
                  "height":1160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u0.png"}},
{
          "id":"769593e1a35e4d218e7a6ad45d2f6ac2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac4f327c16e948948572f1e9ba63a6a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u2.png"}},
{
          "id":"c28cb6f51f86491fb20d360993946914",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":20},
            "size":{
              "width":640,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7df5a56671744ee58cd1aabf858af520",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":20},
                "size":{
                  "width":640,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/业务页背景/u4.png"}},
{
          "id":"206dd22f0a134776954c2f55403de961",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":23,
              "y":70},
            "size":{
              "width":45,
              "height":60},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61deb5cdbc7e49f9a7eb9eaa815d3d1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":23,
                  "y":70},
                "size":{
                  "width":45,
                  "height":60},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/业务页背景/u6.png"}},
{
          "id":"466f12de1af541459dad37eb0a740eba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "location":{
              "x":138,
              "y":70},
            "size":{
              "width":241,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13a5d42bfe4f4e909525f29f8203347e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "location":{
                  "x":138,
                  "y":70},
                "size":{
                  "width":241,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"748211e4eece4bbba668709a95cbad08",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":23,
              "y":140},
            "size":{
              "width":607,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/业务页背景/u10_line.png"}},
{
          "id":"74c61e6ce92143d7abf9a53692ac2dad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":1138,
              "y":219},
            "size":{
              "width":188,
              "height":19},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99a688174c4b4e0a8d19f000a20b6fd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":1138,
                  "y":219},
                "size":{
                  "width":188,
                  "height":19},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1e66f6bbac87400089983c9d08510102",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"28px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":430,
              "y":153},
            "size":{
              "width":85,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b862645527244eaa88f3a28a4fea340",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Bold', '微软雅黑'",
                "fontSize":"28px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":430,
                  "y":153},
                "size":{
                  "width":85,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"128545627ce642a9925347a15097cbd3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":160},
            "size":{
              "width":570,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67f6e3b9ff7a4d96baac0c74056fafd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":160},
                "size":{
                  "width":570,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 业务页",
                      "target":{
                        "targetType":"page",
                        "url":"业务页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/银行卡列表页/u15.png"}},
{
          "id":"1a9c170cefbd480f8ffe8bf24234c5a0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":60,
              "y":220},
            "size":{
              "width":570,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b193f130a324cf5b85113b711ed91d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":60,
                  "y":220},
                "size":{
                  "width":570,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/银行卡列表页/u15.png"}},
{
          "id":"a715c86ed3c149bc946c5dbdb2e023d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":60,
              "y":280},
            "size":{
              "width":570,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7742ea4798cf4471bd2e817f94d0f0dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":60,
                  "y":280},
                "size":{
                  "width":570,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/银行卡列表页/u15.png"}},
{
          "id":"2aafbdfe39b94a2ca692a3c6f4c7734f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":88,
              "y":173},
            "size":{
              "width":47,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b15b2e361ad45aaa9df19a237afb15e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":88,
                  "y":173},
                "size":{
                  "width":47,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5403b76174484aee806e739b9cdf344a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":430},
            "size":{
              "width":551,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f7be003166344bd6bcbf71e394628b02",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":430},
                "size":{
                  "width":551,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bd19cb6e689c4af4b99a1483f649d6ef",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":586,
              "y":83},
            "size":{
              "width":44,
              "height":44},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6d3e23643d7402facd76900f0db5716",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":586,
                  "y":83},
                "size":{
                  "width":44,
                  "height":44},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 新增默认收款账户",
                      "target":{
                        "targetType":"page",
                        "url":"新增默认收款账户.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/银行卡列表页/u25.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d9eaaf20a16f48468d5642c958660409":{
      "scriptId":"u0"},
    "d63fd04842fa4378bc5795518758e957":{
      "scriptId":"u1"},
    "769593e1a35e4d218e7a6ad45d2f6ac2":{
      "scriptId":"u2"},
    "ac4f327c16e948948572f1e9ba63a6a7":{
      "scriptId":"u3"},
    "c28cb6f51f86491fb20d360993946914":{
      "scriptId":"u4"},
    "7df5a56671744ee58cd1aabf858af520":{
      "scriptId":"u5"},
    "206dd22f0a134776954c2f55403de961":{
      "scriptId":"u6"},
    "61deb5cdbc7e49f9a7eb9eaa815d3d1d":{
      "scriptId":"u7"},
    "466f12de1af541459dad37eb0a740eba":{
      "scriptId":"u8"},
    "13a5d42bfe4f4e909525f29f8203347e":{
      "scriptId":"u9"},
    "748211e4eece4bbba668709a95cbad08":{
      "scriptId":"u10"},
    "74c61e6ce92143d7abf9a53692ac2dad":{
      "scriptId":"u11"},
    "99a688174c4b4e0a8d19f000a20b6fd4":{
      "scriptId":"u12"},
    "1e66f6bbac87400089983c9d08510102":{
      "scriptId":"u13"},
    "6b862645527244eaa88f3a28a4fea340":{
      "scriptId":"u14"},
    "128545627ce642a9925347a15097cbd3":{
      "scriptId":"u15"},
    "67f6e3b9ff7a4d96baac0c74056fafd4":{
      "scriptId":"u16"},
    "1a9c170cefbd480f8ffe8bf24234c5a0":{
      "scriptId":"u17"},
    "2b193f130a324cf5b85113b711ed91d1":{
      "scriptId":"u18"},
    "a715c86ed3c149bc946c5dbdb2e023d5":{
      "scriptId":"u19"},
    "7742ea4798cf4471bd2e817f94d0f0dc":{
      "scriptId":"u20"},
    "2aafbdfe39b94a2ca692a3c6f4c7734f":{
      "scriptId":"u21"},
    "5b15b2e361ad45aaa9df19a237afb15e":{
      "scriptId":"u22"},
    "5403b76174484aee806e739b9cdf344a":{
      "scriptId":"u23"},
    "f7be003166344bd6bcbf71e394628b02":{
      "scriptId":"u24"},
    "bd19cb6e689c4af4b99a1483f649d6ef":{
      "scriptId":"u25"},
    "f6d3e23643d7402facd76900f0db5716":{
      "scriptId":"u26"}}});