$axure.loadCurrentPage({
  "url":"填写银行卡.html",
  "generationDate":new Date(1411108789375),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1ca763c7c72e449788836a5e614e0fd9",
    "type":"Axure:Page",
    "name":"填写银行卡",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"ee03f9f4469e4d9daa4f70b21747cc08",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":26},
            "size":{
              "width":380,
              "height":744},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"813e863319604a57b99bc1cedb343480",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":26},
                "size":{
                  "width":380,
                  "height":744},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝订单支付/u0.png"}},
{
          "id":"abc1c664fe9247719d2cb69abe6c7503",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":51,
              "y":178},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4e5b09eff194269a30b33fb807d16c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":51,
                  "y":178},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/填写银行卡/u2.png"}},
{
          "id":"d40f4014d4db4e9fb6b1df43c342cbad",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":163},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fd79db73d4cd4122969296dcc50af5f7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":163},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝订单支付/u2.png"}},
{
          "id":"dcc3adc8fe354774a874fa7714418fa0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":70,
              "y":304},
            "size":{
              "width":290,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e386cc836d34d47bd3179b13779a471",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":70,
                  "y":304},
                "size":{
                  "width":290,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/填写银行卡/u6.png"}},
{
          "id":"9f959e55844447bb8d957ff599ef92b5",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":131,
              "y":187},
            "size":{
              "width":168,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"07d2888cf25a48df8ced3581d0651e80",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":131,
                  "y":187},
                "size":{
                  "width":168,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8225f8ea727345a39f643fbfd0a802e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":162,
              "y":370},
            "size":{
              "width":90,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d5474dc95fc4cd3a79b820ea0c65eff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":162,
                  "y":370},
                "size":{
                  "width":90,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 信用卡支付",
                      "target":{
                        "targetType":"page",
                        "url":"信用卡支付.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/填写银行卡/u10.png"}},
{
          "id":"e9190e4643134b198ac01c904b2818d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":61,
              "y":186},
            "size":{
              "width":39,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce409824c6244d3aaf1c2af5f16ab2dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":61,
                  "y":186},
                "size":{
                  "width":39,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 银行卡支付",
                      "target":{
                        "targetType":"page",
                        "url":"银行卡支付.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/填写银行卡/u12.png"}},
{
          "id":"7a5059b9580d420b998f424c4d7fe0e6",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":70,
              "y":270},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"901a8f4577ce418c985bcb97247e36a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":70,
                  "y":270},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c5890d33c0c145469651354e7de7e4b1",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":162,
              "y":270},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a6cb5528285443878f1c88fc367f4884",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":162,
                  "y":270},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"2306bb02786d4f95a55e846009a863a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":290,
              "y":304},
            "size":{
              "width":70,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfc4ab8372ff4a82b7cb9f64b90c4dc0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":290,
                  "y":304},
                "size":{
                  "width":70,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的银行卡",
                      "target":{
                        "targetType":"page",
                        "url":"我的银行卡.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/填写银行卡/u18.png"}},
{
          "id":"38d6683aadd84b8c91f4a5e28d74a561",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":420,
              "y":258},
            "size":{
              "width":390,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"662a40982ff6469583fbb78b5be02f52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":420,
                  "y":258},
                "size":{
                  "width":390,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/填写银行卡/u20.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "ee03f9f4469e4d9daa4f70b21747cc08":{
      "scriptId":"u0"},
    "813e863319604a57b99bc1cedb343480":{
      "scriptId":"u1"},
    "abc1c664fe9247719d2cb69abe6c7503":{
      "scriptId":"u2"},
    "d4e5b09eff194269a30b33fb807d16c7":{
      "scriptId":"u3"},
    "d40f4014d4db4e9fb6b1df43c342cbad":{
      "scriptId":"u4"},
    "fd79db73d4cd4122969296dcc50af5f7":{
      "scriptId":"u5"},
    "dcc3adc8fe354774a874fa7714418fa0":{
      "scriptId":"u6"},
    "3e386cc836d34d47bd3179b13779a471":{
      "scriptId":"u7"},
    "9f959e55844447bb8d957ff599ef92b5":{
      "scriptId":"u8"},
    "07d2888cf25a48df8ced3581d0651e80":{
      "scriptId":"u9"},
    "8225f8ea727345a39f643fbfd0a802e7":{
      "scriptId":"u10"},
    "0d5474dc95fc4cd3a79b820ea0c65eff":{
      "scriptId":"u11"},
    "e9190e4643134b198ac01c904b2818d7":{
      "scriptId":"u12"},
    "ce409824c6244d3aaf1c2af5f16ab2dc":{
      "scriptId":"u13"},
    "7a5059b9580d420b998f424c4d7fe0e6":{
      "scriptId":"u14"},
    "901a8f4577ce418c985bcb97247e36a4":{
      "scriptId":"u15"},
    "c5890d33c0c145469651354e7de7e4b1":{
      "scriptId":"u16"},
    "a6cb5528285443878f1c88fc367f4884":{
      "scriptId":"u17"},
    "2306bb02786d4f95a55e846009a863a1":{
      "scriptId":"u18"},
    "dfc4ab8372ff4a82b7cb9f64b90c4dc0":{
      "scriptId":"u19"},
    "38d6683aadd84b8c91f4a5e28d74a561":{
      "scriptId":"u20"},
    "662a40982ff6469583fbb78b5be02f52":{
      "scriptId":"u21"}}});