$axure.loadCurrentPage({
  "url":"功能列表（新）查询.html",
  "generationDate":new Date(1399184857524.7),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0916b6ee406f48f4b404baa05cbb9df9",
    "type":"Axure:Page",
    "name":"功能列表（新）查询",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"269da3acb0674c00944549b595f7e254",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":80},
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61f3446c5f7a473f9aaac789b9734960",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":80},
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u0.png"}},
{
          "id":"c73ea6199fb347d9b900e92d4771fb11",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":202},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90dda5d6d9164339a6eed6ad23ae06f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":202},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u2.png"}},
{
          "id":"711596f95a89426aa071fbbece86f79c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":720},
            "size":{
              "width":102,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f52d4599640d4b0ba39481b393c703b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":720},
                "size":{
                  "width":102,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包设定（第一次使用）/u12.png"}},
{
          "id":"39e14c36ac5a44eda8cdc0c9374f488c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":720},
            "size":{
              "width":110,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f3d8b0fce114c32a9b96c0b05bca0ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":720},
                "size":{
                  "width":110,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包设定（第一次使用）/u14.png"}},
{
          "id":"8755ea3661874399ba87a44d9c1acb16",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":720},
            "size":{
              "width":97,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8700580998c64a77862adde147028d5c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":268,
                  "y":720},
                "size":{
                  "width":97,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/钱包设定（第一次使用）/u16.png"}},
{
          "id":"8d42b0c5fff84f83a2e14f514264cbe3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":222},
            "size":{
              "width":108,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6766290526749f3a47136af9514f1c4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":222},
                "size":{
                  "width":108,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u12.png"}},
{
          "id":"8a012d9dfdb248eca751db482b89c49d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":162,
              "y":222},
            "size":{
              "width":99,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"878f79edd6cb450795e510973ccd1b66",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":162,
                  "y":222},
                "size":{
                  "width":99,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u22.png"}},
{
          "id":"d4b08f74b2ca45f482d4ec646999d63f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":260,
              "y":222},
            "size":{
              "width":108,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ceafb685066f4220b2b0282ba8651d9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":260,
                  "y":222},
                "size":{
                  "width":108,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u12.png"}},
{
          "id":"5b6a544e5cbd4a0490ef15ff56b63ddc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":520,
              "y":400},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"31809377a27442b88b8e0d2e020ab325",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":520,
                  "y":400},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）收款/u12.png"}},
{
          "id":"218a47f38136481f91b2ddc5b1f48119",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":280},
            "size":{
              "width":189,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51bba12b65504434909594c7a7916e2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":280},
                "size":{
                  "width":189,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）查询/u18.png"}},
{
          "id":"fe6fcabb043c415db345cc50be752b96",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":274,
              "y":280},
            "size":{
              "width":80,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c049ad8f918d4f3f8b18f56ee90e3c2e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":274,
                  "y":280},
                "size":{
                  "width":80,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）查询/u20.png"}},
{
          "id":"9c513057209f48009e1e3b402ecd977b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":274,
              "y":360},
            "size":{
              "width":79,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06d389ab94d94f419ca4d717e438baf4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":274,
                  "y":360},
                "size":{
                  "width":79,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）查询/u22.png"}},
{
          "id":"e65a38c4def347cc9e5b10c184356d02",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":360},
            "size":{
              "width":78,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a3f93a0c4d8b40549551d7aa3531c0ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":360},
                "size":{
                  "width":78,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）查询/u24.png"}},
{
          "id":"611df8b2b7a64463babdedece116c353",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":360},
            "size":{
              "width":100,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"658f18de274f451395417534f430c4f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":360},
                "size":{
                  "width":100,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）查询/u26.png"}},
{
          "id":"9db85cba1ce444d5a40057ab2267e913",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":430},
            "size":{
              "width":188,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"282daac749ee41a1b6a9b461ca9b8085",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":430},
                "size":{
                  "width":188,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）查询/u28.png"}},
{
          "id":"0e84637f55a1450696b874ed8f10c4ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":274,
              "y":530},
            "size":{
              "width":79,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7b64efae8b2434badfa960826c5cc3f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":274,
                  "y":530},
                "size":{
                  "width":79,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）查询/u30.png"}},
{
          "id":"2521ecdc283f4ab0aafd998e95674cd4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":530},
            "size":{
              "width":68,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86880736ab914f498062124f50b484ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":530},
                "size":{
                  "width":68,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）查询/u32.png"}},
{
          "id":"630e2bf3fdcf4565b7a109f89fd383f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":153,
              "y":530},
            "size":{
              "width":107,
              "height":170}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15bdd14a2ac04ff3906a4da8d114e61b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":153,
                  "y":530},
                "size":{
                  "width":107,
                  "height":170}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）查询/u34.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "269da3acb0674c00944549b595f7e254":{
      "scriptId":"u0"},
    "61f3446c5f7a473f9aaac789b9734960":{
      "scriptId":"u1"},
    "c73ea6199fb347d9b900e92d4771fb11":{
      "scriptId":"u2"},
    "90dda5d6d9164339a6eed6ad23ae06f8":{
      "scriptId":"u3"},
    "711596f95a89426aa071fbbece86f79c":{
      "scriptId":"u4"},
    "f52d4599640d4b0ba39481b393c703b7":{
      "scriptId":"u5"},
    "39e14c36ac5a44eda8cdc0c9374f488c":{
      "scriptId":"u6"},
    "4f3d8b0fce114c32a9b96c0b05bca0ff":{
      "scriptId":"u7"},
    "8755ea3661874399ba87a44d9c1acb16":{
      "scriptId":"u8"},
    "8700580998c64a77862adde147028d5c":{
      "scriptId":"u9"},
    "8d42b0c5fff84f83a2e14f514264cbe3":{
      "scriptId":"u10"},
    "c6766290526749f3a47136af9514f1c4":{
      "scriptId":"u11"},
    "8a012d9dfdb248eca751db482b89c49d":{
      "scriptId":"u12"},
    "878f79edd6cb450795e510973ccd1b66":{
      "scriptId":"u13"},
    "d4b08f74b2ca45f482d4ec646999d63f":{
      "scriptId":"u14"},
    "ceafb685066f4220b2b0282ba8651d9b":{
      "scriptId":"u15"},
    "5b6a544e5cbd4a0490ef15ff56b63ddc":{
      "scriptId":"u16"},
    "31809377a27442b88b8e0d2e020ab325":{
      "scriptId":"u17"},
    "218a47f38136481f91b2ddc5b1f48119":{
      "scriptId":"u18"},
    "51bba12b65504434909594c7a7916e2c":{
      "scriptId":"u19"},
    "fe6fcabb043c415db345cc50be752b96":{
      "scriptId":"u20"},
    "c049ad8f918d4f3f8b18f56ee90e3c2e":{
      "scriptId":"u21"},
    "9c513057209f48009e1e3b402ecd977b":{
      "scriptId":"u22"},
    "06d389ab94d94f419ca4d717e438baf4":{
      "scriptId":"u23"},
    "e65a38c4def347cc9e5b10c184356d02":{
      "scriptId":"u24"},
    "a3f93a0c4d8b40549551d7aa3531c0ce":{
      "scriptId":"u25"},
    "611df8b2b7a64463babdedece116c353":{
      "scriptId":"u26"},
    "658f18de274f451395417534f430c4f9":{
      "scriptId":"u27"},
    "9db85cba1ce444d5a40057ab2267e913":{
      "scriptId":"u28"},
    "282daac749ee41a1b6a9b461ca9b8085":{
      "scriptId":"u29"},
    "0e84637f55a1450696b874ed8f10c4ac":{
      "scriptId":"u30"},
    "d7b64efae8b2434badfa960826c5cc3f":{
      "scriptId":"u31"},
    "2521ecdc283f4ab0aafd998e95674cd4":{
      "scriptId":"u32"},
    "86880736ab914f498062124f50b484ba":{
      "scriptId":"u33"},
    "630e2bf3fdcf4565b7a109f89fd383f8":{
      "scriptId":"u34"},
    "15bdd14a2ac04ff3906a4da8d114e61b":{
      "scriptId":"u35"}}});