$axure.loadCurrentPage({
  "url":"历史详情.html",
  "generationDate":new Date(1405580874453.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bfa752b4b3c84634ac2baea0027557ef",
    "type":"Axure:Page",
    "name":"历史详情",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7c1014812d8b46d6a044c319bc81ca89",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c93f224071c4e2c85c72b0d5414eae6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"Move Widget",
                      "objectsToMoves":[]},
{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]},
{
                      "action":"moveWidget",
                      "description":"Move Widget",
                      "objectsToMoves":[]},
{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/机票酒店预定/u0.png"}},
{
          "id":"57396eed891a4f989f0bef826be66ba3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":33,
              "y":117},
            "size":{
              "width":320,
              "height":16},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8d130d5ccc04d51ad752b7f32291a01",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":33,
                  "y":117},
                "size":{
                  "width":320,
                  "height":16},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机票酒店预定/u2.png"}},
{
          "id":"59053a93e9204b928ace2e968b1b41b0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":33,
              "y":132},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c00000feca440b4b1f40557f776e047",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":33,
                  "y":132},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机票酒店预定/u4.png"}},
{
          "id":"13d35b8488af47ce8f2b118fc7246286",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"21px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":145,
              "y":144},
            "size":{
              "width":95,
              "height":75},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f93e445ce4654cf8a7116a07baad4895",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"21px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":145,
                  "y":144},
                "size":{
                  "width":95,
                  "height":75},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3b9888ec61741a6b46fde192c76e142",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":44,
              "y":145},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87c21eebc3544325936c6f44306e3035",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":145},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 历史记录",
                      "target":{
                        "targetType":"page",
                        "url":"历史记录.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/机票预定/u8.png"}},
{
          "id":"81a47da5c99e4b9d9d8494bdd167a889",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":32,
              "y":178},
            "size":{
              "width":320,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ddf3a3e700d4e8bab9cc550913b9c57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":32,
                  "y":178},
                "size":{
                  "width":320,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史记录/u10.png"}},
{
          "id":"c01153d4a1074e58bf2764afe214cdfc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":44,
              "y":188},
            "size":{
              "width":76,
              "height":22},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"44e42bfe026c46f5b17c448427dad9e4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":44,
                  "y":188},
                "size":{
                  "width":76,
                  "height":22},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史记录/u12.png"}},
{
          "id":"f4848e1a27f14b3cb4be8d57167e97b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":32,
              "y":220},
            "size":{
              "width":320,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab9224ed6b894189934d20539aa896a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":32,
                  "y":220},
                "size":{
                  "width":320,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史记录/u10.png"}},
{
          "id":"b6caec8bf542462d8920d3f869f7ebf6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":43,
              "y":230},
            "size":{
              "width":76,
              "height":22},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"988e06de8bed4217b3f0dc84da10d0c6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":43,
                  "y":230},
                "size":{
                  "width":76,
                  "height":22},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史记录/u12.png"}},
{
          "id":"0d1f59855a2644b7bdb4a7ead68ee98a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":32,
              "y":262},
            "size":{
              "width":320,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a35663cc463e4746817d53385bd0a584",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":32,
                  "y":262},
                "size":{
                  "width":320,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史记录/u10.png"}},
{
          "id":"f2a7d1c84e8c498ebcaa3e7cc2d4c8d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":44,
              "y":272},
            "size":{
              "width":76,
              "height":22},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3a5447a5e7914cac8cf052b401a701b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":44,
                  "y":272},
                "size":{
                  "width":76,
                  "height":22},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史记录/u12.png"}},
{
          "id":"0436a36ae68c4da6b227f9a1bcfdd42d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"200",
            "location":{
              "x":32,
              "y":304},
            "size":{
              "width":320,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4408f2ca2b5445eba6686fbf7f924d55",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"200",
                "location":{
                  "x":32,
                  "y":304},
                "size":{
                  "width":320,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史记录/u10.png"}},
{
          "id":"ccd12cceb0b74a8c9e121d9a7f858ff7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":43,
              "y":314},
            "size":{
              "width":76,
              "height":22},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68b86313be1740388078d0a0dcea9d03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":43,
                  "y":314},
                "size":{
                  "width":76,
                  "height":22},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史记录/u12.png"}},
{
          "id":"74f8dcf02b6b44cdaec23d6ad11fcd98",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":32,
              "y":346},
            "size":{
              "width":320,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5e8e0bd74ae4ad89d6d231030b8a2d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":32,
                  "y":346},
                "size":{
                  "width":320,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史记录/u10.png"}},
{
          "id":"1ab4885e92ea4fd38148da7c78ff5676",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":44,
              "y":356},
            "size":{
              "width":76,
              "height":22},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6a1c224055f4489c8df27266fd2832aa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":44,
                  "y":356},
                "size":{
                  "width":76,
                  "height":22},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史记录/u12.png"}},
{
          "id":"a05abe0050ea41a7929c4cc6ab391741",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":32,
              "y":388},
            "size":{
              "width":320,
              "height":42}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7dd8d724726412a98b0b78cfdc624e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":32,
                  "y":388},
                "size":{
                  "width":320,
                  "height":42}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史记录/u10.png"}},
{
          "id":"5f8f951477554c0991e67fa61f95a88b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "location":{
              "x":43,
              "y":398},
            "size":{
              "width":76,
              "height":22},
            "linePattern":"none"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30252e61ff514e45b09cf1863ba2bbd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "location":{
                  "x":43,
                  "y":398},
                "size":{
                  "width":76,
                  "height":22},
                "linePattern":"none"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/历史记录/u12.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "7c1014812d8b46d6a044c319bc81ca89":{
      "scriptId":"u0"},
    "4c93f224071c4e2c85c72b0d5414eae6":{
      "scriptId":"u1"},
    "57396eed891a4f989f0bef826be66ba3":{
      "scriptId":"u2"},
    "a8d130d5ccc04d51ad752b7f32291a01":{
      "scriptId":"u3"},
    "59053a93e9204b928ace2e968b1b41b0":{
      "scriptId":"u4"},
    "0c00000feca440b4b1f40557f776e047":{
      "scriptId":"u5"},
    "13d35b8488af47ce8f2b118fc7246286":{
      "scriptId":"u6"},
    "f93e445ce4654cf8a7116a07baad4895":{
      "scriptId":"u7"},
    "d3b9888ec61741a6b46fde192c76e142":{
      "scriptId":"u8"},
    "87c21eebc3544325936c6f44306e3035":{
      "scriptId":"u9"},
    "81a47da5c99e4b9d9d8494bdd167a889":{
      "scriptId":"u10"},
    "8ddf3a3e700d4e8bab9cc550913b9c57":{
      "scriptId":"u11"},
    "c01153d4a1074e58bf2764afe214cdfc":{
      "scriptId":"u12"},
    "44e42bfe026c46f5b17c448427dad9e4":{
      "scriptId":"u13"},
    "f4848e1a27f14b3cb4be8d57167e97b7":{
      "scriptId":"u14"},
    "ab9224ed6b894189934d20539aa896a7":{
      "scriptId":"u15"},
    "b6caec8bf542462d8920d3f869f7ebf6":{
      "scriptId":"u16"},
    "988e06de8bed4217b3f0dc84da10d0c6":{
      "scriptId":"u17"},
    "0d1f59855a2644b7bdb4a7ead68ee98a":{
      "scriptId":"u18"},
    "a35663cc463e4746817d53385bd0a584":{
      "scriptId":"u19"},
    "f2a7d1c84e8c498ebcaa3e7cc2d4c8d5":{
      "scriptId":"u20"},
    "3a5447a5e7914cac8cf052b401a701b2":{
      "scriptId":"u21"},
    "0436a36ae68c4da6b227f9a1bcfdd42d":{
      "scriptId":"u22"},
    "4408f2ca2b5445eba6686fbf7f924d55":{
      "scriptId":"u23"},
    "ccd12cceb0b74a8c9e121d9a7f858ff7":{
      "scriptId":"u24"},
    "68b86313be1740388078d0a0dcea9d03":{
      "scriptId":"u25"},
    "74f8dcf02b6b44cdaec23d6ad11fcd98":{
      "scriptId":"u26"},
    "f5e8e0bd74ae4ad89d6d231030b8a2d6":{
      "scriptId":"u27"},
    "1ab4885e92ea4fd38148da7c78ff5676":{
      "scriptId":"u28"},
    "6a1c224055f4489c8df27266fd2832aa":{
      "scriptId":"u29"},
    "a05abe0050ea41a7929c4cc6ab391741":{
      "scriptId":"u30"},
    "d7dd8d724726412a98b0b78cfdc624e1":{
      "scriptId":"u31"},
    "5f8f951477554c0991e67fa61f95a88b":{
      "scriptId":"u32"},
    "30252e61ff514e45b09cf1863ba2bbd1":{
      "scriptId":"u33"}}});