$axure.loadCurrentPage({
  "url":"银行卡管理.html",
  "generationDate":new Date(1407393883577.47),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"2477a32ec60148f9bae57f3a5f82f3eb",
    "type":"Axure:Page",
    "name":"银行卡管理",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c5afec55d47d46ed8e9758398c93dbc0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":26},
            "size":{
              "width":380,
              "height":744},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4a56e5a17a04320a0c9c8dbe8cd35d5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":26},
                "size":{
                  "width":380,
                  "height":744},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账户管理/u0.png"}},
{
          "id":"e69cf16b8a2049e8a35451b844c36c48",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":51,
              "y":178},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8348ece0c0f7494982e1802e18deea45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":51,
                  "y":178},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账户管理/u2.png"}},
{
          "id":"4688642cad994b5ca527f9b0fcbec9fb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":163},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea28a92837724e52bf7c4fdadbeeb813",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":163},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账户管理/u4.png"}},
{
          "id":"fa5f917b55034f04a2cdfefeb723aa00",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":79,
              "y":250},
            "size":{
              "width":271,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efd1f89c0ccf49b7b7bffe20a07f7b05",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":79,
                  "y":250},
                "size":{
                  "width":271,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 银行卡修改",
                      "target":{
                        "targetType":"page",
                        "url":"银行卡修改.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/银行卡管理/u6.png"}},
{
          "id":"7fd954affa2e4f279299599cb1838457",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":132,
              "y":182},
            "size":{
              "width":168,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"804a2a3e946a42f39da5be3fe2c67fac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":132,
                  "y":182},
                "size":{
                  "width":168,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5b7c153683845ad9c06729cc3627d51",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":79,
              "y":480},
            "size":{
              "width":271,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a75e4b77387e4f9d98e2370985c26e26",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":79,
                  "y":480},
                "size":{
                  "width":271,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 银行卡添加",
                      "target":{
                        "targetType":"page",
                        "url":"银行卡添加.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/账户管理/u8.png"}},
{
          "id":"65e79376567b4732ac832e547abd958d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":79,
              "y":330},
            "size":{
              "width":271,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"625fee24e76941909017b2a8003a3406",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":79,
                  "y":330},
                "size":{
                  "width":271,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 银行卡修改",
                      "target":{
                        "targetType":"page",
                        "url":"银行卡修改.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/银行卡管理/u6.png"}},
{
          "id":"f8831a22a58f4c13a6d8c09c110ec107",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":79,
              "y":410},
            "size":{
              "width":271,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5f28c3889f1548a0b02320d3a6562273",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":79,
                  "y":410},
                "size":{
                  "width":271,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账户管理/u8.png"}},
{
          "id":"79e8b4400e1544f58920b8cf88afa553",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":51,
              "y":181},
            "size":{
              "width":71,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c8bd5744e23f4349bc1a445d2ed7c1b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":51,
                  "y":181},
                "size":{
                  "width":71,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 账户管理",
                      "target":{
                        "targetType":"page",
                        "url":"账户管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/银行卡管理/u16.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c5afec55d47d46ed8e9758398c93dbc0":{
      "scriptId":"u0"},
    "b4a56e5a17a04320a0c9c8dbe8cd35d5":{
      "scriptId":"u1"},
    "e69cf16b8a2049e8a35451b844c36c48":{
      "scriptId":"u2"},
    "8348ece0c0f7494982e1802e18deea45":{
      "scriptId":"u3"},
    "4688642cad994b5ca527f9b0fcbec9fb":{
      "scriptId":"u4"},
    "ea28a92837724e52bf7c4fdadbeeb813":{
      "scriptId":"u5"},
    "fa5f917b55034f04a2cdfefeb723aa00":{
      "scriptId":"u6"},
    "efd1f89c0ccf49b7b7bffe20a07f7b05":{
      "scriptId":"u7"},
    "7fd954affa2e4f279299599cb1838457":{
      "scriptId":"u8"},
    "804a2a3e946a42f39da5be3fe2c67fac":{
      "scriptId":"u9"},
    "a5b7c153683845ad9c06729cc3627d51":{
      "scriptId":"u10"},
    "a75e4b77387e4f9d98e2370985c26e26":{
      "scriptId":"u11"},
    "65e79376567b4732ac832e547abd958d":{
      "scriptId":"u12"},
    "625fee24e76941909017b2a8003a3406":{
      "scriptId":"u13"},
    "f8831a22a58f4c13a6d8c09c110ec107":{
      "scriptId":"u14"},
    "5f28c3889f1548a0b02320d3a6562273":{
      "scriptId":"u15"},
    "79e8b4400e1544f58920b8cf88afa553":{
      "scriptId":"u16"},
    "c8bd5744e23f4349bc1a445d2ed7c1b9":{
      "scriptId":"u17"}}});