$axure.loadCurrentPage({
  "url":"通讯录选择号码.html",
  "generationDate":new Date(1397786910444.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ca2c06dd52324772bd868cc130004a76",
    "type":"Axure:Page",
    "name":"通讯录选择号码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a6f7a120cc5743b09bd13a316ab7a300",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c69503fb00743299dc75c9892be1a95",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机充值首页/u0.png"}},
{
          "id":"a0a5dbc0c3044ae88a9c9f2c7476739a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":150},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc5e4075a17a46f99f08165cd5eabb2c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":150},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机充值首页/u2.png"}},
{
          "id":"6c2f6f9cc5a348f4be2fed9f5c934fc6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":37,
              "y":173},
            "size":{
              "width":73,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b72facc42048445eb3c21a0ba6233581",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":37,
                  "y":173},
                "size":{
                  "width":73,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通讯录选择号码/u4.png"}},
{
          "id":"39e0a513c0e946fd9b90acfa87f7a92d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":361},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db80dbe95a974fabbceb7eed8a37df1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":361},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机充值首页/u12.png"}},
{
          "id":"c298c7f4cfa640b8a967d0dc387fac6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":109,
              "y":173},
            "size":{
              "width":233,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40c4405ec2f84fba9570efbd62a8ae31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":109,
                  "y":173},
                "size":{
                  "width":233,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通讯录选择号码/u8.png"}},
{
          "id":"cbc4f54de0e845bba6e35f8e471da39d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":314,
              "y":184},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f9d6c2491e54fb79cf82485e4a174f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":314,
                  "y":184},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通讯录选择号码/u10.png"}},
{
          "id":"85cd195309734c9d8c7cdaed592d5b07",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":240},
            "size":{
              "width":262,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f561dafd68b41f886f9a16829f6e980",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":240},
                "size":{
                  "width":262,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通讯录选择号码/u12.png"}},
{
          "id":"2471f9ce64814e36bffe7cc2a055884a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":322},
            "size":{
              "width":262,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc68385ff8244aba9a77a6e221128603",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":322},
                "size":{
                  "width":262,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通讯录选择号码/u14.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "a6f7a120cc5743b09bd13a316ab7a300":{
      "scriptId":"u0"},
    "5c69503fb00743299dc75c9892be1a95":{
      "scriptId":"u1"},
    "a0a5dbc0c3044ae88a9c9f2c7476739a":{
      "scriptId":"u2"},
    "bc5e4075a17a46f99f08165cd5eabb2c":{
      "scriptId":"u3"},
    "6c2f6f9cc5a348f4be2fed9f5c934fc6":{
      "scriptId":"u4"},
    "b72facc42048445eb3c21a0ba6233581":{
      "scriptId":"u5"},
    "39e0a513c0e946fd9b90acfa87f7a92d":{
      "scriptId":"u6"},
    "db80dbe95a974fabbceb7eed8a37df1d":{
      "scriptId":"u7"},
    "c298c7f4cfa640b8a967d0dc387fac6e":{
      "scriptId":"u8"},
    "40c4405ec2f84fba9570efbd62a8ae31":{
      "scriptId":"u9"},
    "cbc4f54de0e845bba6e35f8e471da39d":{
      "scriptId":"u10"},
    "3f9d6c2491e54fb79cf82485e4a174f8":{
      "scriptId":"u11"},
    "85cd195309734c9d8c7cdaed592d5b07":{
      "scriptId":"u12"},
    "6f561dafd68b41f886f9a16829f6e980":{
      "scriptId":"u13"},
    "2471f9ce64814e36bffe7cc2a055884a":{
      "scriptId":"u14"},
    "cc68385ff8244aba9a77a6e221128603":{
      "scriptId":"u15"}}});