$axure.loadCurrentPage({
  "url":"客房详情页.html",
  "generationDate":new Date(1416378074343.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"rl_date",
"rl_day"],
  "page":{
    "packageId":"7743cf677cf74e8bb01ced736eefd695",
    "type":"Axure:Page",
    "name":"客房详情页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d23888fd425b4b4688347366cd8e4eba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":116},
            "size":{
              "width":8,
              "height":36},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b7c25c9d27f4540878cb0a5620019e0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":116},
                "size":{
                  "width":8,
                  "height":36},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u0.png"}},
{
          "id":"6b4e6959c85049f385682706457bb6b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":192},
            "size":{
              "width":8,
              "height":27},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afe4e64f46d34714851797be154bc691",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":192},
                "size":{
                  "width":8,
                  "height":27},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u2.png"}},
{
          "id":"365a9d1b96074d289e585fa67c7f1127",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":255},
            "size":{
              "width":8,
              "height":27},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e6e2fe2b67284f98b914c6aaeb63e7ca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":255},
                "size":{
                  "width":8,
                  "height":27},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u2.png"}},
{
          "id":"9ab920a985e947b9a141b23dd4fca6cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":0},
            "size":{
              "width":60,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9bd14ea9152446d1b30ddbd12def8b89",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":259,
                  "y":0},
                "size":{
                  "width":60,
                  "height":10},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u6.png"}},
{
          "id":"f336fe887a8e489f842bb073878b4888",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":6},
            "size":{
              "width":372,
              "height":796},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"52"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c290c47b4f9444784ffbe6c0fc3fa00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":6},
                "size":{
                  "width":372,
                  "height":796},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"52"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u8.png"}},
{
          "id":"c299b48f599947e2bbecb0a9f2dd9a44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":32,
              "y":120},
            "size":{
              "width":320,
              "height":568},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0092daeb76fd4160b410622d6216df6c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":32,
                  "y":120},
                "size":{
                  "width":320,
                  "height":568},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店预订/u10.png"}},
{
          "id":"9c6542e772da46d784d6ade7a91459dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":157,
              "y":66},
            "size":{
              "width":70,
              "height":14},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"35"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e8ec1ce700b34213801b6dc2dc389c1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":157,
                  "y":66},
                "size":{
                  "width":70,
                  "height":14},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"35"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店预订/u12.png"}},
{
          "id":"937c5b4828a844289633919e46543f1c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":185,
              "y":40},
            "size":{
              "width":14,
              "height":14},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"35"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cc18739a85b04629bd207cdf310b2bf4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":185,
                  "y":40},
                "size":{
                  "width":14,
                  "height":14},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"35"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店预订/u14.png"}},
{
          "id":"03a8a65c59df434a9b114e581298fde3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":156,
              "y":704},
            "size":{
              "width":72,
              "height":72},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"35"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d4d723d562104eff8c5cb7e05bcdb9d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":156,
                  "y":704},
                "size":{
                  "width":72,
                  "height":72},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"35"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店预订/u16.png"}},
{
          "id":"643f132a1caf46a4ad572373bf870ea3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":124},
            "size":{
              "width":318,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"91b0d33722324009bebae28e9a107d24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":124},
                "size":{
                  "width":318,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店预订/u42.png"}},
{
          "id":"2a95b49d363941afb2e28bb5f33648f5",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":144,
              "y":135},
            "size":{
              "width":94,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"30da5614b49d4ca0b6f320e75e6d7cba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":144,
                  "y":135},
                "size":{
                  "width":94,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"630d96a7f0784bf0b54c28696b5119ba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":137},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"68716934e9aa48e5b884abb566d35285",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":137},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 酒店详情页",
                      "target":{
                        "targetType":"page",
                        "url":"酒店详情页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/酒店预订/u46.png"}},
{
          "id":"ee47774b14f64074aeacf335c98bfb85",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":180},
            "size":{
              "width":296,
              "height":200}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c627d832af24a9b88199dd1034f88e6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":180},
                "size":{
                  "width":296,
                  "height":200}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/客房详情页/u24.png"}},
{
          "id":"7679a117825f4c9aa74d2975193d0410",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":44,
              "y":424},
            "size":{
              "width":57,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a5f468f6de6497da97d1ab8de1a9ba5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":44,
                  "y":424},
                "size":{
                  "width":57,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9d7e9912470848c695d49f117f06c80a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":111,
              "y":421},
            "size":{
              "width":7,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d329939cb6004fde959a64851191885b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":111,
                  "y":421},
                "size":{
                  "width":7,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98fe03fc7a9e4e788e5698bdab21374d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":44,
              "y":443},
            "size":{
              "width":51,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c320c99b727744d184744519d57ff9d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":44,
                  "y":443},
                "size":{
                  "width":51,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b83f7088d126462aa6f9472342d5ae11",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":44,
              "y":500},
            "size":{
              "width":45,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14b12408ae7b44d89c9609e51d767b6e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":500},
                "size":{
                  "width":45,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"83229dd122f64b3f8c0c561c12a58091",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":44,
              "y":461},
            "size":{
              "width":124,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2efe612cd47496e8c366bfcbb93b420",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":44,
                  "y":461},
                "size":{
                  "width":124,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"628a314de7984002b65f3c068787cd09",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":44,
              "y":481},
            "size":{
              "width":67,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eac629ee2e1f4b0186f822644659c83e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":44,
                  "y":481},
                "size":{
                  "width":67,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"af8b0f2287c849248f33f270ea36324f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"11px",
            "location":{
              "x":113,
              "y":500},
            "size":{
              "width":38,
              "height":14}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"757d533381b84b738ce949d4e1e94a3d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"11px",
                "location":{
                  "x":113,
                  "y":500},
                "size":{
                  "width":38,
                  "height":14}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81adb842bdc84fd7bb48b7d99cc63194",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":44,
              "y":524},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"134cdda906ee438892f199a11a1451a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":44,
                  "y":524},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c475c3cd8c24551a7e7fb9f891054e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":79,
              "y":524},
            "size":{
              "width":259,
              "height":96}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8f76b2aba614bc89a907458896bf52f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":79,
                  "y":524},
                "size":{
                  "width":259,
                  "height":96}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4aaf0708d470409b8d15dc917d1b8587",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":44,
              "y":644},
            "size":{
              "width":19,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38802452724744a4b47b2dbeccd05cb7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":44,
                  "y":644},
                "size":{
                  "width":19,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b6ec0f7e50fd4b419784a2b2d60b65d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":63,
              "y":642},
            "size":{
              "width":45,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc36576760ff42229239128b83c69e2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":63,
                  "y":642},
                "size":{
                  "width":45,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"11fcb3608cf841e49fdd5582ef4fbf58",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"700",
            "location":{
              "x":238,
              "y":641},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订单确认页 - 预订",
                      "target":{
                        "targetType":"page",
                        "url":"订单确认页_-_预订.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"ab1f6ee6154b441bbafd467c93f7eb48",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":145.5,
              "y":390},
            "size":{
              "width":22,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"157ca573ea734cf5b70b93c5aa35ec72",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":145.5,
                  "y":390},
                "size":{
                  "width":22,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"368f984cb8cc46fdb5b72caf9f99510e",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":184.5,
              "y":390},
            "size":{
              "width":22,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d5f85bd750434aad908ba7a3190ef57c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":184.5,
                  "y":390},
                "size":{
                  "width":22,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"228aada82ea644449826814b00146fc4",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "location":{
              "x":216.5,
              "y":390},
            "size":{
              "width":22,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e3e5212190046e0846495224b081e17",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":216.5,
                  "y":390},
                "size":{
                  "width":22,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"81fd8db6b4ea4a58bd7d461a0053b1aa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":44,
              "y":574},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3f681a303f04afb91a0fdd6bc146702",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":44,
                  "y":574},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "d23888fd425b4b4688347366cd8e4eba":{
      "scriptId":"u0"},
    "5b7c25c9d27f4540878cb0a5620019e0":{
      "scriptId":"u1"},
    "6b4e6959c85049f385682706457bb6b9":{
      "scriptId":"u2"},
    "afe4e64f46d34714851797be154bc691":{
      "scriptId":"u3"},
    "365a9d1b96074d289e585fa67c7f1127":{
      "scriptId":"u4"},
    "e6e2fe2b67284f98b914c6aaeb63e7ca":{
      "scriptId":"u5"},
    "9ab920a985e947b9a141b23dd4fca6cd":{
      "scriptId":"u6"},
    "9bd14ea9152446d1b30ddbd12def8b89":{
      "scriptId":"u7"},
    "f336fe887a8e489f842bb073878b4888":{
      "scriptId":"u8"},
    "9c290c47b4f9444784ffbe6c0fc3fa00":{
      "scriptId":"u9"},
    "c299b48f599947e2bbecb0a9f2dd9a44":{
      "scriptId":"u10"},
    "0092daeb76fd4160b410622d6216df6c":{
      "scriptId":"u11"},
    "9c6542e772da46d784d6ade7a91459dc":{
      "scriptId":"u12"},
    "e8ec1ce700b34213801b6dc2dc389c1f":{
      "scriptId":"u13"},
    "937c5b4828a844289633919e46543f1c":{
      "scriptId":"u14"},
    "cc18739a85b04629bd207cdf310b2bf4":{
      "scriptId":"u15"},
    "03a8a65c59df434a9b114e581298fde3":{
      "scriptId":"u16"},
    "d4d723d562104eff8c5cb7e05bcdb9d1":{
      "scriptId":"u17"},
    "643f132a1caf46a4ad572373bf870ea3":{
      "scriptId":"u18"},
    "91b0d33722324009bebae28e9a107d24":{
      "scriptId":"u19"},
    "2a95b49d363941afb2e28bb5f33648f5":{
      "scriptId":"u20"},
    "30da5614b49d4ca0b6f320e75e6d7cba":{
      "scriptId":"u21"},
    "630d96a7f0784bf0b54c28696b5119ba":{
      "scriptId":"u22"},
    "68716934e9aa48e5b884abb566d35285":{
      "scriptId":"u23"},
    "ee47774b14f64074aeacf335c98bfb85":{
      "scriptId":"u24"},
    "9c627d832af24a9b88199dd1034f88e6":{
      "scriptId":"u25"},
    "7679a117825f4c9aa74d2975193d0410":{
      "scriptId":"u26"},
    "9a5f468f6de6497da97d1ab8de1a9ba5":{
      "scriptId":"u27"},
    "9d7e9912470848c695d49f117f06c80a":{
      "scriptId":"u28"},
    "d329939cb6004fde959a64851191885b":{
      "scriptId":"u29"},
    "98fe03fc7a9e4e788e5698bdab21374d":{
      "scriptId":"u30"},
    "c320c99b727744d184744519d57ff9d0":{
      "scriptId":"u31"},
    "b83f7088d126462aa6f9472342d5ae11":{
      "scriptId":"u32"},
    "14b12408ae7b44d89c9609e51d767b6e":{
      "scriptId":"u33"},
    "83229dd122f64b3f8c0c561c12a58091":{
      "scriptId":"u34"},
    "a2efe612cd47496e8c366bfcbb93b420":{
      "scriptId":"u35"},
    "628a314de7984002b65f3c068787cd09":{
      "scriptId":"u36"},
    "eac629ee2e1f4b0186f822644659c83e":{
      "scriptId":"u37"},
    "af8b0f2287c849248f33f270ea36324f":{
      "scriptId":"u38"},
    "757d533381b84b738ce949d4e1e94a3d":{
      "scriptId":"u39"},
    "81adb842bdc84fd7bb48b7d99cc63194":{
      "scriptId":"u40"},
    "134cdda906ee438892f199a11a1451a7":{
      "scriptId":"u41"},
    "9c475c3cd8c24551a7e7fb9f891054e4":{
      "scriptId":"u42"},
    "f8f76b2aba614bc89a907458896bf52f":{
      "scriptId":"u43"},
    "4aaf0708d470409b8d15dc917d1b8587":{
      "scriptId":"u44"},
    "38802452724744a4b47b2dbeccd05cb7":{
      "scriptId":"u45"},
    "b6ec0f7e50fd4b419784a2b2d60b65d6":{
      "scriptId":"u46"},
    "bc36576760ff42229239128b83c69e2f":{
      "scriptId":"u47"},
    "11fcb3608cf841e49fdd5582ef4fbf58":{
      "scriptId":"u48"},
    "ab1f6ee6154b441bbafd467c93f7eb48":{
      "scriptId":"u49"},
    "157ca573ea734cf5b70b93c5aa35ec72":{
      "scriptId":"u50"},
    "368f984cb8cc46fdb5b72caf9f99510e":{
      "scriptId":"u51"},
    "d5f85bd750434aad908ba7a3190ef57c":{
      "scriptId":"u52"},
    "228aada82ea644449826814b00146fc4":{
      "scriptId":"u53"},
    "8e3e5212190046e0846495224b081e17":{
      "scriptId":"u54"},
    "81fd8db6b4ea4a58bd7d461a0053b1aa":{
      "scriptId":"u55"},
    "d3f681a303f04afb91a0fdd6bc146702":{
      "scriptId":"u56"}}});