$axure.loadCurrentPage({
  "url":"代理商分配授权码.html",
  "generationDate":new Date(1416631107375),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"66f25c3f90e84bd6b6c625aa7c555123",
    "type":"Axure:Page",
    "name":"代理商分配授权码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"f2224b1254594005929e32f48cf35d30",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":20},
            "size":{
              "width":380,
              "height":744},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef034a122cfb405c87bd012bf8e5b6be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":20},
                "size":{
                  "width":380,
                  "height":744},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买授权码/u0.png"}},
{
          "id":"f8a00e8ba35d4fff9cfa58fb26884bbf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":163},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a96cf75000e24ad58a071749db203cc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":163},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买授权码/u2.png"}},
{
          "id":"891c19ecfe1f4f6387c5602196b4b503",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":166.5,
              "y":193},
            "size":{
              "width":177,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3746b5eb27604bedb7a97472e26cecd2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":166.5,
                  "y":193},
                "size":{
                  "width":177,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f897b0b3addc4464b40e362dc4f731e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":70,
              "y":360},
            "size":{
              "width":300,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f666b06c6d674f19b78529eca7fe8944",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":70,
                  "y":360},
                "size":{
                  "width":300,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/代理商分配授权码/u6.png"}},
{
          "id":"ff651c157d32449fb4a81d92e4670c72",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":70,
              "y":263},
            "size":{
              "width":300,
              "height":87}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c994f250d6fd426e9cfc22b2ad9fd43b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":70,
                  "y":263},
                "size":{
                  "width":300,
                  "height":87}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/代理商分配授权码/u8.png"}},
{
          "id":"b7b4c32b35654af788786603c612ee61",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":80,
              "y":460},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9cd443640ed462fad966a4e39420781",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":80,
                  "y":460},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/代理商分配授权码/u10.png"}},
{
          "id":"03109b7cfe7b423f81ceb30e04dba598",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":440},
            "size":{
              "width":300,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/代理商分配授权码/u12_line.png"}},
{
          "id":"5f2f1bebc8154b0586b38f73b01b421e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":150,
              "y":460},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36199fb767fa4ca3a796116eea1ca2d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":150,
                  "y":460},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/代理商分配授权码/u10.png"}},
{
          "id":"3d373267ed6d4a2aa3cc12f1215e4103",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":220,
              "y":460},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"082886b4966b4647af7386758258e310",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":220,
                  "y":460},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/代理商分配授权码/u10.png"}},
{
          "id":"fc433715859b485db3c261293354dc38",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":290,
              "y":460},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4801d354766499a9c3dda9c03bc77bc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":290,
                  "y":460},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 授权码出售",
                      "target":{
                        "targetType":"page",
                        "url":"授权码出售.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/代理商分配授权码/u10.png"}},
{
          "id":"aad9dda5463b4052a95cf0d7150a2216",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "location":{
              "x":70,
              "y":203},
            "size":{
              "width":86,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1db5c9d3f3ac46c1a29ded870037805a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "location":{
                  "x":70,
                  "y":203},
                "size":{
                  "width":86,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6786bc08897f43dca202fba764bada41",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":80,
              "y":530},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f018be1a54e845d2a732bb339fb4dca3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":80,
                  "y":530},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/代理商分配授权码/u10.png"}},
{
          "id":"4af8caad95934a36a0c4aca205dc4fb4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":150,
              "y":530},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ab7ffb3f67554249b54caf77cc42a92b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":150,
                  "y":530},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/代理商分配授权码/u10.png"}},
{
          "id":"529483374baa4d37814ea6c976d3d5c4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":220,
              "y":530},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e21607a05c5f42eabd819b72f29005ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":220,
                  "y":530},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/代理商分配授权码/u10.png"}},
{
          "id":"08b1981241a24894b19b909c120f109e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":290,
              "y":530},
            "size":{
              "width":70,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc9565fa3ea548b0b1afa8fbfa5b2bf8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":290,
                  "y":530},
                "size":{
                  "width":70,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/代理商分配授权码/u10.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "f2224b1254594005929e32f48cf35d30":{
      "scriptId":"u0"},
    "ef034a122cfb405c87bd012bf8e5b6be":{
      "scriptId":"u1"},
    "f8a00e8ba35d4fff9cfa58fb26884bbf":{
      "scriptId":"u2"},
    "a96cf75000e24ad58a071749db203cc6":{
      "scriptId":"u3"},
    "891c19ecfe1f4f6387c5602196b4b503":{
      "scriptId":"u4"},
    "3746b5eb27604bedb7a97472e26cecd2":{
      "scriptId":"u5"},
    "f897b0b3addc4464b40e362dc4f731e1":{
      "scriptId":"u6"},
    "f666b06c6d674f19b78529eca7fe8944":{
      "scriptId":"u7"},
    "ff651c157d32449fb4a81d92e4670c72":{
      "scriptId":"u8"},
    "c994f250d6fd426e9cfc22b2ad9fd43b":{
      "scriptId":"u9"},
    "b7b4c32b35654af788786603c612ee61":{
      "scriptId":"u10"},
    "d9cd443640ed462fad966a4e39420781":{
      "scriptId":"u11"},
    "03109b7cfe7b423f81ceb30e04dba598":{
      "scriptId":"u12"},
    "5f2f1bebc8154b0586b38f73b01b421e":{
      "scriptId":"u13"},
    "36199fb767fa4ca3a796116eea1ca2d1":{
      "scriptId":"u14"},
    "3d373267ed6d4a2aa3cc12f1215e4103":{
      "scriptId":"u15"},
    "082886b4966b4647af7386758258e310":{
      "scriptId":"u16"},
    "fc433715859b485db3c261293354dc38":{
      "scriptId":"u17"},
    "e4801d354766499a9c3dda9c03bc77bc":{
      "scriptId":"u18"},
    "aad9dda5463b4052a95cf0d7150a2216":{
      "scriptId":"u19"},
    "1db5c9d3f3ac46c1a29ded870037805a":{
      "scriptId":"u20"},
    "6786bc08897f43dca202fba764bada41":{
      "scriptId":"u21"},
    "f018be1a54e845d2a732bb339fb4dca3":{
      "scriptId":"u22"},
    "4af8caad95934a36a0c4aca205dc4fb4":{
      "scriptId":"u23"},
    "ab7ffb3f67554249b54caf77cc42a92b":{
      "scriptId":"u24"},
    "529483374baa4d37814ea6c976d3d5c4":{
      "scriptId":"u25"},
    "e21607a05c5f42eabd819b72f29005ea":{
      "scriptId":"u26"},
    "08b1981241a24894b19b909c120f109e":{
      "scriptId":"u27"},
    "fc9565fa3ea548b0b1afa8fbfa5b2bf8":{
      "scriptId":"u28"}}});