$axure.loadCurrentPage({
  "url":"城市列表.html",
  "generationDate":new Date(1405580873937.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"d6b193fc58b24ccea9e94633c7c25ef8",
    "type":"Axure:Page",
    "name":"城市列表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7295082c9bd54178adab09613d75011f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d65f41e24204c9f91efe3cfd7ae908e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机票酒店预定/u0.png"}},
{
          "id":"b3a6206eec4c43f2b3b0053df3f05288",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":33,
              "y":130},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71e24720d3604981bd6a1669a1db0f48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":33,
                  "y":130},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机票酒店预定/u4.png"}},
{
          "id":"804995acabc14c2090a99d19272d7565",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"21px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":145,
              "y":141},
            "size":{
              "width":95,
              "height":50},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"439fec7cffa1473e9851af11f0d3a858",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"21px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":145,
                  "y":141},
                "size":{
                  "width":95,
                  "height":50},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b87e6dbe52a14c428d7f08c53015e2ba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":33,
              "y":117},
            "size":{
              "width":320,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16d211503fc24def8d4bb04b45c3c758",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":33,
                  "y":117},
                "size":{
                  "width":320,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机票酒店预定/u2.png"}},
{
          "id":"79208915147d4041826c21ada8c656ab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":40,
              "y":140},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a753a28cb9ab435a8454622e9069dfea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":40,
                  "y":140},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 机票预定",
                      "target":{
                        "targetType":"page",
                        "url":"机票预定.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/城市列表/u8.png"}},
{
          "id":"16f85264f2414298ba02fcab001cdb6d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":338,
              "y":294},
            "size":{
              "width":10,
              "height":296},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86b41a866bd34d63b01cfc7cfdf4dbf2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":338,
                  "y":294},
                "size":{
                  "width":10,
                  "height":296},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/城市列表/u10.png"}},
{
          "id":"ba07606e2ca34c7ea8fde665cc4194db",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":41,
              "y":249},
            "size":{
              "width":308,
              "height":35},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b70e79d34a7450e8023ecade5118d74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":41,
                  "y":249},
                "size":{
                  "width":308,
                  "height":35},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/城市列表/u12.png"}},
{
          "id":"ac0224d2d3df453db036500ae2110626",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":107,
              "y":258},
            "size":{
              "width":15,
              "height":15},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c2873039cae4da892924d0274fae356",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":107,
                  "y":258},
                "size":{
                  "width":15,
                  "height":15},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/城市列表/u14.png"}},
{
          "id":"ab55e81a8cab4979a4a373fff9723f52",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":133,
              "y":259},
            "size":{
              "width":150,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80a676ed2a8a4a27b621113eca73c0bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":133,
                  "y":259},
                "size":{
                  "width":150,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"728e193ace534161ab542fc29ef17234",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4F4F4F,
              "opacity":1},
            "location":{
              "x":41,
              "y":338},
            "size":{
              "width":296,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bad41eb00204e62b5a1793855563e79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4F4F4F,
                  "opacity":1},
                "location":{
                  "x":41,
                  "y":338},
                "size":{
                  "width":296,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5a0bc6e7237647a8ac87143b11d12ca6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":31,
              "y":370},
            "size":{
              "width":295,
              "height":85},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC8C8C8}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc6e6956b34c4023a5d0be50b6223ffa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":31,
                  "y":370},
                "size":{
                  "width":295,
                  "height":85},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC8C8C8}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/城市列表/u20.png"}},
{
          "id":"477f3eecd73f47c48a53931f85597702",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":45,
              "y":379},
            "size":{
              "width":136,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01a70ab044ce4b23b7f51d2120c6c1e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":45,
                  "y":379},
                "size":{
                  "width":136,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf398a1b64fb4a3c97dc0aedc34a66f8",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":45,
              "y":408},
            "size":{
              "width":283,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC8C8C8}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/城市列表/u24_line.png"}},
{
          "id":"95a13bac32c841599241b9f3e7922afa",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":45,
              "y":421},
            "size":{
              "width":136,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7aca74cb84e24a7fa9993a2c04761c96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":45,
                  "y":421},
                "size":{
                  "width":136,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f31103b7dddb411991dba15c3c97687e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF4F4F4F,
              "opacity":1},
            "location":{
              "x":41,
              "y":455},
            "size":{
              "width":274,
              "height":22},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"601432c03786485f9c3d31bd047ff0f2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF4F4F4F,
                  "opacity":1},
                "location":{
                  "x":41,
                  "y":455},
                "size":{
                  "width":274,
                  "height":22},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"12cf767f1a384573a14fdd5db5025a2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":487},
            "size":{
              "width":296,
              "height":168},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC8C8C8}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92b2ef36d6274a7898d80c1ad9ba3549",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":487},
                "size":{
                  "width":296,
                  "height":168},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFC8C8C8}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/城市列表/u29.png"}},
{
          "id":"5083f12045674a2c80640651161850e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":43,
              "y":495},
            "size":{
              "width":126,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d796d4f28e02409c9a9830c35a9edf6f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":43,
                  "y":495},
                "size":{
                  "width":126,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b2ab824957164e5fb1f3178d93559dad",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":524},
            "size":{
              "width":282,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC8C8C8}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/城市列表/u33_line.png"}},
{
          "id":"6934598580a24e0ab782cb69af5e95cc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":43,
              "y":537},
            "size":{
              "width":126,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc38007945814ea09f1c6b5bb13587ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":43,
                  "y":537},
                "size":{
                  "width":126,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8f2fd14533a841628b012a9cc588a020",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":566},
            "size":{
              "width":282,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC8C8C8}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/城市列表/u33_line.png"}},
{
          "id":"f355a38091984218af6313804e1936d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":43,
              "y":579},
            "size":{
              "width":126,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7adf3e6e25b441b79f4459728b225e5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":43,
                  "y":579},
                "size":{
                  "width":126,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9c904782f487496ca26c5daaf67ec26f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":43,
              "y":608},
            "size":{
              "width":282,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFC8C8C8}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/城市列表/u33_line.png"}},
{
          "id":"1bd69f298b554b1d9aee2b2010a702c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":43,
              "y":621},
            "size":{
              "width":126,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aea03c7f41864550a4e2c5a3250f858e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":43,
                  "y":621},
                "size":{
                  "width":126,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"01dd5df33deb4d58b5f1e1269bb9b263",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":373,
              "y":1051},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfcca0a179884e7781b377da780e3ac7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":373,
                  "y":1051},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/城市列表/u42.png"}},
{
          "id":"3300bec2d9a94c51abc2766b417da6e3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":51,
              "y":191},
            "size":{
              "width":130,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46617c42d8ea4671baba5621d5dfe770",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":51,
                  "y":191},
                "size":{
                  "width":130,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机票预定/u12.png"}},
{
          "id":"4c05b5bec5aa49649f57eb11c5717a95",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":181,
              "y":191},
            "size":{
              "width":130,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f28e7a931b1415b9c1410e1ddbf6f11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":181,
                  "y":191},
                "size":{
                  "width":130,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机票预定/u12.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "7295082c9bd54178adab09613d75011f":{
      "scriptId":"u0"},
    "5d65f41e24204c9f91efe3cfd7ae908e":{
      "scriptId":"u1"},
    "b3a6206eec4c43f2b3b0053df3f05288":{
      "scriptId":"u2"},
    "71e24720d3604981bd6a1669a1db0f48":{
      "scriptId":"u3"},
    "804995acabc14c2090a99d19272d7565":{
      "scriptId":"u4"},
    "439fec7cffa1473e9851af11f0d3a858":{
      "scriptId":"u5"},
    "b87e6dbe52a14c428d7f08c53015e2ba":{
      "scriptId":"u6"},
    "16d211503fc24def8d4bb04b45c3c758":{
      "scriptId":"u7"},
    "79208915147d4041826c21ada8c656ab":{
      "scriptId":"u8"},
    "a753a28cb9ab435a8454622e9069dfea":{
      "scriptId":"u9"},
    "16f85264f2414298ba02fcab001cdb6d":{
      "scriptId":"u10"},
    "86b41a866bd34d63b01cfc7cfdf4dbf2":{
      "scriptId":"u11"},
    "ba07606e2ca34c7ea8fde665cc4194db":{
      "scriptId":"u12"},
    "5b70e79d34a7450e8023ecade5118d74":{
      "scriptId":"u13"},
    "ac0224d2d3df453db036500ae2110626":{
      "scriptId":"u14"},
    "9c2873039cae4da892924d0274fae356":{
      "scriptId":"u15"},
    "ab55e81a8cab4979a4a373fff9723f52":{
      "scriptId":"u16"},
    "80a676ed2a8a4a27b621113eca73c0bb":{
      "scriptId":"u17"},
    "728e193ace534161ab542fc29ef17234":{
      "scriptId":"u18"},
    "4bad41eb00204e62b5a1793855563e79":{
      "scriptId":"u19"},
    "5a0bc6e7237647a8ac87143b11d12ca6":{
      "scriptId":"u20"},
    "dc6e6956b34c4023a5d0be50b6223ffa":{
      "scriptId":"u21"},
    "477f3eecd73f47c48a53931f85597702":{
      "scriptId":"u22"},
    "01a70ab044ce4b23b7f51d2120c6c1e8":{
      "scriptId":"u23"},
    "bf398a1b64fb4a3c97dc0aedc34a66f8":{
      "scriptId":"u24"},
    "95a13bac32c841599241b9f3e7922afa":{
      "scriptId":"u25"},
    "7aca74cb84e24a7fa9993a2c04761c96":{
      "scriptId":"u26"},
    "f31103b7dddb411991dba15c3c97687e":{
      "scriptId":"u27"},
    "601432c03786485f9c3d31bd047ff0f2":{
      "scriptId":"u28"},
    "12cf767f1a384573a14fdd5db5025a2c":{
      "scriptId":"u29"},
    "92b2ef36d6274a7898d80c1ad9ba3549":{
      "scriptId":"u30"},
    "5083f12045674a2c80640651161850e0":{
      "scriptId":"u31"},
    "d796d4f28e02409c9a9830c35a9edf6f":{
      "scriptId":"u32"},
    "b2ab824957164e5fb1f3178d93559dad":{
      "scriptId":"u33"},
    "6934598580a24e0ab782cb69af5e95cc":{
      "scriptId":"u34"},
    "fc38007945814ea09f1c6b5bb13587ff":{
      "scriptId":"u35"},
    "8f2fd14533a841628b012a9cc588a020":{
      "scriptId":"u36"},
    "f355a38091984218af6313804e1936d8":{
      "scriptId":"u37"},
    "7adf3e6e25b441b79f4459728b225e5f":{
      "scriptId":"u38"},
    "9c904782f487496ca26c5daaf67ec26f":{
      "scriptId":"u39"},
    "1bd69f298b554b1d9aee2b2010a702c1":{
      "scriptId":"u40"},
    "aea03c7f41864550a4e2c5a3250f858e":{
      "scriptId":"u41"},
    "01dd5df33deb4d58b5f1e1269bb9b263":{
      "scriptId":"u42"},
    "bfcca0a179884e7781b377da780e3ac7":{
      "scriptId":"u43"},
    "3300bec2d9a94c51abc2766b417da6e3":{
      "scriptId":"u44"},
    "46617c42d8ea4671baba5621d5dfe770":{
      "scriptId":"u45"},
    "4c05b5bec5aa49649f57eb11c5717a95":{
      "scriptId":"u46"},
    "0f28e7a931b1415b9c1410e1ddbf6f11":{
      "scriptId":"u47"}}});