$axure.loadCurrentPage({
  "url":"支付校验（超限）_2.html",
  "generationDate":new Date(1409800781718.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"992ce210fbcd4c1883678b6a98daa302",
    "type":"Axure:Page",
    "name":"支付校验（超限）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a273ef03d70d4bc59907ea01a95c2d64",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":26},
            "size":{
              "width":380,
              "height":704},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b9254beeea947eb933b95034211c330",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":26},
                "size":{
                  "width":380,
                  "height":704},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息设置/u0.png"}},
{
          "id":"215cc9b19c784b24a510e7dfdacaa0ca",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":51,
              "y":178},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5fee5a59012641a2bb91afbe5eb21e3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":51,
                  "y":178},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息设置/u2.png"}},
{
          "id":"824a91c9d1da46018021d8d9c929e460",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":163},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2fe012017a9d4da4a84f2c05050d99b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":163},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息设置/u4.png"}},
{
          "id":"6721db213c044a3099c3aa7b1e9314b6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":150,
              "y":182},
            "size":{
              "width":168,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"036c2090b26b4525b6cf113e6225bf30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":150,
                  "y":182},
                "size":{
                  "width":168,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"841730974f574bad9f172aec9ae176fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":160,
              "y":560},
            "size":{
              "width":90,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"92a20cb6272e4e4fb62a661dd62a63e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":160,
                  "y":560},
                "size":{
                  "width":90,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/话费充值/u8.png"}},
{
          "id":"642990cd85314592a054694a7413162a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":270},
            "size":{
              "width":260,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8806485ae82f4e27b9608fd426383fe9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":270},
                "size":{
                  "width":260,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息设置/u8.png"}},
{
          "id":"4b4df9d7d52e4689b87164a11b2d4048",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":300},
            "size":{
              "width":260,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e43dd95e1aa24331aeacebe65936f600",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":300},
                "size":{
                  "width":260,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息设置/u8.png"}},
{
          "id":"98470c1b10094110a7a972b70e99f1f5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":330},
            "size":{
              "width":260,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfd52844192d405fbc4b67d48899aa59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":330},
                "size":{
                  "width":260,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息设置/u8.png"}},
{
          "id":"6d650c23c9624fd78162cb2d2676e0a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":360},
            "size":{
              "width":260,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"011bb1f0d844401880dce99118678afa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":360},
                "size":{
                  "width":260,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息设置/u8.png"}},
{
          "id":"631c8f8978a141aab91f740fb5b1d9c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":80,
              "y":244},
            "size":{
              "width":120,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"313d78d7ba634f45b0005b09837f0644",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":80,
                  "y":244},
                "size":{
                  "width":120,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bcd5774df71a4361b09a5f634a40c073",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":85,
              "y":400},
            "size":{
              "width":250,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49068ebb66244a4390e1309be299985b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":85,
                  "y":400},
                "size":{
                  "width":250,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付校验（进入风控）_2/u20.png"}},
{
          "id":"e0bcdf96cb2f499c850d0a3ad4b9d1e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":160,
              "y":510},
            "size":{
              "width":90,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b3563f5f03447b4b65b1f1240ee6a35",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":160,
                  "y":510},
                "size":{
                  "width":90,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 转账汇款（超级转账）",
                      "target":{
                        "targetType":"page",
                        "url":"转账汇款（超级转账）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/话费充值/u8.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "a273ef03d70d4bc59907ea01a95c2d64":{
      "scriptId":"u0"},
    "5b9254beeea947eb933b95034211c330":{
      "scriptId":"u1"},
    "215cc9b19c784b24a510e7dfdacaa0ca":{
      "scriptId":"u2"},
    "5fee5a59012641a2bb91afbe5eb21e3b":{
      "scriptId":"u3"},
    "824a91c9d1da46018021d8d9c929e460":{
      "scriptId":"u4"},
    "2fe012017a9d4da4a84f2c05050d99b8":{
      "scriptId":"u5"},
    "6721db213c044a3099c3aa7b1e9314b6":{
      "scriptId":"u6"},
    "036c2090b26b4525b6cf113e6225bf30":{
      "scriptId":"u7"},
    "841730974f574bad9f172aec9ae176fb":{
      "scriptId":"u8"},
    "92a20cb6272e4e4fb62a661dd62a63e9":{
      "scriptId":"u9"},
    "642990cd85314592a054694a7413162a":{
      "scriptId":"u10"},
    "8806485ae82f4e27b9608fd426383fe9":{
      "scriptId":"u11"},
    "4b4df9d7d52e4689b87164a11b2d4048":{
      "scriptId":"u12"},
    "e43dd95e1aa24331aeacebe65936f600":{
      "scriptId":"u13"},
    "98470c1b10094110a7a972b70e99f1f5":{
      "scriptId":"u14"},
    "cfd52844192d405fbc4b67d48899aa59":{
      "scriptId":"u15"},
    "6d650c23c9624fd78162cb2d2676e0a4":{
      "scriptId":"u16"},
    "011bb1f0d844401880dce99118678afa":{
      "scriptId":"u17"},
    "631c8f8978a141aab91f740fb5b1d9c0":{
      "scriptId":"u18"},
    "313d78d7ba634f45b0005b09837f0644":{
      "scriptId":"u19"},
    "bcd5774df71a4361b09a5f634a40c073":{
      "scriptId":"u20"},
    "49068ebb66244a4390e1309be299985b":{
      "scriptId":"u21"},
    "e0bcdf96cb2f499c850d0a3ad4b9d1e9":{
      "scriptId":"u22"},
    "9b3563f5f03447b4b65b1f1240ee6a35":{
      "scriptId":"u23"}}});