$axure.loadCurrentPage({
  "url":"首页面.html",
  "generationDate":new Date(1416378071906.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"rl_date",
"rl_day"],
  "page":{
    "packageId":"54f18865ce654fbbbbc2e088e499b51a",
    "type":"Axure:Page",
    "name":"首页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9b0ec74c9b544ce29e6a6e460a86ecbf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":116},
            "size":{
              "width":8,
              "height":36},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"49e5bb950f3f4bfdb577aef278004c58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":116},
                "size":{
                  "width":8,
                  "height":36},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u0.png"}},
{
          "id":"51c8014765e14bf388ec09b59e08d24c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":192},
            "size":{
              "width":8,
              "height":27},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb8dd99d25c14c598119f8ef8be8757c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":192},
                "size":{
                  "width":8,
                  "height":27},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u2.png"}},
{
          "id":"348797d5864d4d8fbe4ae751a07ee1ed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":255},
            "size":{
              "width":8,
              "height":27},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a52e018b2694bdd8d740b3c8ce1d8d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":255},
                "size":{
                  "width":8,
                  "height":27},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u2.png"}},
{
          "id":"defc5e7fbed840eea7b86ee232683474",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":0},
            "size":{
              "width":60,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccfccf6aa8c5429dbcdf2ec304781ea2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":259,
                  "y":0},
                "size":{
                  "width":60,
                  "height":10},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u6.png"}},
{
          "id":"ee298feedbe34c73aa2e75b75a28990e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":6},
            "size":{
              "width":372,
              "height":796},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"52"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d5eb91ea81d40f3ada420180a832bbc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":6},
                "size":{
                  "width":372,
                  "height":796},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"52"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u8.png"}},
{
          "id":"27b46499f55747d1a5e741b224d8d252",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":32,
              "y":120},
            "size":{
              "width":320,
              "height":568},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f3eea768d6d14595823f6f98e7475cf1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFCCCCCC},
                "location":{
                  "x":32,
                  "y":120},
                "size":{
                  "width":320,
                  "height":568},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u10.png"}},
{
          "id":"96d40fe57c05461facfe430f691eb1e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":157,
              "y":66},
            "size":{
              "width":70,
              "height":14},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"35"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8306fdfb434488a90110f0aad576b60",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":157,
                  "y":66},
                "size":{
                  "width":70,
                  "height":14},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"35"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u12.png"}},
{
          "id":"d15322e269194fe1a7f78c07a12be63b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":40},
            "size":{
              "width":14,
              "height":14},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"35"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3530eba908a742998ca104681d9c8887",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":185,
                  "y":40},
                "size":{
                  "width":14,
                  "height":14},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"35"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u14.png"}},
{
          "id":"f96f8bc22fd541fa99d873db4f92e3b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":704},
            "size":{
              "width":72,
              "height":72},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"35"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56da81ac6a254133a5ef7958a6fe3df3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":156,
                  "y":704},
                "size":{
                  "width":72,
                  "height":72},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"35"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u16.png"}},
{
          "id":"28b885385b5a49d782d1d65861f169e2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":173},
            "size":{
              "width":64,
              "height":65},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae99b921599d48acb540c354d57e6a18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":173},
                "size":{
                  "width":64,
                  "height":65},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u18.png"}},
{
          "id":"45e22d6d5dd8407d98c875ab721cf75e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":38,
              "y":127.5},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a26b4e1072cf41518cc0f9ac1dfbaab7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":38,
                  "y":127.5},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u20.png"}},
{
          "id":"d848a82612d84080b61a152667637b5b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":255},
            "size":{
              "width":64,
              "height":65},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"182cb4c752674fceab2f1853758cf96d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":255},
                "size":{
                  "width":64,
                  "height":65},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u18.png"}},
{
          "id":"7636187b0c4e4dd5a3e07cfe836b143f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":340},
            "size":{
              "width":64,
              "height":65},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83e1a351ecbf409c8f03ff54cc6598c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":340},
                "size":{
                  "width":64,
                  "height":65},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u18.png"}},
{
          "id":"ca303474c9cd4121ae0c9bbd1c59b24a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":255},
            "size":{
              "width":64,
              "height":65},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2dcf6a6041244a8bbafe445e032e3ee0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":255},
                "size":{
                  "width":64,
                  "height":65},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u18.png"}},
{
          "id":"533aa1f2535a44eab7398fba0f308e43",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":340},
            "size":{
              "width":64,
              "height":65},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2011343b30194a2d9a6536cf7eba71dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":340},
                "size":{
                  "width":64,
                  "height":65},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u18.png"}},
{
          "id":"a1e236073f2b4568bb40aa4b964b9954",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":173},
            "size":{
              "width":64,
              "height":65},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cb72e2525cd4b969869f7c087343540",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":173},
                "size":{
                  "width":64,
                  "height":65},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u18.png"}},
{
          "id":"1207c1b8930e44e9a843a88dc63d552a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":197,
              "y":256},
            "size":{
              "width":65,
              "height":64},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"18447e5d73c345218e30ec5e613e41b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":197,
                  "y":256},
                "size":{
                  "width":65,
                  "height":64},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u32.png"}},
{
          "id":"06e14d9e313e4da789e366eb1f08a6db",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":124,
              "y":255},
            "size":{
              "width":65,
              "height":66},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0f53957a7914af19a5a6796bf810636",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":124,
                  "y":255},
                "size":{
                  "width":65,
                  "height":66},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u34.png"}},
{
          "id":"74d9c15c90d0442d87fc8028dc03c71b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":173},
            "size":{
              "width":64,
              "height":65},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bae8e6f96482407d8dbb24806ae573db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":198,
                  "y":173},
                "size":{
                  "width":64,
                  "height":65},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u18.png"}},
{
          "id":"d54ccbf69b06413cbf8707a4fe9761b2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":124,
              "y":173},
            "size":{
              "width":64,
              "height":65},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54ac4782492a48b099f1125614c3f8b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":124,
                  "y":173},
                "size":{
                  "width":64,
                  "height":65},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u18.png"}},
{
          "id":"d8b3f522a45f42d981733e7717c85498",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":420},
            "size":{
              "width":64,
              "height":65},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f3f2a1ca72a441e8ad7c8eb3e7be2df",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":420},
                "size":{
                  "width":64,
                  "height":65},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u18.png"}},
{
          "id":"73207d8b8f5445789ec2f3f87a3adb8b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":505},
            "size":{
              "width":64,
              "height":65},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ba9de792d9145eb808a3bc6225a6fd4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":505},
                "size":{
                  "width":64,
                  "height":65},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u18.png"}},
{
          "id":"8bb5771054a4411b8b9d968cb3ffe809",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":505},
            "size":{
              "width":64,
              "height":65},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF0000FF},
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4e07393a52da4db7bce9d5be810f9129",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":505},
                "size":{
                  "width":64,
                  "height":65},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF},
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 酒店预订",
                      "target":{
                        "targetType":"page",
                        "url":"酒店预订.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/首页面/u18.png"}},
{
          "id":"0f6688b2dabb4f3681c2984fb0e5878e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":272,
              "y":420},
            "size":{
              "width":64,
              "height":65},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1208c3796a3c44f58d583d1c00ad5c67",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":272,
                  "y":420},
                "size":{
                  "width":64,
                  "height":65},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u18.png"}},
{
          "id":"db3e2a3d03bb4e36ba23891068ef36ba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":198,
              "y":505},
            "size":{
              "width":64,
              "height":65},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73af6347f27546fa933cb28b94becddb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":198,
                  "y":505},
                "size":{
                  "width":64,
                  "height":65},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u18.png"}},
{
          "id":"b02f85e3a9424b3d88534b201182bc13",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":124,
              "y":505},
            "size":{
              "width":64,
              "height":65},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dd86cc86a13a4657b961da47070bc424",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":124,
                  "y":505},
                "size":{
                  "width":64,
                  "height":65},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u18.png"}},
{
          "id":"9fe9367ee9da4f03911ff44055b86264",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":197,
              "y":340},
            "size":{
              "width":65,
              "height":66},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f45206c630c0473b9accd226938db87a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":197,
                  "y":340},
                "size":{
                  "width":65,
                  "height":66},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u34.png"}},
{
          "id":"71def3f25ca948b4957d74776823f51a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":124,
              "y":420},
            "size":{
              "width":65,
              "height":66},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a1082e0925942cf8b9aa11d20837778",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":124,
                  "y":420},
                "size":{
                  "width":65,
                  "height":66},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u34.png"}},
{
          "id":"3fcdeb44bd894bc3925be6da70b3e92c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":122,
              "y":341},
            "size":{
              "width":65,
              "height":64},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5344c760f94e4b8cb66713ea2df51fb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":122,
                  "y":341},
                "size":{
                  "width":65,
                  "height":64},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u32.png"}},
{
          "id":"e7226b786d3e4ec7930418cf21eb1b88",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":199,
              "y":420},
            "size":{
              "width":65,
              "height":64},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"153ee3e34c30452e8941924ae0f624d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":199,
                  "y":420},
                "size":{
                  "width":65,
                  "height":64},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u32.png"}},
{
          "id":"af2d8544a65348d898b33e3e4636689d",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":580},
            "size":{
              "width":320,
              "height":108}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed4915dfd245487ab7118e5fba06d13a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":580},
                "size":{
                  "width":320,
                  "height":108}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u60.png"}},
{
          "id":"d5b1b38fab0b4233a00c23cb80f88ff1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":594},
            "size":{
              "width":66,
              "height":63},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62ff846876734a959e302334705fc25e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":594},
                "size":{
                  "width":66,
                  "height":63},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u62.png"}},
{
          "id":"aad720b4482547f49a4fbb0eb8612374",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":274,
              "y":594},
            "size":{
              "width":64,
              "height":63},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71156ad00c214be1bba35273a09ee71d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":274,
                  "y":594},
                "size":{
                  "width":64,
                  "height":63},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u64.png"}},
{
          "id":"2289426bf6eb42e6b6abd5312f7fa7e6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":126,
              "y":594},
            "size":{
              "width":66,
              "height":63},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed96f88154114eb782f15dba4f8b3766",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":126,
                  "y":594},
                "size":{
                  "width":66,
                  "height":63},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u66.png"}},
{
          "id":"8e299712a5424a7784099c5290f434a1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":200,
              "y":594},
            "size":{
              "width":64,
              "height":63},
            "rotation":"0",
            "textRotation":"0",
            "borderWidth":"0",
            "cornerRadiusTopLeft":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e43b2428c96743ab885f8539f887f847",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":200,
                  "y":594},
                "size":{
                  "width":64,
                  "height":63},
                "rotation":"0",
                "textRotation":"0",
                "borderWidth":"0",
                "cornerRadiusTopLeft":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u68.png"}},
{
          "id":"5d8e8a54268e4c2fabea601a44ee787a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":67,
              "y":658},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d1f0857b38dc4addae96219eee938069",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":67,
                  "y":658},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"45b74c214f574d4a8fda6c6686bc8288",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":146,
              "y":657},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76c9347bf66e4453977cd18e0c438297",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":146,
                  "y":657},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e15e32790e3449bf99ecfcf31fe45c72",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":216,
              "y":657},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea1558cff3d946e68b9462b257dc0f27",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":216,
                  "y":657},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb499d146ed348628b71f174f7010295",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":292,
              "y":657},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"25d8cccd2dc24111bea9edb450271e15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":292,
                  "y":657},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6088d165e49744f2a09280e82bcc9e8b",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":160},
            "size":{
              "width":286,
              "height":410}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 酒店预订",
                      "target":{
                        "targetType":"page",
                        "url":"酒店预订.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "9b0ec74c9b544ce29e6a6e460a86ecbf":{
      "scriptId":"u0"},
    "49e5bb950f3f4bfdb577aef278004c58":{
      "scriptId":"u1"},
    "51c8014765e14bf388ec09b59e08d24c":{
      "scriptId":"u2"},
    "bb8dd99d25c14c598119f8ef8be8757c":{
      "scriptId":"u3"},
    "348797d5864d4d8fbe4ae751a07ee1ed":{
      "scriptId":"u4"},
    "1a52e018b2694bdd8d740b3c8ce1d8d9":{
      "scriptId":"u5"},
    "defc5e7fbed840eea7b86ee232683474":{
      "scriptId":"u6"},
    "ccfccf6aa8c5429dbcdf2ec304781ea2":{
      "scriptId":"u7"},
    "ee298feedbe34c73aa2e75b75a28990e":{
      "scriptId":"u8"},
    "5d5eb91ea81d40f3ada420180a832bbc":{
      "scriptId":"u9"},
    "27b46499f55747d1a5e741b224d8d252":{
      "scriptId":"u10"},
    "f3eea768d6d14595823f6f98e7475cf1":{
      "scriptId":"u11"},
    "96d40fe57c05461facfe430f691eb1e8":{
      "scriptId":"u12"},
    "b8306fdfb434488a90110f0aad576b60":{
      "scriptId":"u13"},
    "d15322e269194fe1a7f78c07a12be63b":{
      "scriptId":"u14"},
    "3530eba908a742998ca104681d9c8887":{
      "scriptId":"u15"},
    "f96f8bc22fd541fa99d873db4f92e3b9":{
      "scriptId":"u16"},
    "56da81ac6a254133a5ef7958a6fe3df3":{
      "scriptId":"u17"},
    "28b885385b5a49d782d1d65861f169e2":{
      "scriptId":"u18"},
    "ae99b921599d48acb540c354d57e6a18":{
      "scriptId":"u19"},
    "45e22d6d5dd8407d98c875ab721cf75e":{
      "scriptId":"u20"},
    "a26b4e1072cf41518cc0f9ac1dfbaab7":{
      "scriptId":"u21"},
    "d848a82612d84080b61a152667637b5b":{
      "scriptId":"u22"},
    "182cb4c752674fceab2f1853758cf96d":{
      "scriptId":"u23"},
    "7636187b0c4e4dd5a3e07cfe836b143f":{
      "scriptId":"u24"},
    "83e1a351ecbf409c8f03ff54cc6598c9":{
      "scriptId":"u25"},
    "ca303474c9cd4121ae0c9bbd1c59b24a":{
      "scriptId":"u26"},
    "2dcf6a6041244a8bbafe445e032e3ee0":{
      "scriptId":"u27"},
    "533aa1f2535a44eab7398fba0f308e43":{
      "scriptId":"u28"},
    "2011343b30194a2d9a6536cf7eba71dc":{
      "scriptId":"u29"},
    "a1e236073f2b4568bb40aa4b964b9954":{
      "scriptId":"u30"},
    "2cb72e2525cd4b969869f7c087343540":{
      "scriptId":"u31"},
    "1207c1b8930e44e9a843a88dc63d552a":{
      "scriptId":"u32"},
    "18447e5d73c345218e30ec5e613e41b2":{
      "scriptId":"u33"},
    "06e14d9e313e4da789e366eb1f08a6db":{
      "scriptId":"u34"},
    "b0f53957a7914af19a5a6796bf810636":{
      "scriptId":"u35"},
    "74d9c15c90d0442d87fc8028dc03c71b":{
      "scriptId":"u36"},
    "bae8e6f96482407d8dbb24806ae573db":{
      "scriptId":"u37"},
    "d54ccbf69b06413cbf8707a4fe9761b2":{
      "scriptId":"u38"},
    "54ac4782492a48b099f1125614c3f8b6":{
      "scriptId":"u39"},
    "d8b3f522a45f42d981733e7717c85498":{
      "scriptId":"u40"},
    "2f3f2a1ca72a441e8ad7c8eb3e7be2df":{
      "scriptId":"u41"},
    "73207d8b8f5445789ec2f3f87a3adb8b":{
      "scriptId":"u42"},
    "8ba9de792d9145eb808a3bc6225a6fd4":{
      "scriptId":"u43"},
    "8bb5771054a4411b8b9d968cb3ffe809":{
      "scriptId":"u44"},
    "4e07393a52da4db7bce9d5be810f9129":{
      "scriptId":"u45"},
    "0f6688b2dabb4f3681c2984fb0e5878e":{
      "scriptId":"u46"},
    "1208c3796a3c44f58d583d1c00ad5c67":{
      "scriptId":"u47"},
    "db3e2a3d03bb4e36ba23891068ef36ba":{
      "scriptId":"u48"},
    "73af6347f27546fa933cb28b94becddb":{
      "scriptId":"u49"},
    "b02f85e3a9424b3d88534b201182bc13":{
      "scriptId":"u50"},
    "dd86cc86a13a4657b961da47070bc424":{
      "scriptId":"u51"},
    "9fe9367ee9da4f03911ff44055b86264":{
      "scriptId":"u52"},
    "f45206c630c0473b9accd226938db87a":{
      "scriptId":"u53"},
    "71def3f25ca948b4957d74776823f51a":{
      "scriptId":"u54"},
    "5a1082e0925942cf8b9aa11d20837778":{
      "scriptId":"u55"},
    "3fcdeb44bd894bc3925be6da70b3e92c":{
      "scriptId":"u56"},
    "5344c760f94e4b8cb66713ea2df51fb6":{
      "scriptId":"u57"},
    "e7226b786d3e4ec7930418cf21eb1b88":{
      "scriptId":"u58"},
    "153ee3e34c30452e8941924ae0f624d0":{
      "scriptId":"u59"},
    "af2d8544a65348d898b33e3e4636689d":{
      "scriptId":"u60"},
    "ed4915dfd245487ab7118e5fba06d13a":{
      "scriptId":"u61"},
    "d5b1b38fab0b4233a00c23cb80f88ff1":{
      "scriptId":"u62"},
    "62ff846876734a959e302334705fc25e":{
      "scriptId":"u63"},
    "aad720b4482547f49a4fbb0eb8612374":{
      "scriptId":"u64"},
    "71156ad00c214be1bba35273a09ee71d":{
      "scriptId":"u65"},
    "2289426bf6eb42e6b6abd5312f7fa7e6":{
      "scriptId":"u66"},
    "ed96f88154114eb782f15dba4f8b3766":{
      "scriptId":"u67"},
    "8e299712a5424a7784099c5290f434a1":{
      "scriptId":"u68"},
    "e43b2428c96743ab885f8539f887f847":{
      "scriptId":"u69"},
    "5d8e8a54268e4c2fabea601a44ee787a":{
      "scriptId":"u70"},
    "d1f0857b38dc4addae96219eee938069":{
      "scriptId":"u71"},
    "45b74c214f574d4a8fda6c6686bc8288":{
      "scriptId":"u72"},
    "76c9347bf66e4453977cd18e0c438297":{
      "scriptId":"u73"},
    "e15e32790e3449bf99ecfcf31fe45c72":{
      "scriptId":"u74"},
    "ea1558cff3d946e68b9462b257dc0f27":{
      "scriptId":"u75"},
    "bb499d146ed348628b71f174f7010295":{
      "scriptId":"u76"},
    "25d8cccd2dc24111bea9edb450271e15":{
      "scriptId":"u77"},
    "6088d165e49744f2a09280e82bcc9e8b":{
      "scriptId":"u78"}}});