$axure.loadCurrentPage({
  "url":"账户设定（第一次使用）.html",
  "generationDate":new Date(1398151328278.28),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"da0687809ceb43e093688135f9756003",
    "type":"Axure:Page",
    "name":"账户设定（第一次使用）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e5578af6261c41b0bf505688cf6fc57a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":80},
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ba1490d89fc445bb3fd2315a2cff759",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":80},
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u0.png"}},
{
          "id":"45543af5de2e463fbdd0c5e7c8df8b1a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":202},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eeeedf4822a940028f3c32448c080e0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":202},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u2.png"}},
{
          "id":"2bac3807c8c84c2e83ee8cefa72d7381",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":67,
              "y":230},
            "size":{
              "width":293,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b57d1e4495504dd4ac5919484b6b6541",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":67,
                  "y":230},
                "size":{
                  "width":293,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账户设定（第一次使用）/u4.png"}},
{
          "id":"cb14335b3df24d9ba69ceda091da6024",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":67,
              "y":290},
            "size":{
              "width":293,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e2e9d32597804961a5ef0ec35bfdd3ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":67,
                  "y":290},
                "size":{
                  "width":293,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账户设定（第一次使用）/u6.png"}},
{
          "id":"c9e81ce4a6814fe793235358d5e8326a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":67,
              "y":490},
            "size":{
              "width":293,
              "height":190}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"51e2681b0d9c4915a93b1fc16bb7a830",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":67,
                  "y":490},
                "size":{
                  "width":293,
                  "height":190}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账户设定（第一次使用）/u6.png"}},
{
          "id":"f0b6e8989a0847c0a702352d3db2c16b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontSize":"12px",
            "location":{
              "x":315,
              "y":454},
            "size":{
              "width":25,
              "height":15}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fda8c0a383f0456cb4bdad8a015edbc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"12px",
                "location":{
                  "x":315,
                  "y":454},
                "size":{
                  "width":25,
                  "height":15}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"06db572c02774e149343e745e1fb1943",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":720},
            "size":{
              "width":102,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19da3c76f2954cedb1883228390c2c8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":720},
                "size":{
                  "width":102,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账户设定（第一次使用）/u12.png"}},
{
          "id":"1a7a7d342f9b419189bb968dea3ca1d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":159,
              "y":720},
            "size":{
              "width":110,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e55ca477981a4400a32b66750a6d6434",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":159,
                  "y":720},
                "size":{
                  "width":110,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账户设定（第一次使用）/u14.png"}},
{
          "id":"4390cd9e601545f4acfcb39159835118",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":268,
              "y":720},
            "size":{
              "width":97,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eea0acb3125146e7a2724c814ca44e6b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":268,
                  "y":720},
                "size":{
                  "width":97,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账户设定（第一次使用）/u16.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e5578af6261c41b0bf505688cf6fc57a":{
      "scriptId":"u0"},
    "3ba1490d89fc445bb3fd2315a2cff759":{
      "scriptId":"u1"},
    "45543af5de2e463fbdd0c5e7c8df8b1a":{
      "scriptId":"u2"},
    "eeeedf4822a940028f3c32448c080e0f":{
      "scriptId":"u3"},
    "2bac3807c8c84c2e83ee8cefa72d7381":{
      "scriptId":"u4"},
    "b57d1e4495504dd4ac5919484b6b6541":{
      "scriptId":"u5"},
    "cb14335b3df24d9ba69ceda091da6024":{
      "scriptId":"u6"},
    "e2e9d32597804961a5ef0ec35bfdd3ee":{
      "scriptId":"u7"},
    "c9e81ce4a6814fe793235358d5e8326a":{
      "scriptId":"u8"},
    "51e2681b0d9c4915a93b1fc16bb7a830":{
      "scriptId":"u9"},
    "f0b6e8989a0847c0a702352d3db2c16b":{
      "scriptId":"u10"},
    "fda8c0a383f0456cb4bdad8a015edbc6":{
      "scriptId":"u11"},
    "06db572c02774e149343e745e1fb1943":{
      "scriptId":"u12"},
    "19da3c76f2954cedb1883228390c2c8d":{
      "scriptId":"u13"},
    "1a7a7d342f9b419189bb968dea3ca1d8":{
      "scriptId":"u14"},
    "e55ca477981a4400a32b66750a6d6434":{
      "scriptId":"u15"},
    "4390cd9e601545f4acfcb39159835118":{
      "scriptId":"u16"},
    "eea0acb3125146e7a2724c814ca44e6b":{
      "scriptId":"u17"}}});