$axure.loadCurrentPage({
  "url":"签收历史.html",
  "generationDate":new Date(1411007650859.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"a4f6037b328a418b89bf96f2fe8a17df",
    "type":"Axure:Page",
    "name":"签收历史",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"89c9829558d6405c934475683aff7d9b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":26},
            "size":{
              "width":380,
              "height":744},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c0a62a19c514c1eb1336f5c55084cfa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":26},
                "size":{
                  "width":380,
                  "height":744},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工资收发/u0.png"}},
{
          "id":"81651284b35144119e1f73a2e9b7035e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":51,
              "y":178},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e7cd4f7a8b44124b3773c3986a4657a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":51,
                  "y":178},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工资收发/u2.png"}},
{
          "id":"7dd807dea083413fa564c4ded578a0a8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":163},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa75bd8d8596480bad38fa71dc905858",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":163},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工资收发/u4.png"}},
{
          "id":"c020b75292da403c9aa56548afc5efed",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":234},
            "size":{
              "width":168,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"372e9ffba069431cb760447ee5520e5f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":234},
                "size":{
                  "width":168,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ca8414f5e3054e169e007a9b5b989af3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":51,
              "y":181},
            "size":{
              "width":71,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c63ce24310a7407fb63551d8a40acf13",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":51,
                  "y":181},
                "size":{
                  "width":71,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 工资签收",
                      "target":{
                        "targetType":"page",
                        "url":"工资签收.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/工资收发/u6.png"}},
{
          "id":"6e4546604f14469f887fd81d55dec864",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":152,
              "y":182},
            "size":{
              "width":148,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b2882d077224614b87494f55e2d2d46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":152,
                  "y":182},
                "size":{
                  "width":148,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2eb01517264547bf955f338740877e59",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":62,
              "y":271},
            "size":{
              "width":298,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7efe560600114861b94cce7fa25d3491",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":62,
                  "y":271},
                "size":{
                  "width":298,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/签收历史/u12.png"}},
{
          "id":"00544cd693c14889abf6bec47a5de7e4",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":330},
            "size":{
              "width":168,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"43e0728c038c4fd4a0df5e4283031b45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":330},
                "size":{
                  "width":168,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"89c099d3c7814e26b9c4c6f380de35c2",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":368},
            "size":{
              "width":168,
              "height":56}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"69c5dc92f29345ac8be36333b357aded",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":368},
                "size":{
                  "width":168,
                  "height":56}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "89c9829558d6405c934475683aff7d9b":{
      "scriptId":"u0"},
    "2c0a62a19c514c1eb1336f5c55084cfa":{
      "scriptId":"u1"},
    "81651284b35144119e1f73a2e9b7035e":{
      "scriptId":"u2"},
    "8e7cd4f7a8b44124b3773c3986a4657a":{
      "scriptId":"u3"},
    "7dd807dea083413fa564c4ded578a0a8":{
      "scriptId":"u4"},
    "aa75bd8d8596480bad38fa71dc905858":{
      "scriptId":"u5"},
    "c020b75292da403c9aa56548afc5efed":{
      "scriptId":"u6"},
    "372e9ffba069431cb760447ee5520e5f":{
      "scriptId":"u7"},
    "ca8414f5e3054e169e007a9b5b989af3":{
      "scriptId":"u8"},
    "c63ce24310a7407fb63551d8a40acf13":{
      "scriptId":"u9"},
    "6e4546604f14469f887fd81d55dec864":{
      "scriptId":"u10"},
    "4b2882d077224614b87494f55e2d2d46":{
      "scriptId":"u11"},
    "2eb01517264547bf955f338740877e59":{
      "scriptId":"u12"},
    "7efe560600114861b94cce7fa25d3491":{
      "scriptId":"u13"},
    "00544cd693c14889abf6bec47a5de7e4":{
      "scriptId":"u14"},
    "43e0728c038c4fd4a0df5e4283031b45":{
      "scriptId":"u15"},
    "89c099d3c7814e26b9c4c6f380de35c2":{
      "scriptId":"u16"},
    "69c5dc92f29345ac8be36333b357aded":{
      "scriptId":"u17"}}});