$axure.loadCurrentPage({
  "url":"银行卡修改.html",
  "generationDate":new Date(1407393883749.34),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"0842dd97a1b7441ea135e34e67a3be4f",
    "type":"Axure:Page",
    "name":"银行卡修改",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"9f684ff491334dcc93b834954201b5b2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":26},
            "size":{
              "width":380,
              "height":744},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"973d8921229844809794e9c6b8585a9b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":26},
                "size":{
                  "width":380,
                  "height":744},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账户管理/u0.png"}},
{
          "id":"73ddc448910f4d9d8aba33704d7a40f5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":51,
              "y":178},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa971b57194a40388b2e7aecad2bdfae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":51,
                  "y":178},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账户管理/u2.png"}},
{
          "id":"3e0e4b347537485588cdc6530dd64d07",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":163},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a8ff792ba6924ee5a02addd0605d1513",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":163},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/账户管理/u4.png"}},
{
          "id":"ca6be30f918642b99b071bb914b30bc4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":270},
            "size":{
              "width":271,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6dc90011eac649249e42639ecdfeeda1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":270},
                "size":{
                  "width":271,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/银行卡添加/u6.png"}},
{
          "id":"5589b83783054aad8656fc08bc22e1e1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":51,
              "y":181},
            "size":{
              "width":71,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c9724d86a324ec1a01a14452d59d93e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":51,
                  "y":181},
                "size":{
                  "width":71,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 银行卡管理",
                      "target":{
                        "targetType":"page",
                        "url":"银行卡管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/银行卡管理/u16.png"}},
{
          "id":"7c02a7f635a849cea65c084dc7ce8639",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":132,
              "y":182},
            "size":{
              "width":168,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7c480e9ddea440dca2124f7d8e103569",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":132,
                  "y":182},
                "size":{
                  "width":168,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ebac8cb0773249798a73f0aa1983b0d1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":80,
              "y":540},
            "size":{
              "width":80,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6576200cf5f445c1afd94c629619082d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":80,
                  "y":540},
                "size":{
                  "width":80,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 银行卡管理",
                      "target":{
                        "targetType":"page",
                        "url":"银行卡管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/银行卡修改/u12.png"}},
{
          "id":"b20dd9c14a4b43bababde91766ee655e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":79,
              "y":300},
            "size":{
              "width":271,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc80a57168194804927be1013824e0ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":79,
                  "y":300},
                "size":{
                  "width":271,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/银行卡添加/u6.png"}},
{
          "id":"67f92793016546638ea562547c7efb5e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":330},
            "size":{
              "width":271,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1d9a78925fd74b56bd37f7a24476aead",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":330},
                "size":{
                  "width":271,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/银行卡添加/u6.png"}},
{
          "id":"6c0710c65fae497aa646f58aa6ecbc68",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":360},
            "size":{
              "width":271,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"99f3c9d528e84ac6983d6fbe39d99805",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":360},
                "size":{
                  "width":271,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/银行卡添加/u6.png"}},
{
          "id":"8c290719173c4b1f9deb9e7a142d42c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":420},
            "size":{
              "width":271,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85d082b07a594f49bc13b2660b5ee4d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":420},
                "size":{
                  "width":271,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/银行卡添加/u6.png"}},
{
          "id":"2cdc7d19e2ce4041b6586ff6c8b86b51",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":419,
              "y":383},
            "size":{
              "width":331,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90426c15cbf04de9b4dbfbee8e6101c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":419,
                  "y":383},
                "size":{
                  "width":331,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/银行卡修改/u22.png"}},
{
          "id":"44ba18070d3649e0ad366d94ad6fd0b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":450},
            "size":{
              "width":271,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfb34e67e56c4f808842574ab3f45780",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":450},
                "size":{
                  "width":271,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/银行卡添加/u6.png"}},
{
          "id":"fd77ebf0cc864ddebafac0df48d137e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":480},
            "size":{
              "width":271,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10ed709fd13e42939923e550663e5366",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":480},
                "size":{
                  "width":271,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/银行卡添加/u6.png"}},
{
          "id":"4c358ce27271464488a7f121726b1d9c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":230},
            "size":{
              "width":271,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"193dfbfdabf44c9da11189739b9923bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":230},
                "size":{
                  "width":271,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/银行卡添加/u6.png"}},
{
          "id":"434163d1be804d6cbb15852ff5a77530",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":175.5,
              "y":540},
            "size":{
              "width":80,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12e0909b42a5453484f626a1e2a28985",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":175.5,
                  "y":540},
                "size":{
                  "width":80,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 银行卡管理",
                      "target":{
                        "targetType":"page",
                        "url":"银行卡管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/银行卡修改/u12.png"}},
{
          "id":"0753c143f50a43339b7f76c168056add",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":271,
              "y":540},
            "size":{
              "width":80,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21c5e70a0aeb4918ba0a04f1a716cbc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":271,
                  "y":540},
                "size":{
                  "width":80,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 银行卡管理",
                      "target":{
                        "targetType":"page",
                        "url":"银行卡管理.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/银行卡修改/u12.png"}},
{
          "id":"4623204903dc4f2ea0680403b90c9309",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":419,
              "y":540},
            "size":{
              "width":331,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3929bb91dfb74f1aa4ea8a05ddfb04c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":419,
                  "y":540},
                "size":{
                  "width":331,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/银行卡修改/u22.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "9f684ff491334dcc93b834954201b5b2":{
      "scriptId":"u0"},
    "973d8921229844809794e9c6b8585a9b":{
      "scriptId":"u1"},
    "73ddc448910f4d9d8aba33704d7a40f5":{
      "scriptId":"u2"},
    "aa971b57194a40388b2e7aecad2bdfae":{
      "scriptId":"u3"},
    "3e0e4b347537485588cdc6530dd64d07":{
      "scriptId":"u4"},
    "a8ff792ba6924ee5a02addd0605d1513":{
      "scriptId":"u5"},
    "ca6be30f918642b99b071bb914b30bc4":{
      "scriptId":"u6"},
    "6dc90011eac649249e42639ecdfeeda1":{
      "scriptId":"u7"},
    "5589b83783054aad8656fc08bc22e1e1":{
      "scriptId":"u8"},
    "5c9724d86a324ec1a01a14452d59d93e":{
      "scriptId":"u9"},
    "7c02a7f635a849cea65c084dc7ce8639":{
      "scriptId":"u10"},
    "7c480e9ddea440dca2124f7d8e103569":{
      "scriptId":"u11"},
    "ebac8cb0773249798a73f0aa1983b0d1":{
      "scriptId":"u12"},
    "6576200cf5f445c1afd94c629619082d":{
      "scriptId":"u13"},
    "b20dd9c14a4b43bababde91766ee655e":{
      "scriptId":"u14"},
    "bc80a57168194804927be1013824e0ff":{
      "scriptId":"u15"},
    "67f92793016546638ea562547c7efb5e":{
      "scriptId":"u16"},
    "1d9a78925fd74b56bd37f7a24476aead":{
      "scriptId":"u17"},
    "6c0710c65fae497aa646f58aa6ecbc68":{
      "scriptId":"u18"},
    "99f3c9d528e84ac6983d6fbe39d99805":{
      "scriptId":"u19"},
    "8c290719173c4b1f9deb9e7a142d42c3":{
      "scriptId":"u20"},
    "85d082b07a594f49bc13b2660b5ee4d2":{
      "scriptId":"u21"},
    "2cdc7d19e2ce4041b6586ff6c8b86b51":{
      "scriptId":"u22"},
    "90426c15cbf04de9b4dbfbee8e6101c0":{
      "scriptId":"u23"},
    "44ba18070d3649e0ad366d94ad6fd0b1":{
      "scriptId":"u24"},
    "dfb34e67e56c4f808842574ab3f45780":{
      "scriptId":"u25"},
    "fd77ebf0cc864ddebafac0df48d137e0":{
      "scriptId":"u26"},
    "10ed709fd13e42939923e550663e5366":{
      "scriptId":"u27"},
    "4c358ce27271464488a7f121726b1d9c":{
      "scriptId":"u28"},
    "193dfbfdabf44c9da11189739b9923bf":{
      "scriptId":"u29"},
    "434163d1be804d6cbb15852ff5a77530":{
      "scriptId":"u30"},
    "12e0909b42a5453484f626a1e2a28985":{
      "scriptId":"u31"},
    "0753c143f50a43339b7f76c168056add":{
      "scriptId":"u32"},
    "21c5e70a0aeb4918ba0a04f1a716cbc8":{
      "scriptId":"u33"},
    "4623204903dc4f2ea0680403b90c9309":{
      "scriptId":"u34"},
    "3929bb91dfb74f1aa4ea8a05ddfb04c3":{
      "scriptId":"u35"}}});