$axure.loadCurrentPage({
  "url":"代理商订货.html",
  "generationDate":new Date(1399184858057.73),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"8a8d6e0cbec34181a6c9673a6f629262",
    "type":"Axure:Page",
    "name":"代理商订货",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"eeef9c68efd0416f957a30f0d032cd80",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":235},
            "size":{
              "width":380,
              "height":744},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3bad8db3e7a54904b75973edc6b03426",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":185,
                  "y":235},
                "size":{
                  "width":380,
                  "height":744},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（效果页面）（新app）/u0.png"}},
{
          "id":"a581eb40a3704bed8f54a3ddc45319b0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":216,
              "y":387},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a88da184eb2c4132aed165213c82055e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":216,
                  "y":387},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（效果页面）（新app）/u2.png"}},
{
          "id":"636c891f3fa144a9b6ef0569876dd27f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":227,
              "y":372},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe04fc2d851e4a7fa033fe3c1ba6a33a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":227,
                  "y":372},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u2.png"}},
{
          "id":"c5543e59311a42739fd488e63c6bb073",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":225,
              "y":785},
            "size":{
              "width":140,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0cd92536ff9418183e686d39e40e542",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":225,
                  "y":785},
                "size":{
                  "width":140,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（效果页面）（新app）/u12.png"}},
{
          "id":"691f66aadbc8458ea4565ac446aa31ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":385,
              "y":785},
            "size":{
              "width":140,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c937cf157a34259acedea20b8a40669",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":385,
                  "y":785},
                "size":{
                  "width":140,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（效果页面）（新app）/u12.png"}},
{
          "id":"5750ab2a2cf8425e83c35838d413a12c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":308,
              "y":392},
            "size":{
              "width":208,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d790206d6cc64dc6a87ef8c8d13b448d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":308,
                  "y":392},
                "size":{
                  "width":208,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"00a822148db542d98dbf8445cd75fc3b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":236,
              "y":487},
            "size":{
              "width":60,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"541c8b50b0974c4a9ebf689bf82db30d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":236,
                  "y":487},
                "size":{
                  "width":60,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/代理商查询/u12.png"}},
{
          "id":"5b1ad70dfaa74d8a96b13655726ea5b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":605,
              "y":487},
            "size":{
              "width":120,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"19e52a674b6d429a9cb829fee315c0b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":605,
                  "y":487},
                "size":{
                  "width":120,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/转账汇款（记录和个人账户）/u32.png"}},
{
          "id":"3024e86899f647f099fbebb6d6a41cf0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":355,
              "y":735},
            "size":{
              "width":170,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fef95a2d5b8c4491917067c5711cc282",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":355,
                  "y":735},
                "size":{
                  "width":170,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/代理商查询/u20.png"}},
{
          "id":"0a2d5dd9ea274ce1858c190853c0ba62",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":257,
              "y":443},
            "size":{
              "width":153,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a5b5eb4d5ca4dfab58c432f5a510f31",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":257,
                  "y":443},
                "size":{
                  "width":153,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/代理商订货/u18.png"}},
{
          "id":"1f5d176520754e06a46bbd3bef62459c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":448},
            "size":{
              "width":97,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4fd05a8938c944e6bc4a7974c8cfea2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":236,
              "y":537},
            "size":{
              "width":224,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"388bd939a968439f9774d64ddf941fd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":236,
                  "y":537},
                "size":{
                  "width":224,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"31950b545d6c4a9f843d3d0c55195983",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":532},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"e823c08db379404ba9b6f2e4643ebe17",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":236,
              "y":599},
            "size":{
              "width":224,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65379f58e76348c489aa099b48b48044",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":236,
                  "y":599},
                "size":{
                  "width":224,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "eeef9c68efd0416f957a30f0d032cd80":{
      "scriptId":"u0"},
    "3bad8db3e7a54904b75973edc6b03426":{
      "scriptId":"u1"},
    "a581eb40a3704bed8f54a3ddc45319b0":{
      "scriptId":"u2"},
    "a88da184eb2c4132aed165213c82055e":{
      "scriptId":"u3"},
    "636c891f3fa144a9b6ef0569876dd27f":{
      "scriptId":"u4"},
    "fe04fc2d851e4a7fa033fe3c1ba6a33a":{
      "scriptId":"u5"},
    "c5543e59311a42739fd488e63c6bb073":{
      "scriptId":"u6"},
    "a0cd92536ff9418183e686d39e40e542":{
      "scriptId":"u7"},
    "691f66aadbc8458ea4565ac446aa31ca":{
      "scriptId":"u8"},
    "1c937cf157a34259acedea20b8a40669":{
      "scriptId":"u9"},
    "5750ab2a2cf8425e83c35838d413a12c":{
      "scriptId":"u10"},
    "d790206d6cc64dc6a87ef8c8d13b448d":{
      "scriptId":"u11"},
    "00a822148db542d98dbf8445cd75fc3b":{
      "scriptId":"u12"},
    "541c8b50b0974c4a9ebf689bf82db30d":{
      "scriptId":"u13"},
    "5b1ad70dfaa74d8a96b13655726ea5b2":{
      "scriptId":"u14"},
    "19e52a674b6d429a9cb829fee315c0b8":{
      "scriptId":"u15"},
    "3024e86899f647f099fbebb6d6a41cf0":{
      "scriptId":"u16"},
    "fef95a2d5b8c4491917067c5711cc282":{
      "scriptId":"u17"},
    "0a2d5dd9ea274ce1858c190853c0ba62":{
      "scriptId":"u18"},
    "9a5b5eb4d5ca4dfab58c432f5a510f31":{
      "scriptId":"u19"},
    "1f5d176520754e06a46bbd3bef62459c":{
      "scriptId":"u20"},
    "4fd05a8938c944e6bc4a7974c8cfea2b":{
      "scriptId":"u21"},
    "388bd939a968439f9774d64ddf941fd0":{
      "scriptId":"u22"},
    "31950b545d6c4a9f843d3d0c55195983":{
      "scriptId":"u23"},
    "e823c08db379404ba9b6f2e4643ebe17":{
      "scriptId":"u24"},
    "65379f58e76348c489aa099b48b48044":{
      "scriptId":"u25"}}});