$axure.loadCurrentPage({
  "url":"刷卡支付.html",
  "generationDate":new Date(1411546126234.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ba494486cdbc4605b36d7f4e9915aa43",
    "type":"Axure:Page",
    "name":"刷卡支付",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"c8748adc15b84fc7a2026f379a1eece3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":20},
            "size":{
              "width":390,
              "height":744},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fabf762851664378ba147459443d1a62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":20},
                "size":{
                  "width":390,
                  "height":744},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝订单支付/u0.png"}},
{
          "id":"3a51c0d65c434c7da960a5f0d7034a5f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":163},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3959b9d99c7f49d0bf5e1ff949cc92ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":163},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝订单支付/u2.png"}},
{
          "id":"d6b96d09de7c4e71b0a1917cd89d5700",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"center",
            "location":{
              "x":143,
              "y":186},
            "size":{
              "width":164,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e873463e24574858a3db2916a29abbc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "location":{
                  "x":143,
                  "y":186},
                "size":{
                  "width":164,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a65dc481b067478fbdb4dc5eb3b6e109",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":95,
              "y":470},
            "size":{
              "width":260,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66fa8bcb99204577b90396e401161f99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":95,
                  "y":470},
                "size":{
                  "width":260,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 填写银行卡",
                      "target":{
                        "targetType":"page",
                        "url":"填写银行卡.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/通付宝订单支付/u6.png"}},
{
          "id":"5b0e7ea5790441638538a5b1952ce959",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":70,
              "y":290},
            "size":{
              "width":310,
              "height":117}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cb20f3a5abd74839b3004392a214129f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":70,
                  "y":290},
                "size":{
                  "width":310,
                  "height":117}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/刷卡支付/u8.png"}},
{
          "id":"3a708ca82bd04be8978a4499a245d367",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":270,
              "y":350},
            "size":{
              "width":100,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b28424d01c94544b79bab5ca100d184",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":270,
                  "y":350},
                "size":{
                  "width":100,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/刷卡支付/u10.png"}},
{
          "id":"55302e1150d94c0cbee0196832156c6d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":350},
            "size":{
              "width":180,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eee3c94ae0f24fce8fb3e66dc5ab0885",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":350},
                "size":{
                  "width":180,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/刷卡支付/u12.png"}},
{
          "id":"03abf4035d5f421b96c71d4f1d0f2b53",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000FF,
              "opacity":1},
            "location":{
              "x":70,
              "y":290},
            "size":{
              "width":100,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e9b3fb61f0394d75abb0f53081cd6200",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF0000FF,
                  "opacity":1},
                "location":{
                  "x":70,
                  "y":290},
                "size":{
                  "width":100,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 刷卡支付",
                      "target":{
                        "targetType":"page",
                        "url":"刷卡支付.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/刷卡支付/u10.png"}},
{
          "id":"b1a6eac6257242faaf5f83eac05004b9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":170,
              "y":290},
            "size":{
              "width":100,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10618bea06014e40a261ca3434957183",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":170,
                  "y":290},
                "size":{
                  "width":100,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 填写银行卡",
                      "target":{
                        "targetType":"page",
                        "url":"填写银行卡.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/刷卡支付/u10.png"}},
{
          "id":"bef46615fe3d4bd4b4947aac692fc1e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":270,
              "y":290},
            "size":{
              "width":110,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"67b08760ade64f1baa1673776b6d081a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":270,
                  "y":290},
                "size":{
                  "width":110,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 优惠卡支付",
                      "target":{
                        "targetType":"page",
                        "url":"优惠卡支付.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/刷卡支付/u18.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "c8748adc15b84fc7a2026f379a1eece3":{
      "scriptId":"u0"},
    "fabf762851664378ba147459443d1a62":{
      "scriptId":"u1"},
    "3a51c0d65c434c7da960a5f0d7034a5f":{
      "scriptId":"u2"},
    "3959b9d99c7f49d0bf5e1ff949cc92ea":{
      "scriptId":"u3"},
    "d6b96d09de7c4e71b0a1917cd89d5700":{
      "scriptId":"u4"},
    "e873463e24574858a3db2916a29abbc9":{
      "scriptId":"u5"},
    "a65dc481b067478fbdb4dc5eb3b6e109":{
      "scriptId":"u6"},
    "66fa8bcb99204577b90396e401161f99":{
      "scriptId":"u7"},
    "5b0e7ea5790441638538a5b1952ce959":{
      "scriptId":"u8"},
    "cb20f3a5abd74839b3004392a214129f":{
      "scriptId":"u9"},
    "3a708ca82bd04be8978a4499a245d367":{
      "scriptId":"u10"},
    "6b28424d01c94544b79bab5ca100d184":{
      "scriptId":"u11"},
    "55302e1150d94c0cbee0196832156c6d":{
      "scriptId":"u12"},
    "eee3c94ae0f24fce8fb3e66dc5ab0885":{
      "scriptId":"u13"},
    "03abf4035d5f421b96c71d4f1d0f2b53":{
      "scriptId":"u14"},
    "e9b3fb61f0394d75abb0f53081cd6200":{
      "scriptId":"u15"},
    "b1a6eac6257242faaf5f83eac05004b9":{
      "scriptId":"u16"},
    "10618bea06014e40a261ca3434957183":{
      "scriptId":"u17"},
    "bef46615fe3d4bd4b4947aac692fc1e0":{
      "scriptId":"u18"},
    "67b08760ade64f1baa1673776b6d081a":{
      "scriptId":"u19"}}});