$axure.loadCurrentPage({
  "url":"业务页.html",
  "generationDate":new Date(1415177480593.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"43efcc40bc374a79a0e99fe761eaeac0",
    "type":"Axure:Page",
    "name":"业务页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d9eaaf20a16f48468d5642c958660409",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF666666},
            "size":{
              "width":660,
              "height":1160}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d63fd04842fa4378bc5795518758e957",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF666666},
                "size":{
                  "width":660,
                  "height":1160}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u0.png"}},
{
          "id":"769593e1a35e4d218e7a6ad45d2f6ac2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":10},
            "size":{
              "width":640,
              "height":1136}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ac4f327c16e948948572f1e9ba63a6a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":10},
                "size":{
                  "width":640,
                  "height":1136}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u2.png"}},
{
          "id":"c28cb6f51f86491fb20d360993946914",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":10,
              "y":20},
            "size":{
              "width":640,
              "height":30},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7df5a56671744ee58cd1aabf858af520",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":10,
                  "y":20},
                "size":{
                  "width":640,
                  "height":30},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/业务页背景/u4.png"}},
{
          "id":"206dd22f0a134776954c2f55403de961",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":23,
              "y":70},
            "size":{
              "width":45,
              "height":60},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61deb5cdbc7e49f9a7eb9eaa815d3d1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":23,
                  "y":70},
                "size":{
                  "width":45,
                  "height":60},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/业务页背景/u6.png"}},
{
          "id":"466f12de1af541459dad37eb0a740eba",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"48px",
            "location":{
              "x":217,
              "y":72},
            "size":{
              "width":193,
              "height":57}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"13a5d42bfe4f4e909525f29f8203347e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"48px",
                "location":{
                  "x":217,
                  "y":72},
                "size":{
                  "width":193,
                  "height":57}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"748211e4eece4bbba668709a95cbad08",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":23,
              "y":140},
            "size":{
              "width":607,
              "height":10}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/业务页背景/u10_line.png"}},
{
          "id":"e275d824a2914e4db559458918d79442",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0066FF},
            "location":{
              "x":50,
              "y":185},
            "size":{
              "width":240,
              "height":60}},
          "adaptiveStyles":{
}},
{
          "id":"c5ff7b01d55a473ea0d7c20c5d760745",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0066FF},
            "location":{
              "x":50,
              "y":255},
            "size":{
              "width":170,
              "height":60}},
          "adaptiveStyles":{
}},
{
          "id":"b81067ef77cb4f60a743f051783f22f6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":185},
            "size":{
              "width":250,
              "height":60}},
          "adaptiveStyles":{
}},
{
          "id":"8de285acfd8b49738542f5f3f6e02c5b",
          "label":"手机号码",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":185},
            "size":{
              "width":250,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 手机号码 to 点击后",
                      "panelsToStates":[{
                          "panelPath":["8de285acfd8b49738542f5f3f6e02c5b"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]},
            "onPanelStateChange":{
              "description":"OnPanelStateChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 keyboard1 向上滑动 500 ms",
                      "objectsToFades":[{
                          "objectPath":["45d05dd2997f43309d2ebf9d970dd33f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideUp",
                              "duration":500,
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 321",
                      "objectsToFades":[{
                          "objectPath":["6b469ec47a534e988a17bcb3cff0b40e"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"f8d538d603484390898b5b90f8d48b27",
              "label":"点击前",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"37c84a6de5414045a1e8e84bda7307b9",
                  "label":"",
                  "parentDynamicPanel":"8de285acfd8b49738542f5f3f6e02c5b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":250,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"703ab6cdc8cc4daa91877284bdc7a145",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8de285acfd8b49738542f5f3f6e02c5b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":250,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/业务页背景/u15.png"}},
{
                  "id":"6394dff0a1cb42769e2b0fe958966243",
                  "label":"",
                  "parentDynamicPanel":"8de285acfd8b49738542f5f3f6e02c5b",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":4,
                      "y":20},
                    "size":{
                      "width":300,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6ade230843ce4081b714fac07091f6bd",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8de285acfd8b49738542f5f3f6e02c5b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":4,
                          "y":20},
                        "size":{
                          "width":300,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"acc3868ca66d418dba64eb885c96cc1f",
              "label":"点击后",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"5ee5020cf9ca46d2a68bc64524f723bb",
                  "label":"",
                  "parentDynamicPanel":"8de285acfd8b49738542f5f3f6e02c5b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":250,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"c57df2420d4242a2a7c65ce9a3378732",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8de285acfd8b49738542f5f3f6e02c5b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":250,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/业务页背景/u15.png"}},
{
                  "id":"dcebcb35775b42fd806d5184830bc9f5",
                  "label":"",
                  "parentDynamicPanel":"8de285acfd8b49738542f5f3f6e02c5b",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":250,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"a8275cc584c145c69c5fa0ed8851e502",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"8de285acfd8b49738542f5f3f6e02c5b",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":250,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/业务页背景/u15.png"}}]}]},
{
          "id":"9ce19d1d35ff48888a9b16fd5f11d172",
          "label":"收款金额",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":255},
            "size":{
              "width":310,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 收款金额 to 点击后",
                      "panelsToStates":[{
                          "panelPath":["9ce19d1d35ff48888a9b16fd5f11d172"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]},
            "onPanelStateChange":{
              "description":"OnPanelStateChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 keyboard1 向上滑动 500 ms",
                      "objectsToFades":[{
                          "objectPath":["45d05dd2997f43309d2ebf9d970dd33f"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideUp",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"c5e6705797e0488891034ab09da40b38",
              "label":"点击前",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"d4e723507d9e49ffbc09f74929641d2d",
                  "label":"",
                  "parentDynamicPanel":"9ce19d1d35ff48888a9b16fd5f11d172",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":310,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"6b6e65aefa7d490294ab3250e2745019",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9ce19d1d35ff48888a9b16fd5f11d172",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":310,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/业务页背景/u24.png"}},
{
                  "id":"250e4879b5ea48418ff83ee5e5baea82",
                  "label":"",
                  "parentDynamicPanel":"9ce19d1d35ff48888a9b16fd5f11d172",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":4,
                      "y":20},
                    "size":{
                      "width":300,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"b63032cc30e34ce1a52f6ceadfd290e1",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9ce19d1d35ff48888a9b16fd5f11d172",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":4,
                          "y":20},
                        "size":{
                          "width":300,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"1a9136e6cc0a489a833e934887cfa298",
              "label":"点击后",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"7b249d16828f4ef98b0384a7c16a6e7e",
                  "label":"",
                  "parentDynamicPanel":"9ce19d1d35ff48888a9b16fd5f11d172",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":310,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"490dced5811c49bb9da2581afc783304",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"9ce19d1d35ff48888a9b16fd5f11d172",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":310,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/业务页背景/u24.png"}}]}]},
{
          "id":"a35e3a26c4d24641a563d4601ae3058d",
          "label":"",
          "type":"textArea",
          "styleType":"textArea",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "location":{
              "x":50,
              "y":510},
            "size":{
              "width":550,
              "height":375}},
          "adaptiveStyles":{
}},
{
          "id":"556c36a6761441dea8ad9d3bdd78234f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0066FF},
            "location":{
              "x":50,
              "y":395},
            "size":{
              "width":100,
              "height":60}},
          "adaptiveStyles":{
}},
{
          "id":"0e0bcbc1204c4e6baffa975d1357ad64",
          "label":"备注",
          "type":"dynamicPanel",
          "styleType":"dynamicPanel",
          "visible":true,
          "style":{
            "location":{
              "x":150,
              "y":395},
            "size":{
              "width":450,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"setPanelState",
                      "description":"设置 备注 to 点击后",
                      "panelsToStates":[{
                          "panelPath":["0e0bcbc1204c4e6baffa975d1357ad64"],
                          "stateInfo":{
                            "setStateType":"diagram",
                            "stateNumber":2,
                            "stateValue":{
                              "exprType":"stringLiteral",
                              "value":"1",
                              "stos":[]},
                            "loop":false,
                            "showWhenSet":false,
                            "options":{
                              "compress":false}}}]}]}]},
            "onPanelStateChange":{
              "description":"OnPanelStateChange",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 keyboard 向上滑动 500 ms",
                      "objectsToFades":[{
                          "objectPath":["2560bd00fff944bba655842f629a2788"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "easing":"slideUp",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "scrollbars":"none",
          "fitToContent":false,
          "propagate":false,
          "diagrams":[{
              "id":"059b4ffc9d3f45bbb86d00982073cc17",
              "label":"点击前",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"886a3b112ef94b6684a3cb3b88adcafa",
                  "label":"",
                  "parentDynamicPanel":"0e0bcbc1204c4e6baffa975d1357ad64",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":450,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"01b9d29e0fc74dea91bbdfd4befd554a",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e0bcbc1204c4e6baffa975d1357ad64",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":450,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/业务页背景/u33.png"}},
{
                  "id":"17eb4594a0c3445aac537baa15172449",
                  "label":"",
                  "parentDynamicPanel":"0e0bcbc1204c4e6baffa975d1357ad64",
                  "type":"buttonShape",
                  "styleType":"paragraph",
                  "visible":true,
                  "style":{
                    "fontSize":"20px",
                    "foreGroundFill":{
                      "fillType":"solid",
                      "color":0xFFCCCCCC,
                      "opacity":1},
                    "location":{
                      "x":4,
                      "y":20},
                    "size":{
                      "width":300,
                      "height":16}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"40b37bc4828d4bada4f4d29c8111a406",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e0bcbc1204c4e6baffa975d1357ad64",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "fontSize":"20px",
                        "foreGroundFill":{
                          "fillType":"solid",
                          "color":0xFFCCCCCC,
                          "opacity":1},
                        "location":{
                          "x":4,
                          "y":20},
                        "size":{
                          "width":300,
                          "height":16}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"resources/images/transparent.gif"}}]},
{
              "id":"330f81dd900e4ab69dcd64836c3ff5cc",
              "label":"点击后",
              "type":"Axure:PanelDiagram",
              "objects":[{
                  "id":"f5c23360b8eb440e8f21ec71108cb189",
                  "label":"",
                  "parentDynamicPanel":"0e0bcbc1204c4e6baffa975d1357ad64",
                  "type":"buttonShape",
                  "styleType":"buttonShape",
                  "visible":true,
                  "style":{
                    "size":{
                      "width":450,
                      "height":60}},
                  "adaptiveStyles":{
},
                  "objects":[{
                      "id":"853fcb9e93794157953989b2c8fe6589",
                      "label":"",
                      "isContained":true,
                      "parentDynamicPanel":"0e0bcbc1204c4e6baffa975d1357ad64",
                      "type":"richTextPanel",
                      "styleType":"paragraph",
                      "visible":true,
                      "style":{
                        "size":{
                          "width":450,
                          "height":60}},
                      "adaptiveStyles":{
}}],
                  "images":{
                    "normal~":"images/业务页背景/u33.png"}}]}]},
{
          "id":"79b6d21336674fb0afa688cfecadd5d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":68,
              "y":590},
            "size":{
              "width":490,
              "height":66}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"000b4763bedd4dbaaf444db6d89b520b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":68,
                  "y":590},
                "size":{
                  "width":490,
                  "height":66}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81675bca55784d07a377a66ee480b5aa",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0066FF},
            "location":{
              "x":220,
              "y":255},
            "size":{
              "width":70,
              "height":60}},
          "adaptiveStyles":{
}},
{
          "id":"850e32d2fbcf402f8be9aa7879524b7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":68,
              "y":786},
            "size":{
              "width":490,
              "height":99}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"372fad37dc3f40a69384fdae3d2eca0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":68,
                  "y":786},
                "size":{
                  "width":490,
                  "height":99}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8b5ba10a9a6b4d88a24b2567c9504210",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFFCCCCCC},
            "location":{
              "x":50,
              "y":465},
            "size":{
              "width":420,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"cf6bcd06177e4a6da9100a450fe91ff8",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0066FF},
            "location":{
              "x":470,
              "y":465},
            "size":{
              "width":130,
              "height":30}},
          "adaptiveStyles":{
}},
{
          "id":"999c2d9093514dc9a9ba0929141830bf",
          "label":"keyboard",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"28px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":68,
              "y":677},
            "size":{
              "width":490,
              "height":99}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1917aecf4ba445de9bd0b985639b326a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"28px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":68,
                  "y":677},
                "size":{
                  "width":490,
                  "height":99}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3b2e237a5794ef48f77a12f36bf9bd7",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontSize":"15px",
            "location":{
              "x":50,
              "y":910},
            "size":{
              "width":550,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56b11a3b865f4af29796b76c48b82566",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"15px",
                "location":{
                  "x":50,
                  "y":910},
                "size":{
                  "width":550,
                  "height":17}},
              "adaptiveStyles":{
}}]},
{
          "id":"124edd82547e4d0ab3504147aa396d2a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Bold', '微软雅黑'",
            "fontSize":"36px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF0000CC,
              "opacity":1},
            "location":{
              "x":50,
              "y":960},
            "size":{
              "width":550,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 结果通知页",
                      "target":{
                        "targetType":"page",
                        "url":"结果通知页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"45d05dd2997f43309d2ebf9d970dd33f",
          "label":"keyboard1",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":10,
              "y":714},
            "size":{
              "width":638,
              "height":432},
            "visible":false,
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"75592551d11845c0a6e0540f3fa14cc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":10,
                  "y":714},
                "size":{
                  "width":638,
                  "height":432},
                "visible":false,
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/业务页/keyboard1_u51.png"}},
{
          "id":"2560bd00fff944bba655842f629a2788",
          "label":"keyboard",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":false,
          "style":{
            "location":{
              "x":10,
              "y":714},
            "size":{
              "width":638,
              "height":432},
            "visible":false,
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b1df52c986754a1fbfa1bf73d65dd25a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":10,
                  "y":714},
                "size":{
                  "width":638,
                  "height":432},
                "visible":false,
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 keyboard 向下滑动 500 ms",
                      "objectsToFades":[{
                          "objectPath":["2560bd00fff944bba655842f629a2788"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/业务页/keyboard_u53.png"}},
{
          "id":"53b9b6b7d429416b9dd7664bca8a5473",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0066FF},
            "location":{
              "x":50,
              "y":325},
            "size":{
              "width":170,
              "height":60}},
          "adaptiveStyles":{
}},
{
          "id":"fd5bdb65c0214d9a845929be181f1252",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontSize":"36px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"solid",
              "color":0xFF0066FF},
            "location":{
              "x":220,
              "y":325},
            "size":{
              "width":70,
              "height":60}},
          "adaptiveStyles":{
}},
{
          "id":"9cb1ca29eca14a149797b338500d7723",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":325},
            "size":{
              "width":310,
              "height":60}},
          "adaptiveStyles":{
}},
{
          "id":"cabd3d49c6a24cb680a3752b7cf82c9c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":550,
              "y":193},
            "size":{
              "width":44,
              "height":44},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"702cf5dd2f8d4c40b1870769937c5c45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":550,
                  "y":193},
                "size":{
                  "width":44,
                  "height":44},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/业务页背景/u54.png"}},
{
          "id":"6b469ec47a534e988a17bcb3cff0b40e",
          "label":"321",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":false,
          "style":{
            "location":{
              "x":512,
              "y":1070},
            "size":{
              "width":46,
              "height":60},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 keyboard1 向下滑动 500 ms",
                      "objectsToFades":[{
                          "objectPath":["45d05dd2997f43309d2ebf9d970dd33f"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"f51f748bd4ab423fb0f91664110fd075",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":558,
              "y":1070},
            "size":{
              "width":52,
              "height":60}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 keyboard 向下滑动 500 ms",
                      "objectsToFades":[{
                          "objectPath":["2560bd00fff944bba655842f629a2788"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "easing":"slideDown",
                              "duration":500,
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"2093ed972d0d4beb8f44588f7fc60007",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":470,
              "y":465},
            "size":{
              "width":130,
              "height":30}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 银行卡列表页",
                      "target":{
                        "targetType":"page",
                        "url":"银行卡列表页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "d9eaaf20a16f48468d5642c958660409":{
      "scriptId":"u0"},
    "d63fd04842fa4378bc5795518758e957":{
      "scriptId":"u1"},
    "769593e1a35e4d218e7a6ad45d2f6ac2":{
      "scriptId":"u2"},
    "ac4f327c16e948948572f1e9ba63a6a7":{
      "scriptId":"u3"},
    "c28cb6f51f86491fb20d360993946914":{
      "scriptId":"u4"},
    "7df5a56671744ee58cd1aabf858af520":{
      "scriptId":"u5"},
    "206dd22f0a134776954c2f55403de961":{
      "scriptId":"u6"},
    "61deb5cdbc7e49f9a7eb9eaa815d3d1d":{
      "scriptId":"u7"},
    "466f12de1af541459dad37eb0a740eba":{
      "scriptId":"u8"},
    "13a5d42bfe4f4e909525f29f8203347e":{
      "scriptId":"u9"},
    "748211e4eece4bbba668709a95cbad08":{
      "scriptId":"u10"},
    "e275d824a2914e4db559458918d79442":{
      "scriptId":"u11"},
    "c5ff7b01d55a473ea0d7c20c5d760745":{
      "scriptId":"u12"},
    "b81067ef77cb4f60a743f051783f22f6":{
      "scriptId":"u13"},
    "8de285acfd8b49738542f5f3f6e02c5b":{
      "scriptId":"u14"},
    "37c84a6de5414045a1e8e84bda7307b9":{
      "scriptId":"u15"},
    "703ab6cdc8cc4daa91877284bdc7a145":{
      "scriptId":"u16"},
    "6394dff0a1cb42769e2b0fe958966243":{
      "scriptId":"u17"},
    "6ade230843ce4081b714fac07091f6bd":{
      "scriptId":"u18"},
    "5ee5020cf9ca46d2a68bc64524f723bb":{
      "scriptId":"u19"},
    "c57df2420d4242a2a7c65ce9a3378732":{
      "scriptId":"u20"},
    "dcebcb35775b42fd806d5184830bc9f5":{
      "scriptId":"u21"},
    "a8275cc584c145c69c5fa0ed8851e502":{
      "scriptId":"u22"},
    "9ce19d1d35ff48888a9b16fd5f11d172":{
      "scriptId":"u23"},
    "d4e723507d9e49ffbc09f74929641d2d":{
      "scriptId":"u24"},
    "6b6e65aefa7d490294ab3250e2745019":{
      "scriptId":"u25"},
    "250e4879b5ea48418ff83ee5e5baea82":{
      "scriptId":"u26"},
    "b63032cc30e34ce1a52f6ceadfd290e1":{
      "scriptId":"u27"},
    "7b249d16828f4ef98b0384a7c16a6e7e":{
      "scriptId":"u28"},
    "490dced5811c49bb9da2581afc783304":{
      "scriptId":"u29"},
    "a35e3a26c4d24641a563d4601ae3058d":{
      "scriptId":"u30"},
    "556c36a6761441dea8ad9d3bdd78234f":{
      "scriptId":"u31"},
    "0e0bcbc1204c4e6baffa975d1357ad64":{
      "scriptId":"u32"},
    "886a3b112ef94b6684a3cb3b88adcafa":{
      "scriptId":"u33"},
    "01b9d29e0fc74dea91bbdfd4befd554a":{
      "scriptId":"u34"},
    "17eb4594a0c3445aac537baa15172449":{
      "scriptId":"u35"},
    "40b37bc4828d4bada4f4d29c8111a406":{
      "scriptId":"u36"},
    "f5c23360b8eb440e8f21ec71108cb189":{
      "scriptId":"u37"},
    "853fcb9e93794157953989b2c8fe6589":{
      "scriptId":"u38"},
    "79b6d21336674fb0afa688cfecadd5d8":{
      "scriptId":"u39"},
    "000b4763bedd4dbaaf444db6d89b520b":{
      "scriptId":"u40"},
    "81675bca55784d07a377a66ee480b5aa":{
      "scriptId":"u41"},
    "850e32d2fbcf402f8be9aa7879524b7f":{
      "scriptId":"u42"},
    "372fad37dc3f40a69384fdae3d2eca0a":{
      "scriptId":"u43"},
    "8b5ba10a9a6b4d88a24b2567c9504210":{
      "scriptId":"u44"},
    "cf6bcd06177e4a6da9100a450fe91ff8":{
      "scriptId":"u45"},
    "999c2d9093514dc9a9ba0929141830bf":{
      "scriptId":"u46"},
    "1917aecf4ba445de9bd0b985639b326a":{
      "scriptId":"u47"},
    "d3b2e237a5794ef48f77a12f36bf9bd7":{
      "scriptId":"u48"},
    "56b11a3b865f4af29796b76c48b82566":{
      "scriptId":"u49"},
    "124edd82547e4d0ab3504147aa396d2a":{
      "scriptId":"u50"},
    "45d05dd2997f43309d2ebf9d970dd33f":{
      "scriptId":"u51"},
    "75592551d11845c0a6e0540f3fa14cc5":{
      "scriptId":"u52"},
    "2560bd00fff944bba655842f629a2788":{
      "scriptId":"u53"},
    "b1df52c986754a1fbfa1bf73d65dd25a":{
      "scriptId":"u54"},
    "53b9b6b7d429416b9dd7664bca8a5473":{
      "scriptId":"u55"},
    "fd5bdb65c0214d9a845929be181f1252":{
      "scriptId":"u56"},
    "9cb1ca29eca14a149797b338500d7723":{
      "scriptId":"u57"},
    "cabd3d49c6a24cb680a3752b7cf82c9c":{
      "scriptId":"u58"},
    "702cf5dd2f8d4c40b1870769937c5c45":{
      "scriptId":"u59"},
    "6b469ec47a534e988a17bcb3cff0b40e":{
      "scriptId":"u60"},
    "f51f748bd4ab423fb0f91664110fd075":{
      "scriptId":"u61"},
    "2093ed972d0d4beb8f44588f7fc60007":{
      "scriptId":"u62"}}});