$axure.loadCurrentPage({
  "url":"7、利润表.html",
  "generationDate":new Date(1403260000265.63),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"602cf842e2e4460a9abfa863892a553a",
    "type":"Axure:Page",
    "name":"7、利润表",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"da1b01e1480a43c4a860a685393e74cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":40,
              "y":120},
            "size":{
              "width":70,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd3bd3573dba407dacaf10dd1e488715",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":40,
                  "y":120},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7、利润表/u0.png"}},
{
          "id":"0bba4f75e1be4e90b9bdfd65213bff32",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":250,
              "y":120},
            "size":{
              "width":73,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f93f098019294de3a74e5c72e3937479",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":250,
                  "y":120},
                "size":{
                  "width":73,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7、利润表/u2.png"}},
{
          "id":"264284c2fb334753a173bdddfdae40c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":250,
              "y":60},
            "size":{
              "width":60,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f3c851d5e3942a5aa53da9d67b7b58e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":250,
                  "y":60},
                "size":{
                  "width":60,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7、利润表/u4.png"}},
{
          "id":"8ef7c07e49e84702ba801560ec235daa",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":330,
              "y":62},
            "size":{
              "width":25,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62bdd24e5b194f8bbb654f26fc555d5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":330,
                  "y":62},
                "size":{
                  "width":25,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d4475fddda146a6a436ab8032b71d64",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":370,
              "y":60},
            "size":{
              "width":48,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4efe78a0f9e4fceb41ae5e3161ff9e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":370,
                  "y":60},
                "size":{
                  "width":48,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7、利润表/u8.png"}},
{
          "id":"2f65cad2c44c4cc2ae157eaef58940b0",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":520,
              "y":30},
            "size":{
              "width":100,
              "height":48}},
          "adaptiveStyles":{
}},
{
          "id":"7577b0d9c8d1439cbfdfa56cd3fce187",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":323,
              "y":120},
            "size":{
              "width":95,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"57cfc14dd45a436d9e4a8b820d315859",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":323,
                  "y":120},
                "size":{
                  "width":95,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7、利润表/u11.png"}},
{
          "id":"ee0254e4c8634fefae421131d54b6ec7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":418,
              "y":120},
            "size":{
              "width":115,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7943e6b80d84c1bbc9a63fbd0eb579e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":418,
                  "y":120},
                "size":{
                  "width":115,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7、利润表/u13.png"}},
{
          "id":"77906db1c0ea40618080218900b6c77b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":110,
              "y":120},
            "size":{
              "width":70,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8c4f5d96f994ce590e0009a96120f74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":110,
                  "y":120},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7、利润表/u0.png"}},
{
          "id":"67b0fb07c84c434eba1a2c8284b136c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":250,
              "y":20},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3f0d04965324983b034e83a107135ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":250,
                  "y":20},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2、代理商管理（业务）/u55.png"}},
{
          "id":"ba6011a30b434ca3b8c38699dce3f07c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":40,
              "y":310},
            "size":{
              "width":100,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de9f2c21a32847848a8ff468f0ad781e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":40,
                  "y":310},
                "size":{
                  "width":100,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/6、代理商产品出库单/u14.png"}},
{
          "id":"0670a14223f04f30bd97a260666cc785",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":180,
              "y":120},
            "size":{
              "width":70,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"457a12351c424d42926c1d9783ef1a45",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":180,
                  "y":120},
                "size":{
                  "width":70,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7、利润表/u0.png"}},
{
          "id":"ff6d801d96364356926b0855d8d63410",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":170,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2be6a0a2f7f4409980f01221498a15d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":170,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7、利润表/u23.png"}},
{
          "id":"134a01bc7d654906abf705efcc497c5f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":40,
              "y":160},
            "size":{
              "width":890,
              "height":140}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4cc6aa3f6915407b9ded631fcbb69448",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":40,
                  "y":160},
                "size":{
                  "width":890,
                  "height":140}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7、利润表/u25.png"}},
{
          "id":"e2b2555428404affb7d622c892a10374",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":640,
              "y":4},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"50cd2ff56fd24f618dcf026594e515c5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":640,
                  "y":4},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1、代理商添加（财务）/u21.png"}},
{
          "id":"e8778f8707de4e69b8f33c6d46a17cbb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":533,
              "y":120},
            "size":{
              "width":77,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a642bf87dded4d64a49370f0cf6fdc11",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":533,
                  "y":120},
                "size":{
                  "width":77,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7、利润表/u29.png"}},
{
          "id":"9b2125e75cac47fca948204814e255a3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":610,
              "y":120},
            "size":{
              "width":90,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c71a7f1703f44d78b14a77a606cdeef5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":610,
                  "y":120},
                "size":{
                  "width":90,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7、利润表/u31.png"}},
{
          "id":"d1a44b4acb3741eca911ca1316c77f73",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":700,
              "y":120},
            "size":{
              "width":90,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c26df4f324943a7b1392dad8c18fc2a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":700,
                  "y":120},
                "size":{
                  "width":90,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7、利润表/u31.png"}},
{
          "id":"71af038782e44df4be9a68451289c1c1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":790,
              "y":120},
            "size":{
              "width":60,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4723de8d63e440f0a945774dd7c33345",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":790,
                  "y":120},
                "size":{
                  "width":60,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2、代理商管理（业务）/u24.png"}},
{
          "id":"a1a1d0bc76be41608d07360cb1673408",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":850,
              "y":120},
            "size":{
              "width":80,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be58b494c4024ae1a34954c6c796402f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":850,
                  "y":120},
                "size":{
                  "width":80,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7、利润表/u37.png"}},
{
          "id":"26fde3d67cd8491a8d890a0d9f844a8c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":215,
              "y":340},
            "size":{
              "width":345,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bc01136e07f54afdbd19bdcda999df08",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":215,
                  "y":340},
                "size":{
                  "width":345,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/7、利润表/u39.png"}},
{
          "id":"5b94dbf418c44148b5397efa123a446f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":600,
              "y":340},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b0cf35ccfd7d4d9ca581feff6300beef",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":600,
                  "y":340},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1、代理商添加（财务）/u21.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "da1b01e1480a43c4a860a685393e74cf":{
      "scriptId":"u0"},
    "bd3bd3573dba407dacaf10dd1e488715":{
      "scriptId":"u1"},
    "0bba4f75e1be4e90b9bdfd65213bff32":{
      "scriptId":"u2"},
    "f93f098019294de3a74e5c72e3937479":{
      "scriptId":"u3"},
    "264284c2fb334753a173bdddfdae40c8":{
      "scriptId":"u4"},
    "8f3c851d5e3942a5aa53da9d67b7b58e":{
      "scriptId":"u5"},
    "8ef7c07e49e84702ba801560ec235daa":{
      "scriptId":"u6"},
    "62bdd24e5b194f8bbb654f26fc555d5e":{
      "scriptId":"u7"},
    "5d4475fddda146a6a436ab8032b71d64":{
      "scriptId":"u8"},
    "c4efe78a0f9e4fceb41ae5e3161ff9e3":{
      "scriptId":"u9"},
    "2f65cad2c44c4cc2ae157eaef58940b0":{
      "scriptId":"u10"},
    "7577b0d9c8d1439cbfdfa56cd3fce187":{
      "scriptId":"u11"},
    "57cfc14dd45a436d9e4a8b820d315859":{
      "scriptId":"u12"},
    "ee0254e4c8634fefae421131d54b6ec7":{
      "scriptId":"u13"},
    "a7943e6b80d84c1bbc9a63fbd0eb579e":{
      "scriptId":"u14"},
    "77906db1c0ea40618080218900b6c77b":{
      "scriptId":"u15"},
    "d8c4f5d96f994ce590e0009a96120f74":{
      "scriptId":"u16"},
    "67b0fb07c84c434eba1a2c8284b136c1":{
      "scriptId":"u17"},
    "e3f0d04965324983b034e83a107135ce":{
      "scriptId":"u18"},
    "ba6011a30b434ca3b8c38699dce3f07c":{
      "scriptId":"u19"},
    "de9f2c21a32847848a8ff468f0ad781e":{
      "scriptId":"u20"},
    "0670a14223f04f30bd97a260666cc785":{
      "scriptId":"u21"},
    "457a12351c424d42926c1d9783ef1a45":{
      "scriptId":"u22"},
    "ff6d801d96364356926b0855d8d63410":{
      "scriptId":"u23"},
    "f2be6a0a2f7f4409980f01221498a15d":{
      "scriptId":"u24"},
    "134a01bc7d654906abf705efcc497c5f":{
      "scriptId":"u25"},
    "4cc6aa3f6915407b9ded631fcbb69448":{
      "scriptId":"u26"},
    "e2b2555428404affb7d622c892a10374":{
      "scriptId":"u27"},
    "50cd2ff56fd24f618dcf026594e515c5":{
      "scriptId":"u28"},
    "e8778f8707de4e69b8f33c6d46a17cbb":{
      "scriptId":"u29"},
    "a642bf87dded4d64a49370f0cf6fdc11":{
      "scriptId":"u30"},
    "9b2125e75cac47fca948204814e255a3":{
      "scriptId":"u31"},
    "c71a7f1703f44d78b14a77a606cdeef5":{
      "scriptId":"u32"},
    "d1a44b4acb3741eca911ca1316c77f73":{
      "scriptId":"u33"},
    "5c26df4f324943a7b1392dad8c18fc2a":{
      "scriptId":"u34"},
    "71af038782e44df4be9a68451289c1c1":{
      "scriptId":"u35"},
    "4723de8d63e440f0a945774dd7c33345":{
      "scriptId":"u36"},
    "a1a1d0bc76be41608d07360cb1673408":{
      "scriptId":"u37"},
    "be58b494c4024ae1a34954c6c796402f":{
      "scriptId":"u38"},
    "26fde3d67cd8491a8d890a0d9f844a8c":{
      "scriptId":"u39"},
    "bc01136e07f54afdbd19bdcda999df08":{
      "scriptId":"u40"},
    "5b94dbf418c44148b5397efa123a446f":{
      "scriptId":"u41"},
    "b0cf35ccfd7d4d9ca581feff6300beef":{
      "scriptId":"u42"}}});