$axure.loadCurrentPage({
  "url":"收银台.html",
  "generationDate":new Date(1417684938562.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7cab18fe54ab4a5ab59958561f7fc1fe",
    "type":"Axure:Page",
    "name":"收银台",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dc839e68076e455b8efe7cec136e7227",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":116},
            "size":{
              "width":8,
              "height":36},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"59a2436f13b1470cb4f620bb62c159d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":116},
                "size":{
                  "width":8,
                  "height":36},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城首页1/u0.png"}},
{
          "id":"d30392d6ab0344e7a8c604761e34ca3f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":192},
            "size":{
              "width":8,
              "height":27},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2cd477bfe29148b29bea6d6266b1c4a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":192},
                "size":{
                  "width":8,
                  "height":27},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城首页1/u2.png"}},
{
          "id":"1b5eb50e07d140bbad66e6ba25233e02",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":255},
            "size":{
              "width":8,
              "height":27},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3823b0ffe0a4ecb8af74e025323073e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":255},
                "size":{
                  "width":8,
                  "height":27},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城首页1/u2.png"}},
{
          "id":"e5c088ac931249a8a9890c52a6d0d02f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":0},
            "size":{
              "width":60,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fc0cad9a125446d8b0fb9478103c61f5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":259,
                  "y":0},
                "size":{
                  "width":60,
                  "height":10},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城首页1/u6.png"}},
{
          "id":"aa1b2df08fc04a3a8d281b11074a66f2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":6},
            "size":{
              "width":372,
              "height":796},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"52"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"540c76ce80ad457a8094d544cd1be7cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":6},
                "size":{
                  "width":372,
                  "height":796},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"52"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城首页1/u8.png"}},
{
          "id":"cba3e2553f8e4a42a8cfeb95bdc45687",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":32,
              "y":120},
            "size":{
              "width":320,
              "height":568},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79077f8a9eb147a290f639c4b66f3c54",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":32,
                  "y":120},
                "size":{
                  "width":320,
                  "height":568},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城首页1/u10.png"}},
{
          "id":"0b9c273a5e714cfa857a54a5b5741711",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":157,
              "y":66},
            "size":{
              "width":70,
              "height":14},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"35"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27e10b068e59470ebcd82b0f27223a03",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":157,
                  "y":66},
                "size":{
                  "width":70,
                  "height":14},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"35"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城首页1/u12.png"}},
{
          "id":"c9599df1ae624ab686a5c606bf25e159",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":185,
              "y":40},
            "size":{
              "width":14,
              "height":14},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"35"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79307284921b4c0b96531e51db7a85d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":185,
                  "y":40},
                "size":{
                  "width":14,
                  "height":14},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"35"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城首页1/u14.png"}},
{
          "id":"d90ab8c2a8bf4a40912813a51b036927",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":156,
              "y":704},
            "size":{
              "width":72,
              "height":72},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"35"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84a1c1c6dbb449c9b7ff88988b43fa20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":156,
                  "y":704},
                "size":{
                  "width":72,
                  "height":72},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"35"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城首页1/u16.png"}},
{
          "id":"ad6872e8d9d64d119e09be888cb59016",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFF990066},
            "location":{
              "x":33,
              "y":120},
            "size":{
              "width":318,
              "height":568},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8e6081cb6567495fa9644555217dd6c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFF990066},
                "location":{
                  "x":33,
                  "y":120},
                "size":{
                  "width":318,
                  "height":568},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城首页1/u20.png"}},
{
          "id":"eb51aecb01644cd4be0e81ce033ca0a1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":38,
              "y":128},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5091775ce70e45559cd0ae7c6b179bba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":38,
                  "y":128},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商城首页1/u22.png"}},
{
          "id":"9b3e7acb610d4bd0ba05385858f92d9a",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":190},
            "size":{
              "width":150,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/订单编辑/u22_line.png"}},
{
          "id":"961bb3a6ef584b4b92e93dcf22564b41",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":157,
              "y":163},
            "size":{
              "width":61,
              "height":27}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c424bf3c4c2e4bcda390bfc758da8377",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":157,
                  "y":163},
                "size":{
                  "width":61,
                  "height":27}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "dc839e68076e455b8efe7cec136e7227":{
      "scriptId":"u0"},
    "59a2436f13b1470cb4f620bb62c159d6":{
      "scriptId":"u1"},
    "d30392d6ab0344e7a8c604761e34ca3f":{
      "scriptId":"u2"},
    "2cd477bfe29148b29bea6d6266b1c4a2":{
      "scriptId":"u3"},
    "1b5eb50e07d140bbad66e6ba25233e02":{
      "scriptId":"u4"},
    "b3823b0ffe0a4ecb8af74e025323073e":{
      "scriptId":"u5"},
    "e5c088ac931249a8a9890c52a6d0d02f":{
      "scriptId":"u6"},
    "fc0cad9a125446d8b0fb9478103c61f5":{
      "scriptId":"u7"},
    "aa1b2df08fc04a3a8d281b11074a66f2":{
      "scriptId":"u8"},
    "540c76ce80ad457a8094d544cd1be7cb":{
      "scriptId":"u9"},
    "cba3e2553f8e4a42a8cfeb95bdc45687":{
      "scriptId":"u10"},
    "79077f8a9eb147a290f639c4b66f3c54":{
      "scriptId":"u11"},
    "0b9c273a5e714cfa857a54a5b5741711":{
      "scriptId":"u12"},
    "27e10b068e59470ebcd82b0f27223a03":{
      "scriptId":"u13"},
    "c9599df1ae624ab686a5c606bf25e159":{
      "scriptId":"u14"},
    "79307284921b4c0b96531e51db7a85d0":{
      "scriptId":"u15"},
    "d90ab8c2a8bf4a40912813a51b036927":{
      "scriptId":"u16"},
    "84a1c1c6dbb449c9b7ff88988b43fa20":{
      "scriptId":"u17"},
    "ad6872e8d9d64d119e09be888cb59016":{
      "scriptId":"u18"},
    "8e6081cb6567495fa9644555217dd6c0":{
      "scriptId":"u19"},
    "eb51aecb01644cd4be0e81ce033ca0a1":{
      "scriptId":"u20"},
    "5091775ce70e45559cd0ae7c6b179bba":{
      "scriptId":"u21"},
    "9b3e7acb610d4bd0ba05385858f92d9a":{
      "scriptId":"u22"},
    "961bb3a6ef584b4b92e93dcf22564b41":{
      "scriptId":"u23"},
    "c424bf3c4c2e4bcda390bfc758da8377":{
      "scriptId":"u24"}}});