$axure.loadCurrentPage({
  "url":"信用卡支付（未保存）.html",
  "generationDate":new Date(1407924517406.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"ee1eb8abae6a448ab06b152d7fbd2ba8",
    "type":"Axure:Page",
    "name":"信用卡支付（未保存）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5a1e3a2f85b94dde81d537d5f9941308",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":26},
            "size":{
              "width":380,
              "height":744},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0980548745184b6393e919598a6d8e97",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":26},
                "size":{
                  "width":380,
                  "height":744},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/话费充值/u0.png"}},
{
          "id":"1cf9ce7301cb49f0b6f446c0d479657f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":51,
              "y":178},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"044a21424c93435b86d8c9e504e24ec3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":51,
                  "y":178},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/话费充值/u2.png"}},
{
          "id":"af42e639707d4444a6166d781447bc1c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":163},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"031c38c04ed54f9c97672b300de42183",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":163},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/话费充值/u4.png"}},
{
          "id":"bf106686c28e4e74baaff898eddb310a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":70,
              "y":234},
            "size":{
              "width":290,
              "height":186}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3775a1641ac249bd910bdcfa12e973de",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":70,
                  "y":234},
                "size":{
                  "width":290,
                  "height":186}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/信用卡支付（易宝）/u6.png"}},
{
          "id":"295425b8e0c54dcd9307e68c9e61cc25",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":150,
              "y":182},
            "size":{
              "width":168,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c30bcb23d7934b06846c070088e3ff07",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":150,
                  "y":182},
                "size":{
                  "width":168,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a2b7b221d21b4d2ea8e40828f3aec979",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":165,
              "y":570},
            "size":{
              "width":90,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d169b9407ceb40ff98a5e8379e87d7c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":165,
                  "y":570},
                "size":{
                  "width":90,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 信用卡支付（手机确认）",
                      "target":{
                        "targetType":"page",
                        "url":"信用卡支付（手机确认）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/话费充值/u8.png"}},
{
          "id":"59cc6d10e12a4fe0b7507d8349922270",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":70,
              "y":510},
            "size":{
              "width":290,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f5670249c9e4d529d5db0c68a8793d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":70,
                  "y":510},
                "size":{
                  "width":290,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"2ace8c47f67d46cc8731c6c91306e39d",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":70,
              "y":475},
            "size":{
              "width":290,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"493cc6c3786d4845b05edebd48ebb63f",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":70,
              "y":440},
            "size":{
              "width":210,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "5a1e3a2f85b94dde81d537d5f9941308":{
      "scriptId":"u0"},
    "0980548745184b6393e919598a6d8e97":{
      "scriptId":"u1"},
    "1cf9ce7301cb49f0b6f446c0d479657f":{
      "scriptId":"u2"},
    "044a21424c93435b86d8c9e504e24ec3":{
      "scriptId":"u3"},
    "af42e639707d4444a6166d781447bc1c":{
      "scriptId":"u4"},
    "031c38c04ed54f9c97672b300de42183":{
      "scriptId":"u5"},
    "bf106686c28e4e74baaff898eddb310a":{
      "scriptId":"u6"},
    "3775a1641ac249bd910bdcfa12e973de":{
      "scriptId":"u7"},
    "295425b8e0c54dcd9307e68c9e61cc25":{
      "scriptId":"u8"},
    "c30bcb23d7934b06846c070088e3ff07":{
      "scriptId":"u9"},
    "a2b7b221d21b4d2ea8e40828f3aec979":{
      "scriptId":"u10"},
    "d169b9407ceb40ff98a5e8379e87d7c3":{
      "scriptId":"u11"},
    "59cc6d10e12a4fe0b7507d8349922270":{
      "scriptId":"u12"},
    "0f5670249c9e4d529d5db0c68a8793d6":{
      "scriptId":"u13"},
    "2ace8c47f67d46cc8731c6c91306e39d":{
      "scriptId":"u14"},
    "493cc6c3786d4845b05edebd48ebb63f":{
      "scriptId":"u15"}}});