$axure.loadCurrentPage({
  "url":"3、产品管理（仓管）.html",
  "generationDate":new Date(1403259999859.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5d5ca58e90294c4f802b566176becdc7",
    "type":"Axure:Page",
    "name":"3、产品管理（仓管）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8b3bf4b5bfe747228e7ffc162134e6ec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":55,
              "y":36},
            "size":{
              "width":220,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f4eca57d65a641a78f65f20549ae2305",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":55,
                  "y":36},
                "size":{
                  "width":220,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3、产品管理（仓管）/u0.png"}},
{
          "id":"cfa7eac19d844ab3acfa1e0b53368a48",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":241,
              "y":114},
            "size":{
              "width":140,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"939c5dcb49cb4143b189634f161153ac",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":241,
                  "y":114},
                "size":{
                  "width":140,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3、产品管理（仓管）/u2.png"}},
{
          "id":"2f770ad47887447eb859d4e5c9c35bb3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":67,
              "y":114},
            "size":{
              "width":100,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a7341fbc436d438e8da8c2d54b793c6a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":67,
                  "y":114},
                "size":{
                  "width":100,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3、产品管理（仓管）/u4.png"}},
{
          "id":"4e530b5bb5314d828595003199b2a13d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":241,
              "y":143},
            "size":{
              "width":140,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fccd842615c54a0f82d7c985444ee373",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":241,
                  "y":143},
                "size":{
                  "width":140,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3、产品管理（仓管）/u6.png"}},
{
          "id":"14fe58695b7949be8943e0cf2a34f4ca",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":380,
              "y":114},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6d01d560f8b240178e45bc45c2996c9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":380,
                  "y":114},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2、代理商管理（业务）/u55.png"}},
{
          "id":"dafa6320738548abb02fda22aae98385",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":67,
              "y":143},
            "size":{
              "width":101,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c43336ecec8b43bca12a959d5dee4966",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":67,
                  "y":143},
                "size":{
                  "width":101,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3、产品管理（仓管）/u10.png"}},
{
          "id":"20fbb4a144854f5db5602e265b40bae5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":380,
              "y":143},
            "size":{
              "width":200,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d37089d2e3944a89bd80f0a50f2ea63f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":380,
                  "y":143},
                "size":{
                  "width":200,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3、产品管理（仓管）/u12.png"}},
{
          "id":"0f0dc2ba8aeb457b9f738f49a736c170",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":55,
              "y":76},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"51343f13913b4294aa84c586f4199394",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":175,
              "y":76},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"82528878b0c54cc7a4f6c4d79bc3e914",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":291,
              "y":76},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"dade938188594966baafd9d3d1644382",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":291,
              "y":36},
            "size":{
              "width":293,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"74fe4b217c784390a4cc874618d6e817",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":291,
                  "y":36},
                "size":{
                  "width":293,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3、产品管理（仓管）/u17.png"}},
{
          "id":"f47506b221cd434c88d58f387754ac25",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":544,
              "y":76},
            "size":{
              "width":200,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ef016be255c947568cb828424ab4bd47",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":506,
              "y":53},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83448968bb294961989bc8fb92ba178d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":506,
                  "y":53},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3、产品管理（仓管）/u20.png"}},
{
          "id":"787c2bc3cdbb46adb46ecd2744d0926e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":579,
              "y":143},
            "size":{
              "width":148,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ca97eb3e1ec488082173ca7aa3d0d2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":579,
                  "y":143},
                "size":{
                  "width":148,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3、产品管理（仓管）/u22.png"}},
{
          "id":"5986a35de14f478bb4071de03aa8cc43",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":579,
              "y":114},
            "size":{
              "width":148,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ef6c066d07540639495d239ce2cec0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":579,
                  "y":114},
                "size":{
                  "width":148,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3、产品管理（仓管）/u24.png"}},
{
          "id":"22514a2bcccf4976b94056fe72b4ee9b",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":594,
              "y":38},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3ba7486912164cf0ae9059db1c2596aa",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":418,
              "y":76},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"bb0c74c7814b4adc991639104b589434",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":603,
              "y":175},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"2e941444ca8b4cb6a4fa81689100a6a8",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":760,
              "y":76},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"0c660a30070b4e3faadde7362847a55f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":57,
              "y":331},
            "size":{
              "width":156,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7962e2a04ed94cd38ded352779b520ec",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":57,
                  "y":331},
                "size":{
                  "width":156,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2、代理商管理（业务）/u53.png"}},
{
          "id":"efb6e0cfca0e4273a96229dee8988ac6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":541,
              "y":331},
            "size":{
              "width":200,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9b8b1e9c9fd42319b9e5540f3debe51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":541,
                  "y":331},
                "size":{
                  "width":200,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2、代理商管理（业务）/u55.png"}},
{
          "id":"5037b89a6d3644d085de6ec1fc349f51",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":166,
              "y":114},
            "size":{
              "width":76,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d850635aa954da4b2d086dc15a57f52",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":166,
                  "y":114},
                "size":{
                  "width":76,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3、产品管理（仓管）/u34.png"}},
{
          "id":"589a0f4e6869426dbf0c5fc9310d85da",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":166,
              "y":143},
            "size":{
              "width":76,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca224a8519eb424fa81cdd992433703f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":166,
                  "y":143},
                "size":{
                  "width":76,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/3、产品管理（仓管）/u36.png"}},
{
          "id":"fe9723d6860e43a6bd71618019736966",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":780,
              "y":143},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3ec5014d0e74857aaf79953741ec152",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":780,
                  "y":143},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1、代理商添加（财务）/u21.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "8b3bf4b5bfe747228e7ffc162134e6ec":{
      "scriptId":"u0"},
    "f4eca57d65a641a78f65f20549ae2305":{
      "scriptId":"u1"},
    "cfa7eac19d844ab3acfa1e0b53368a48":{
      "scriptId":"u2"},
    "939c5dcb49cb4143b189634f161153ac":{
      "scriptId":"u3"},
    "2f770ad47887447eb859d4e5c9c35bb3":{
      "scriptId":"u4"},
    "a7341fbc436d438e8da8c2d54b793c6a":{
      "scriptId":"u5"},
    "4e530b5bb5314d828595003199b2a13d":{
      "scriptId":"u6"},
    "fccd842615c54a0f82d7c985444ee373":{
      "scriptId":"u7"},
    "14fe58695b7949be8943e0cf2a34f4ca":{
      "scriptId":"u8"},
    "6d01d560f8b240178e45bc45c2996c9f":{
      "scriptId":"u9"},
    "dafa6320738548abb02fda22aae98385":{
      "scriptId":"u10"},
    "c43336ecec8b43bca12a959d5dee4966":{
      "scriptId":"u11"},
    "20fbb4a144854f5db5602e265b40bae5":{
      "scriptId":"u12"},
    "d37089d2e3944a89bd80f0a50f2ea63f":{
      "scriptId":"u13"},
    "0f0dc2ba8aeb457b9f738f49a736c170":{
      "scriptId":"u14"},
    "51343f13913b4294aa84c586f4199394":{
      "scriptId":"u15"},
    "82528878b0c54cc7a4f6c4d79bc3e914":{
      "scriptId":"u16"},
    "dade938188594966baafd9d3d1644382":{
      "scriptId":"u17"},
    "74fe4b217c784390a4cc874618d6e817":{
      "scriptId":"u18"},
    "f47506b221cd434c88d58f387754ac25":{
      "scriptId":"u19"},
    "ef016be255c947568cb828424ab4bd47":{
      "scriptId":"u20"},
    "83448968bb294961989bc8fb92ba178d":{
      "scriptId":"u21"},
    "787c2bc3cdbb46adb46ecd2744d0926e":{
      "scriptId":"u22"},
    "4ca97eb3e1ec488082173ca7aa3d0d2f":{
      "scriptId":"u23"},
    "5986a35de14f478bb4071de03aa8cc43":{
      "scriptId":"u24"},
    "8ef6c066d07540639495d239ce2cec0c":{
      "scriptId":"u25"},
    "22514a2bcccf4976b94056fe72b4ee9b":{
      "scriptId":"u26"},
    "3ba7486912164cf0ae9059db1c2596aa":{
      "scriptId":"u27"},
    "bb0c74c7814b4adc991639104b589434":{
      "scriptId":"u28"},
    "2e941444ca8b4cb6a4fa81689100a6a8":{
      "scriptId":"u29"},
    "0c660a30070b4e3faadde7362847a55f":{
      "scriptId":"u30"},
    "7962e2a04ed94cd38ded352779b520ec":{
      "scriptId":"u31"},
    "efb6e0cfca0e4273a96229dee8988ac6":{
      "scriptId":"u32"},
    "b9b8b1e9c9fd42319b9e5540f3debe51":{
      "scriptId":"u33"},
    "5037b89a6d3644d085de6ec1fc349f51":{
      "scriptId":"u34"},
    "4d850635aa954da4b2d086dc15a57f52":{
      "scriptId":"u35"},
    "589a0f4e6869426dbf0c5fc9310d85da":{
      "scriptId":"u36"},
    "ca224a8519eb424fa81cdd992433703f":{
      "scriptId":"u37"},
    "fe9723d6860e43a6bd71618019736966":{
      "scriptId":"u38"},
    "b3ec5014d0e74857aaf79953741ec152":{
      "scriptId":"u39"}}});