$axure.loadCurrentPage({
  "url":"支付验证.html",
  "generationDate":new Date(1399184857643.71),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"30006cfe0ad04d279211624b81583a54",
    "type":"Axure:Page",
    "name":"支付验证",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fdae7c0dde1449a1bfde59bad5efe66e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":80},
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"64a798d170b54a03acb12b89661f1f30",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":80},
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u0.png"}},
{
          "id":"6281b3ba85a84b7fbb526a7803a3dba8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":202},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f168896787f74e9aa018da45e37258e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":202},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u2.png"}},
{
          "id":"578865b4211a41898e539a048040eba3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":233},
            "size":{
              "width":270,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"358ba7e4b89c4297b0da233830c87293",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":233},
                "size":{
                  "width":270,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手势密码设定一/u4.png"}},
{
          "id":"29dd542635184dd3a9e254e8c2109899",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":289},
            "size":{
              "width":270,
              "height":71}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"436384ef076b459aaecf076a410187ff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":289},
                "size":{
                  "width":270,
                  "height":71}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付验证/u6.png"}},
{
          "id":"f80d79e2508b46839ddd875013ab9014",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":383},
            "size":{
              "width":270,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ed22a4aa1cfe4f49bc5aa81ca645dbff",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":383},
                "size":{
                  "width":270,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收款账户列表/u6.png"}},
{
          "id":"940ec0bf83934847b05cade40f49811c",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":81,
              "y":446},
            "size":{
              "width":199,
              "height":75}},
          "adaptiveStyles":{
}},
{
          "id":"90fefb1c204041e9b0dc994d7ce0c57a",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":290,
              "y":446},
            "size":{
              "width":60,
              "height":75}},
          "adaptiveStyles":{
}},
{
          "id":"a2a83848a75046be9880404d9521a73f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":546},
            "size":{
              "width":320,
              "height":216},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2850894a3f5840ba9dd2a2c3c6366c71",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":546},
                "size":{
                  "width":320,
                  "height":216},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付验证/u12.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "fdae7c0dde1449a1bfde59bad5efe66e":{
      "scriptId":"u0"},
    "64a798d170b54a03acb12b89661f1f30":{
      "scriptId":"u1"},
    "6281b3ba85a84b7fbb526a7803a3dba8":{
      "scriptId":"u2"},
    "f168896787f74e9aa018da45e37258e3":{
      "scriptId":"u3"},
    "578865b4211a41898e539a048040eba3":{
      "scriptId":"u4"},
    "358ba7e4b89c4297b0da233830c87293":{
      "scriptId":"u5"},
    "29dd542635184dd3a9e254e8c2109899":{
      "scriptId":"u6"},
    "436384ef076b459aaecf076a410187ff":{
      "scriptId":"u7"},
    "f80d79e2508b46839ddd875013ab9014":{
      "scriptId":"u8"},
    "ed22a4aa1cfe4f49bc5aa81ca645dbff":{
      "scriptId":"u9"},
    "940ec0bf83934847b05cade40f49811c":{
      "scriptId":"u10"},
    "90fefb1c204041e9b0dc994d7ce0c57a":{
      "scriptId":"u11"},
    "a2a83848a75046be9880404d9521a73f":{
      "scriptId":"u12"},
    "2850894a3f5840ba9dd2a2c3c6366c71":{
      "scriptId":"u13"}}});