$axure.loadCurrentPage({
  "url":"我的银行卡_1.html",
  "generationDate":new Date(1407924518484.38),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"198bdf2a085040c6a307cf3f4f5ec5bd",
    "type":"Axure:Page",
    "name":"我的银行卡",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"cee0931a1ce04856b2019a6b18e43f48",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":26},
            "size":{
              "width":380,
              "height":744},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"502ad33ee48a4baf8788f2582b1eda53",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":26},
                "size":{
                  "width":380,
                  "height":744},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/话费充值/u0.png"}},
{
          "id":"e91d3c852d584a86b2ca4d6fc5cd1c2a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":51,
              "y":178},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f934d712d01c4b318ebd8b919dcf7f78",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":51,
                  "y":178},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/话费充值/u2.png"}},
{
          "id":"bfb246055c444cd8b5839e56285dd6a3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":163},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ea31fa167f4e47d38b5363b52713a15c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":163},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/话费充值/u4.png"}},
{
          "id":"8f395aa25f884e8ab905d9d52181318d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":122,
              "y":182},
            "size":{
              "width":168,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82e09b557a3f4df0a8c6f90986dd407a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":122,
                  "y":182},
                "size":{
                  "width":168,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f175b35c92e042a396067b63976e413e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":250},
            "size":{
              "width":260,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"87364a0adbfe4d7f99b2960efd5357e9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":250},
                "size":{
                  "width":260,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 3、充值订单（借记卡-银联）",
                      "target":{
                        "targetType":"page",
                        "url":"3、充值订单（借记卡-银联）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的银行卡/u8.png"}},
{
          "id":"a6a272b022264d97a648495d989819e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":300,
              "y":186},
            "size":{
              "width":70,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a9dce803e384b05a1c15e54dfc21103",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":300,
                  "y":186},
                "size":{
                  "width":70,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 添加银行卡（信用卡）",
                      "target":{
                        "targetType":"page",
                        "url":"添加银行卡（信用卡）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/话费充值/u14.png"}},
{
          "id":"83cb5ed4db8f440282ac978a989090e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":330},
            "size":{
              "width":260,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2177555a8ba424fb92020795a5bbfc5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":330},
                "size":{
                  "width":260,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 2、充值订单（信用卡-易宝）",
                      "target":{
                        "targetType":"page",
                        "url":"2、充值订单（信用卡-易宝）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的银行卡/u8.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "cee0931a1ce04856b2019a6b18e43f48":{
      "scriptId":"u0"},
    "502ad33ee48a4baf8788f2582b1eda53":{
      "scriptId":"u1"},
    "e91d3c852d584a86b2ca4d6fc5cd1c2a":{
      "scriptId":"u2"},
    "f934d712d01c4b318ebd8b919dcf7f78":{
      "scriptId":"u3"},
    "bfb246055c444cd8b5839e56285dd6a3":{
      "scriptId":"u4"},
    "ea31fa167f4e47d38b5363b52713a15c":{
      "scriptId":"u5"},
    "8f395aa25f884e8ab905d9d52181318d":{
      "scriptId":"u6"},
    "82e09b557a3f4df0a8c6f90986dd407a":{
      "scriptId":"u7"},
    "f175b35c92e042a396067b63976e413e":{
      "scriptId":"u8"},
    "87364a0adbfe4d7f99b2960efd5357e9":{
      "scriptId":"u9"},
    "a6a272b022264d97a648495d989819e6":{
      "scriptId":"u10"},
    "4a9dce803e384b05a1c15e54dfc21103":{
      "scriptId":"u11"},
    "83cb5ed4db8f440282ac978a989090e7":{
      "scriptId":"u12"},
    "c2177555a8ba424fb92020795a5bbfc5":{
      "scriptId":"u13"}}});