$axure.loadCurrentPage({
  "url":"通付宝代理商（虚拟）.html",
  "generationDate":new Date(1407117549796.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"efa9d48b305142758c28b20c79e61608",
    "type":"Axure:Page",
    "name":"通付宝代理商（虚拟）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1021ccbe33614940a77e25cda39e873b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":16},
            "size":{
              "width":380,
              "height":744},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f8bf4de125b4ccd951c10957a97a8d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":16},
                "size":{
                  "width":380,
                  "height":744},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（正式）/u0.png"}},
{
          "id":"a30bea4821e6450f90036491586dc514",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":61,
              "y":168},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"be9ff0783498423bb082ed569979609d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":61,
                  "y":168},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（正式）/u2.png"}},
{
          "id":"a9f47ea4c5744514840f52fc78b8ca54",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":72,
              "y":153},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4b07083e043845dd9839454102562455",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":72,
                  "y":153},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（正式）/u4.png"}},
{
          "id":"13d26d363cc5482a953ef1ff72302cc6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":72,
              "y":224},
            "size":{
              "width":223,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d072725f4e5496bad824aa453e82301",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":72,
                  "y":224},
                "size":{
                  "width":223,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"373f8cadb7034a56962c4b608fdb59d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":70,
              "y":259},
            "size":{
              "width":300,
              "height":117}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"814cc8201dd74525a69fda8ade1d9c7a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":70,
                  "y":259},
                "size":{
                  "width":300,
                  "height":117}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（正式）/u8.png"}},
{
          "id":"e6f16737671743bf8da83dc9a42c41d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":72,
              "y":546},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e494d1633dd6434c8912ad10a47aac44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":72,
                  "y":546},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（正式）/u10.png"}},
{
          "id":"69ad71c9ecce4ab89805daf7f25b37f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":300,
              "y":546},
            "size":{
              "width":70,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"532db3706b254dc6a46688fad80c38dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":300,
                  "y":546},
                "size":{
                  "width":70,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（正式）/u12.png"}},
{
          "id":"d4255ccf4fc34d1a8803154e9c7b81f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"center",
            "location":{
              "x":162,
              "y":173},
            "size":{
              "width":108,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c13cf22b24d4da6955592bd4a07415e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "location":{
                  "x":162,
                  "y":173},
                "size":{
                  "width":108,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"79cec9bb307a460fa9c8bb5b4425e378",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "location":{
              "x":291,
              "y":186},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0cb15578dc92470db409ddf76fb487c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "location":{
                  "x":291,
                  "y":186},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"789dcff56f1748c290d38c359d6b8598",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":72,
              "y":396},
            "size":{
              "width":88,
              "height":124}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"676d755aa04d4f2aa20a71efb1fa5398",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":72,
                  "y":396},
                "size":{
                  "width":88,
                  "height":124}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（正式）/u18.png"}},
{
          "id":"aa6b3d8fa293436095f06b5a5cb419e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":190,
              "y":354},
            "size":{
              "width":180,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b3309fab8aa74209b0ee5af935135a84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":190,
                  "y":354},
                "size":{
                  "width":180,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7064a1c1c2ee401ab9d3d0e611acbecb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":142,
              "y":546},
            "size":{
              "width":68,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"40350dde10d949c5adb7c4ab544cfd1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":142,
                  "y":546},
                "size":{
                  "width":68,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（正式）/u22.png"}},
{
          "id":"645fac4999fe403fa26d55b68050f407",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":170,
              "y":396},
            "size":{
              "width":100,
              "height":124}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ca2ce9225194feb948132d8ee80e9c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":170,
                  "y":396},
                "size":{
                  "width":100,
                  "height":124}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（正式）/u24.png"}},
{
          "id":"a398c4fe87d9482896e9142e87c8c41f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":280,
              "y":396},
            "size":{
              "width":90,
              "height":124}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eeb6c96fe636484a9cf0d3a0af153bfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":280,
                  "y":396},
                "size":{
                  "width":90,
                  "height":124}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（正式）/u26.png"}},
{
          "id":"a7e639b41aae4c0092177c5fd02c58f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":220,
              "y":546},
            "size":{
              "width":70,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82aa3496c5274475a9af7173bb33c53c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":220,
                  "y":546},
                "size":{
                  "width":70,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（正式）/u12.png"}},
{
          "id":"0400c4ae5ff240fda6417edeedc239c2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":16},
            "size":{
              "width":380,
              "height":744},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e57d2a05bbc2454cb0dfd7f9ad3a2c3b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":16},
                "size":{
                  "width":380,
                  "height":744},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（正式）/u0.png"}},
{
          "id":"309824249cdb4a3fbc098e972aaaf1d6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":61,
              "y":168},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c3d687abf16a4e33aaf3bcdcb58b2b43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":61,
                  "y":168},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（正式）/u2.png"}},
{
          "id":"ccbf5b2835584856b0d667c4d7bcbf2a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":72,
              "y":153},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ffdce6eadc784eccbf2beebefccc4cc8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":72,
                  "y":153},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（正式）/u4.png"}},
{
          "id":"d0fc506320a249d988879241a135d58e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":72,
              "y":224},
            "size":{
              "width":199,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"46b7ba8bda74414f89a65be37cf75b51",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":72,
                  "y":224},
                "size":{
                  "width":199,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"117a13e9c4214c21945976033109265e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Bold', 'Applied Font'",
            "fontWeight":"700",
            "horizontalAlignment":"left",
            "location":{
              "x":70,
              "y":259},
            "size":{
              "width":300,
              "height":137}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbd56d3fde72484784c5787de7be1137",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Bold', 'Applied Font'",
                "fontWeight":"700",
                "horizontalAlignment":"left",
                "location":{
                  "x":70,
                  "y":259},
                "size":{
                  "width":300,
                  "height":137}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（虚拟）/u38.png"}},
{
          "id":"17b08cb8f5ed4b3688c0e34476b780af",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":310,
              "y":530},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"04e330ddf37e433d9e1c8d63977ea9be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":310,
                  "y":530},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（正式）/u10.png"}},
{
          "id":"8143acce4e13481b82b2b88853d5a6f0",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"center",
            "location":{
              "x":162,
              "y":173},
            "size":{
              "width":108,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ff652d269eb4730a95973a463e57745",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "location":{
                  "x":162,
                  "y":173},
                "size":{
                  "width":108,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4ceaf4041e314a108d519d1245f729f1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "location":{
              "x":291,
              "y":186},
            "size":{
              "width":49,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"61f0fc0d5a5346b1a6ee951d74781bca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "location":{
                  "x":291,
                  "y":186},
                "size":{
                  "width":49,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5d99feb89e8d495eb84ba7b82312bc85",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"400",
            "location":{
              "x":189,
              "y":374},
            "size":{
              "width":180,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b46ecffd63c747acad7ddc7e819a0211",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"400",
                "location":{
                  "x":189,
                  "y":374},
                "size":{
                  "width":180,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9bc85015817548ff89f8f73995a0a7c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":231,
              "y":426},
            "size":{
              "width":139,
              "height":84}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"722a13ca1fb64b31b9d8201dd22706d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":231,
                  "y":426},
                "size":{
                  "width":139,
                  "height":84}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（虚拟）/u48.png"}},
{
          "id":"15e7ddfae2cc49a8976cfda3964ffb4d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":240,
              "y":530},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bd3d66baa6454a808e9b3a32bb2b0ca0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":240,
                  "y":530},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 转让清单",
                      "target":{
                        "targetType":"page",
                        "url":"转让清单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/通付宝代理商（正式）/u10.png"}},
{
          "id":"a3d7f3b61c954a76b09db3865f9ea219",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":72,
              "y":530},
            "size":{
              "width":60,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fbc0a012bd794902baf3f116eb96b726",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":72,
                  "y":530},
                "size":{
                  "width":60,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（正式）/u10.png"}},
{
          "id":"722f87bbe1a04782aa68dbd5063afacf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":142,
              "y":530},
            "size":{
              "width":78,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbad9d530fc248a886d817460a996e1f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":142,
                  "y":530},
                "size":{
                  "width":78,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（虚拟）/u54.png"}},
{
          "id":"569e7095549147b8bcdbb642e5f35922",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":72,
              "y":423},
            "size":{
              "width":149,
              "height":87}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ac231ea50a543b197581a21cf20f78a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":72,
                  "y":423},
                "size":{
                  "width":149,
                  "height":87}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝代理商（虚拟）/u56.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "1021ccbe33614940a77e25cda39e873b":{
      "scriptId":"u0"},
    "6f8bf4de125b4ccd951c10957a97a8d9":{
      "scriptId":"u1"},
    "a30bea4821e6450f90036491586dc514":{
      "scriptId":"u2"},
    "be9ff0783498423bb082ed569979609d":{
      "scriptId":"u3"},
    "a9f47ea4c5744514840f52fc78b8ca54":{
      "scriptId":"u4"},
    "4b07083e043845dd9839454102562455":{
      "scriptId":"u5"},
    "13d26d363cc5482a953ef1ff72302cc6":{
      "scriptId":"u6"},
    "0d072725f4e5496bad824aa453e82301":{
      "scriptId":"u7"},
    "373f8cadb7034a56962c4b608fdb59d3":{
      "scriptId":"u8"},
    "814cc8201dd74525a69fda8ade1d9c7a":{
      "scriptId":"u9"},
    "e6f16737671743bf8da83dc9a42c41d7":{
      "scriptId":"u10"},
    "e494d1633dd6434c8912ad10a47aac44":{
      "scriptId":"u11"},
    "69ad71c9ecce4ab89805daf7f25b37f8":{
      "scriptId":"u12"},
    "532db3706b254dc6a46688fad80c38dd":{
      "scriptId":"u13"},
    "d4255ccf4fc34d1a8803154e9c7b81f6":{
      "scriptId":"u14"},
    "8c13cf22b24d4da6955592bd4a07415e":{
      "scriptId":"u15"},
    "79cec9bb307a460fa9c8bb5b4425e378":{
      "scriptId":"u16"},
    "0cb15578dc92470db409ddf76fb487c3":{
      "scriptId":"u17"},
    "789dcff56f1748c290d38c359d6b8598":{
      "scriptId":"u18"},
    "676d755aa04d4f2aa20a71efb1fa5398":{
      "scriptId":"u19"},
    "aa6b3d8fa293436095f06b5a5cb419e6":{
      "scriptId":"u20"},
    "b3309fab8aa74209b0ee5af935135a84":{
      "scriptId":"u21"},
    "7064a1c1c2ee401ab9d3d0e611acbecb":{
      "scriptId":"u22"},
    "40350dde10d949c5adb7c4ab544cfd1f":{
      "scriptId":"u23"},
    "645fac4999fe403fa26d55b68050f407":{
      "scriptId":"u24"},
    "3ca2ce9225194feb948132d8ee80e9c8":{
      "scriptId":"u25"},
    "a398c4fe87d9482896e9142e87c8c41f":{
      "scriptId":"u26"},
    "eeb6c96fe636484a9cf0d3a0af153bfb":{
      "scriptId":"u27"},
    "a7e639b41aae4c0092177c5fd02c58f6":{
      "scriptId":"u28"},
    "82aa3496c5274475a9af7173bb33c53c":{
      "scriptId":"u29"},
    "0400c4ae5ff240fda6417edeedc239c2":{
      "scriptId":"u30"},
    "e57d2a05bbc2454cb0dfd7f9ad3a2c3b":{
      "scriptId":"u31"},
    "309824249cdb4a3fbc098e972aaaf1d6":{
      "scriptId":"u32"},
    "c3d687abf16a4e33aaf3bcdcb58b2b43":{
      "scriptId":"u33"},
    "ccbf5b2835584856b0d667c4d7bcbf2a":{
      "scriptId":"u34"},
    "ffdce6eadc784eccbf2beebefccc4cc8":{
      "scriptId":"u35"},
    "d0fc506320a249d988879241a135d58e":{
      "scriptId":"u36"},
    "46b7ba8bda74414f89a65be37cf75b51":{
      "scriptId":"u37"},
    "117a13e9c4214c21945976033109265e":{
      "scriptId":"u38"},
    "dbd56d3fde72484784c5787de7be1137":{
      "scriptId":"u39"},
    "17b08cb8f5ed4b3688c0e34476b780af":{
      "scriptId":"u40"},
    "04e330ddf37e433d9e1c8d63977ea9be":{
      "scriptId":"u41"},
    "8143acce4e13481b82b2b88853d5a6f0":{
      "scriptId":"u42"},
    "9ff652d269eb4730a95973a463e57745":{
      "scriptId":"u43"},
    "4ceaf4041e314a108d519d1245f729f1":{
      "scriptId":"u44"},
    "61f0fc0d5a5346b1a6ee951d74781bca":{
      "scriptId":"u45"},
    "5d99feb89e8d495eb84ba7b82312bc85":{
      "scriptId":"u46"},
    "b46ecffd63c747acad7ddc7e819a0211":{
      "scriptId":"u47"},
    "9bc85015817548ff89f8f73995a0a7c5":{
      "scriptId":"u48"},
    "722a13ca1fb64b31b9d8201dd22706d7":{
      "scriptId":"u49"},
    "15e7ddfae2cc49a8976cfda3964ffb4d":{
      "scriptId":"u50"},
    "bd3d66baa6454a808e9b3a32bb2b0ca0":{
      "scriptId":"u51"},
    "a3d7f3b61c954a76b09db3865f9ea219":{
      "scriptId":"u52"},
    "fbc0a012bd794902baf3f116eb96b726":{
      "scriptId":"u53"},
    "722f87bbe1a04782aa68dbd5063afacf":{
      "scriptId":"u54"},
    "dbad9d530fc248a886d817460a996e1f":{
      "scriptId":"u55"},
    "569e7095549147b8bcdbb642e5f35922":{
      "scriptId":"u56"},
    "4ac231ea50a543b197581a21cf20f78a":{
      "scriptId":"u57"}}});