$axure.loadCurrentPage({
  "url":"功能列表（新）支付.html",
  "generationDate":new Date(1399184856079.62),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b3ebf204a4db401c8457ffae0e547fb3",
    "type":"Axure:Page",
    "name":"功能列表（新）支付",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b29a8fcd616547e18b0a7bce809672de",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":81},
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9f975b9564744ab7add754e47adbc00b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":81},
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u0.png"}},
{
          "id":"a003f1119a58413aad0f63e075185bbc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":202},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"451b565cde7848b29400589e8d8f53bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":202},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u2.png"}},
{
          "id":"35178d9e34f54765bbb8da26390213ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":720},
            "size":{
              "width":92,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3e534c45eec8477c8368cf2f42befa00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":720},
                "size":{
                  "width":92,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u4.png"}},
{
          "id":"c786a72c077a4dbd8276af9d9d07949a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":165,
              "y":720},
            "size":{
              "width":90,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73e4b80d5b2d4094969bc139e9ed7344",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":165,
                  "y":720},
                "size":{
                  "width":90,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u6.png"}},
{
          "id":"bf9957cdd3b84851a994fe066490a699",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":270,
              "y":720},
            "size":{
              "width":90,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8551170dd4a64eaeb4f6e3e00ece49a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":270,
                  "y":720},
                "size":{
                  "width":90,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u6.png"}},
{
          "id":"aedc9a20c1bb4b2d8f5c975b4813bd47",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":389},
            "size":{
              "width":87,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a684f61a5aa46559df3b69f9a5166d1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":389},
                "size":{
                  "width":87,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u10.png"}},
{
          "id":"67b41f90d30b4452a8a2e01bb1db2c1d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":55,
              "y":222},
            "size":{
              "width":108,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c76337cc70254612a3d55169a895655f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":55,
                  "y":222},
                "size":{
                  "width":108,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u12.png"}},
{
          "id":"d577b97c6b564b57b36d730ffca6840c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":169,
              "y":390},
            "size":{
              "width":163,
              "height":130}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3dfc680c6fb84489a7a139709258446b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":169,
                  "y":390},
                "size":{
                  "width":163,
                  "height":130}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u14.png"}},
{
          "id":"d9ed5f9260e74e229626f862b5ad4a62",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":71,
              "y":460},
            "size":{
              "width":87,
              "height":128}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3495305c0ff14b4b8cbc4391e8fde851",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":71,
                  "y":460},
                "size":{
                  "width":87,
                  "height":128}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u16.png"}},
{
          "id":"0e78e26fd3bc45459394ffd915d35b26",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":168,
              "y":530},
            "size":{
              "width":163,
              "height":58}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cfe2eb8b1c2c4496b029e0e0ab01ac56",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":168,
                  "y":530},
                "size":{
                  "width":163,
                  "height":58}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u18.png"}},
{
          "id":"d9fb34eb6b7f41cfbff021e3dfe66aa8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":598},
            "size":{
              "width":158,
              "height":95}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5281962caad0490387a98b94dc90a86f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":598},
                "size":{
                  "width":158,
                  "height":95}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u20.png"}},
{
          "id":"385840ff8d334de8a8872ac398763699",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":162,
              "y":222},
            "size":{
              "width":99,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1c8c32e386e945e9b27237379b6f31f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":162,
                  "y":222},
                "size":{
                  "width":99,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u22.png"}},
{
          "id":"287d56d5b327454980cff2c9ec152a03",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":222},
            "size":{
              "width":108,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f1e6355e7e224f2aae862bb94d7aad32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":222},
                "size":{
                  "width":108,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u12.png"}},
{
          "id":"bd3f1fe574f6436f80c8562bca61b540",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":72,
              "y":280},
            "size":{
              "width":168,
              "height":89}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b4683ad6d26472cbfbc0b07f8929a47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":72,
                  "y":280},
                "size":{
                  "width":168,
                  "height":89}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u26.png"}},
{
          "id":"05123002558f4be0af43bc63cf8dc502",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":260,
              "y":280},
            "size":{
              "width":72,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d136ff2c7114c6da45c9d34a2d5a98e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":260,
                  "y":280},
                "size":{
                  "width":72,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u28.png"}},
{
          "id":"86fb0b2af66a464791a1defecea17c44",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":267},
            "size":{
              "width":200,
              "height":73}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"23281353fbfb46baa555de94adea4933",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":267},
                "size":{
                  "width":200,
                  "height":73}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u30.png"}},
{
          "id":"8f7e486ec6df43c58ace8c45b3e3d521",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":250,
              "y":598},
            "size":{
              "width":81,
              "height":95}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9ba2ae787ca54d5cabe1f4ef7da573fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":250,
                  "y":598},
                "size":{
                  "width":81,
                  "height":95}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u32.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "b29a8fcd616547e18b0a7bce809672de":{
      "scriptId":"u0"},
    "9f975b9564744ab7add754e47adbc00b":{
      "scriptId":"u1"},
    "a003f1119a58413aad0f63e075185bbc":{
      "scriptId":"u2"},
    "451b565cde7848b29400589e8d8f53bf":{
      "scriptId":"u3"},
    "35178d9e34f54765bbb8da26390213ff":{
      "scriptId":"u4"},
    "3e534c45eec8477c8368cf2f42befa00":{
      "scriptId":"u5"},
    "c786a72c077a4dbd8276af9d9d07949a":{
      "scriptId":"u6"},
    "73e4b80d5b2d4094969bc139e9ed7344":{
      "scriptId":"u7"},
    "bf9957cdd3b84851a994fe066490a699":{
      "scriptId":"u8"},
    "8551170dd4a64eaeb4f6e3e00ece49a4":{
      "scriptId":"u9"},
    "aedc9a20c1bb4b2d8f5c975b4813bd47":{
      "scriptId":"u10"},
    "9a684f61a5aa46559df3b69f9a5166d1":{
      "scriptId":"u11"},
    "67b41f90d30b4452a8a2e01bb1db2c1d":{
      "scriptId":"u12"},
    "c76337cc70254612a3d55169a895655f":{
      "scriptId":"u13"},
    "d577b97c6b564b57b36d730ffca6840c":{
      "scriptId":"u14"},
    "3dfc680c6fb84489a7a139709258446b":{
      "scriptId":"u15"},
    "d9ed5f9260e74e229626f862b5ad4a62":{
      "scriptId":"u16"},
    "3495305c0ff14b4b8cbc4391e8fde851":{
      "scriptId":"u17"},
    "0e78e26fd3bc45459394ffd915d35b26":{
      "scriptId":"u18"},
    "cfe2eb8b1c2c4496b029e0e0ab01ac56":{
      "scriptId":"u19"},
    "d9fb34eb6b7f41cfbff021e3dfe66aa8":{
      "scriptId":"u20"},
    "5281962caad0490387a98b94dc90a86f":{
      "scriptId":"u21"},
    "385840ff8d334de8a8872ac398763699":{
      "scriptId":"u22"},
    "1c8c32e386e945e9b27237379b6f31f0":{
      "scriptId":"u23"},
    "287d56d5b327454980cff2c9ec152a03":{
      "scriptId":"u24"},
    "f1e6355e7e224f2aae862bb94d7aad32":{
      "scriptId":"u25"},
    "bd3f1fe574f6436f80c8562bca61b540":{
      "scriptId":"u26"},
    "2b4683ad6d26472cbfbc0b07f8929a47":{
      "scriptId":"u27"},
    "05123002558f4be0af43bc63cf8dc502":{
      "scriptId":"u28"},
    "8d136ff2c7114c6da45c9d34a2d5a98e":{
      "scriptId":"u29"},
    "86fb0b2af66a464791a1defecea17c44":{
      "scriptId":"u30"},
    "23281353fbfb46baa555de94adea4933":{
      "scriptId":"u31"},
    "8f7e486ec6df43c58ace8c45b3e3d521":{
      "scriptId":"u32"},
    "9ba2ae787ca54d5cabe1f4ef7da573fe":{
      "scriptId":"u33"}}});