$axure.loadCurrentPage({
  "url":"指定财务（舍弃）.html",
  "generationDate":new Date(1411007650312.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"997da6ca7f0148c6a26dd48cc55473c8",
    "type":"Axure:Page",
    "name":"指定财务（舍弃）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"aede9abf0427456a94cb5cf7fc0cefce",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":26},
            "size":{
              "width":380,
              "height":744},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef7a04d7de53452e9fc788926d6fc5ae",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":26},
                "size":{
                  "width":380,
                  "height":744},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工资收发/u0.png"}},
{
          "id":"e2d5b73a23c64864babcae412d8fa180",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":51,
              "y":178},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"348020154acd461e925a4566d93b212b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":51,
                  "y":178},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工资收发/u2.png"}},
{
          "id":"41ece690f6574735ad4e191c4d1fc412",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":163},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"79cd7dca3f3145e9a11c05325c079eb6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":163},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工资收发/u4.png"}},
{
          "id":"12cecf8374974946b1e4a9663b3f342d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":51,
              "y":181},
            "size":{
              "width":71,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7eb8a9d9578c4848bf4c96c90a82fdcc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":51,
                  "y":181},
                "size":{
                  "width":71,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 工资发放",
                      "target":{
                        "targetType":"page",
                        "url":"工资发放.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/工资收发/u6.png"}},
{
          "id":"e379b207fb484f6dab2b3c7de41ee6db",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":152,
              "y":182},
            "size":{
              "width":148,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"444cd7af05dd45ba8e2f0c7dcf5d3855",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":152,
                  "y":182},
                "size":{
                  "width":148,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3e1b3c69b84e4ac0bf290f8faf3ea74d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":62,
              "y":271},
            "size":{
              "width":298,
              "height":59}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8301d6e55199455abe3437c780ced6bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":62,
                  "y":271},
                "size":{
                  "width":298,
                  "height":59}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/指定财务（舍弃）/u10.png"}},
{
          "id":"f0b1d7bd22cb4b47b7b8525124271603",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":62,
              "y":340},
            "size":{
              "width":298,
              "height":91}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70f3b70054ba4f1bb7a3166893519f79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":62,
                  "y":340},
                "size":{
                  "width":298,
                  "height":91}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/指定财务（舍弃）/u12.png"}},
{
          "id":"319923418d9447d1b2f343af5086e010",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":450},
            "size":{
              "width":298,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9fd1a7ec525c4390ac6cd5fc1aec5cb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":450},
                "size":{
                  "width":298,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 工资发放",
                      "target":{
                        "targetType":"page",
                        "url":"工资发放.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/工资收发/u10.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "aede9abf0427456a94cb5cf7fc0cefce":{
      "scriptId":"u0"},
    "ef7a04d7de53452e9fc788926d6fc5ae":{
      "scriptId":"u1"},
    "e2d5b73a23c64864babcae412d8fa180":{
      "scriptId":"u2"},
    "348020154acd461e925a4566d93b212b":{
      "scriptId":"u3"},
    "41ece690f6574735ad4e191c4d1fc412":{
      "scriptId":"u4"},
    "79cd7dca3f3145e9a11c05325c079eb6":{
      "scriptId":"u5"},
    "12cecf8374974946b1e4a9663b3f342d":{
      "scriptId":"u6"},
    "7eb8a9d9578c4848bf4c96c90a82fdcc":{
      "scriptId":"u7"},
    "e379b207fb484f6dab2b3c7de41ee6db":{
      "scriptId":"u8"},
    "444cd7af05dd45ba8e2f0c7dcf5d3855":{
      "scriptId":"u9"},
    "3e1b3c69b84e4ac0bf290f8faf3ea74d":{
      "scriptId":"u10"},
    "8301d6e55199455abe3437c780ced6bb":{
      "scriptId":"u11"},
    "f0b1d7bd22cb4b47b7b8525124271603":{
      "scriptId":"u12"},
    "70f3b70054ba4f1bb7a3166893519f79":{
      "scriptId":"u13"},
    "319923418d9447d1b2f343af5086e010":{
      "scriptId":"u14"},
    "9fd1a7ec525c4390ac6cd5fc1aec5cb1":{
      "scriptId":"u15"}}});