$axure.loadCurrentPage({
  "url":"通付宝订单支付.html",
  "generationDate":new Date(1411696817593.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"4142154faaa744b1baceb13049660081",
    "type":"Axure:Page",
    "name":"通付宝订单支付",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5ff613e1c7df410c829b7fbd1122fff2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":20},
            "size":{
              "width":390,
              "height":744},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ad0090d183c46a6ae2619c66258521d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":20},
                "size":{
                  "width":390,
                  "height":744},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝订单支付/u0.png"}},
{
          "id":"b5ccea8e7c5a46318e3bda83ff69905b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":163},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9715cbc5db224858b0e855011bbd4784",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":163},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝订单支付/u2.png"}},
{
          "id":"251b98fa9a02481f9d99aa23515219ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"center",
            "location":{
              "x":143,
              "y":186},
            "size":{
              "width":164,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90c11551ab724dbd9a4498d949ee1d9c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "location":{
                  "x":143,
                  "y":186},
                "size":{
                  "width":164,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98de51ed703b46f9beeeb3aab76ac08e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":95,
              "y":580},
            "size":{
              "width":260,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe5dab312b11437f8774ad7c814bb856",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":95,
                  "y":580},
                "size":{
                  "width":260,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 手机验证",
                      "target":{
                        "targetType":"page",
                        "url":"手机验证.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/通付宝订单支付/u6.png"}},
{
          "id":"d6d023db4b9c4c4ba7e9b4a192ca0f34",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":70,
              "y":233},
            "size":{
              "width":310,
              "height":178}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dbe7e6876fb9438abf71b1fb3f41b4e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":70,
                  "y":233},
                "size":{
                  "width":310,
                  "height":178}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝订单支付/u8.png"}},
{
          "id":"620b75da78e74cc782c556f85699e817",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":430,
              "y":230},
            "size":{
              "width":350,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58e972b909ad46b483bafaebe4568430",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":430,
                  "y":230},
                "size":{
                  "width":350,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝订单支付/u10.png"}},
{
          "id":"8da4cfafe0134fbb81d51cf1934690a2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":70,
              "y":411},
            "size":{
              "width":310,
              "height":149}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"374988c28e1f4c0da84b099c0b4047a8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":70,
                  "y":411},
                "size":{
                  "width":310,
                  "height":149}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝订单支付/u12.png"}},
{
          "id":"a53440b5d1334987a844bf2d620e8cb1",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":80,
              "y":448},
            "size":{
              "width":227,
              "height":32}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5b075216023e4962888322817357b026",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":80,
                  "y":448},
                "size":{
                  "width":227,
                  "height":32}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c565d11bd2c34645928a82520fb3c0a4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":317,
              "y":460},
            "size":{
              "width":53,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c2ff13e4d214475a85c93b3c125d7a0e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":317,
                  "y":460},
                "size":{
                  "width":53,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的银行卡",
                      "target":{
                        "targetType":"page",
                        "url":"我的银行卡.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/通付宝订单支付/u16.png"}},
{
          "id":"3d87eb4245d543e08c642558e013bcf9",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":80,
              "y":490},
            "size":{
              "width":140,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d53c327a86546f79e14c32dda31c092",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":80,
                  "y":490},
                "size":{
                  "width":140,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 刷卡支付",
                      "target":{
                        "targetType":"page",
                        "url":"刷卡支付.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"227a5d15ce56476f8a9fdb60e41dc5d5",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":80,
              "y":520},
            "size":{
              "width":140,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eb077648e0b64ee1bb65b298eb46c1bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":80,
                  "y":520},
                "size":{
                  "width":140,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 优惠卡支付",
                      "target":{
                        "targetType":"page",
                        "url":"优惠卡支付.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"831d5eabea134d50a1556008bdf526f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":430,
              "y":411},
            "size":{
              "width":350,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42f48840ab0442e2ad23879b0a81824a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":430,
                  "y":411},
                "size":{
                  "width":350,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝订单支付/u22.png"}},
{
          "id":"3c9a1ef6b85c4667adfa3f0f3bc57cfe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":430,
              "y":460},
            "size":{
              "width":350,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2f6ec6099dba4bf4be6a4f88b62ab361",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":430,
                  "y":460},
                "size":{
                  "width":350,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝订单支付/u24.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "5ff613e1c7df410c829b7fbd1122fff2":{
      "scriptId":"u0"},
    "8ad0090d183c46a6ae2619c66258521d":{
      "scriptId":"u1"},
    "b5ccea8e7c5a46318e3bda83ff69905b":{
      "scriptId":"u2"},
    "9715cbc5db224858b0e855011bbd4784":{
      "scriptId":"u3"},
    "251b98fa9a02481f9d99aa23515219ef":{
      "scriptId":"u4"},
    "90c11551ab724dbd9a4498d949ee1d9c":{
      "scriptId":"u5"},
    "98de51ed703b46f9beeeb3aab76ac08e":{
      "scriptId":"u6"},
    "fe5dab312b11437f8774ad7c814bb856":{
      "scriptId":"u7"},
    "d6d023db4b9c4c4ba7e9b4a192ca0f34":{
      "scriptId":"u8"},
    "dbe7e6876fb9438abf71b1fb3f41b4e8":{
      "scriptId":"u9"},
    "620b75da78e74cc782c556f85699e817":{
      "scriptId":"u10"},
    "58e972b909ad46b483bafaebe4568430":{
      "scriptId":"u11"},
    "8da4cfafe0134fbb81d51cf1934690a2":{
      "scriptId":"u12"},
    "374988c28e1f4c0da84b099c0b4047a8":{
      "scriptId":"u13"},
    "a53440b5d1334987a844bf2d620e8cb1":{
      "scriptId":"u14"},
    "5b075216023e4962888322817357b026":{
      "scriptId":"u15"},
    "c565d11bd2c34645928a82520fb3c0a4":{
      "scriptId":"u16"},
    "c2ff13e4d214475a85c93b3c125d7a0e":{
      "scriptId":"u17"},
    "3d87eb4245d543e08c642558e013bcf9":{
      "scriptId":"u18"},
    "4d53c327a86546f79e14c32dda31c092":{
      "scriptId":"u19"},
    "227a5d15ce56476f8a9fdb60e41dc5d5":{
      "scriptId":"u20"},
    "eb077648e0b64ee1bb65b298eb46c1bf":{
      "scriptId":"u21"},
    "831d5eabea134d50a1556008bdf526f9":{
      "scriptId":"u22"},
    "42f48840ab0442e2ad23879b0a81824a":{
      "scriptId":"u23"},
    "3c9a1ef6b85c4667adfa3f0f3bc57cfe":{
      "scriptId":"u24"},
    "2f6ec6099dba4bf4be6a4f88b62ab361":{
      "scriptId":"u25"}}});