$axure.loadCurrentPage({
  "url":"向×××付款.html",
  "generationDate":new Date(1399184856543.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"1664ebd670f64cf19db9598f32e6a6a8",
    "type":"Axure:Page",
    "name":"向×××付款",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e3ba26631a6e4ef2871345538d792cbf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":208},
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"80fe263e8f774d7db903f6b97a65ef2f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":208},
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u0.png"}},
{
          "id":"34f1d64a03a24f8d998a9ab2a359127c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":132,
              "y":329},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d2d1714b49b74b3c97b1d781a16f6665",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":132,
                  "y":329},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u2.png"}},
{
          "id":"1dd9612573b84b51adf2ebfdfdf84297",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":132,
              "y":847},
            "size":{
              "width":92,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"873bd842fe3249959b96076b3381c2bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":132,
                  "y":847},
                "size":{
                  "width":92,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u4.png"}},
{
          "id":"f111b769ab7749b38dd702b23f97b29f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":239,
              "y":847},
            "size":{
              "width":90,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"393179e0df8a4a89999ec3456416db1b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":239,
                  "y":847},
                "size":{
                  "width":90,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u6.png"}},
{
          "id":"f06c035480ab4fc28153d969ee38110d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":344,
              "y":847},
            "size":{
              "width":90,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d1f6cd04f67410cb9a53c4e5f5d0cc1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":344,
                  "y":847},
                "size":{
                  "width":90,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/功能列表（新）支付/u6.png"}},
{
          "id":"1d621d2b2a5a4987b472076bd2ff2c71",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":349},
            "size":{
              "width":250,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"950895376603416494ac51d3fb0cb218",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":349},
                "size":{
                  "width":250,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当面支付（响应支付）/u4.png"}},
{
          "id":"d650f03794204de2b67ff6d6f52d9907",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":414},
            "size":{
              "width":250,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6553ae8c75624b2280e202110c41dbfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":414},
                "size":{
                  "width":250,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/向×××付款/u12.png"}},
{
          "id":"cd6add0383434a0e8923040bae1ae2ce",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":480},
            "size":{
              "width":250,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec7185fadea74f78a22daa969b7bf5fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":480},
                "size":{
                  "width":250,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/向×××付款/u14.png"}},
{
          "id":"e66b7e627cf24ffa9e6e556bd526a372",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":234,
              "y":690},
            "size":{
              "width":100,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"4f4e2a0450e24b8bb3577149772de93c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":136,
              "y":728},
            "size":{
              "width":189,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9091e25d7cea43a6a975fe05de10a18c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":136,
                  "y":728},
                "size":{
                  "width":189,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/向×××付款/u17.png"}},
{
          "id":"492dba51c95c4953bc50d6616af93c43",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":728},
            "size":{
              "width":108,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3906e85454384192bbf0749687ff8fe5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":325,
                  "y":728},
                "size":{
                  "width":108,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当面支付（发起支付）/u8.jpg"}},
{
          "id":"d09fc3fbfecb42ce843fc94dd7ac99dd",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":604},
            "size":{
              "width":200,
              "height":61}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"722cca140b9d4d3bae70afb09550c6fe",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":604},
                "size":{
                  "width":200,
                  "height":61}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当面支付（响应支付）/u21.png"}},
{
          "id":"15d21163a0084e2aa0ce013338f43812",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":184,
              "y":560},
            "size":{
              "width":200,
              "height":90}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a47ba583e859461caf14fef9897c0c1a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":184,
                  "y":560},
                "size":{
                  "width":200,
                  "height":90}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/向×××付款/u23.png"}},
{
          "id":"3e990ca343d84cb0af1c4185e4f6a60d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":408,
              "y":594},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"62846a875e9041f886078c46e4632689",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":408,
                  "y":594},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/向×××付款/u25.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e3ba26631a6e4ef2871345538d792cbf":{
      "scriptId":"u0"},
    "80fe263e8f774d7db903f6b97a65ef2f":{
      "scriptId":"u1"},
    "34f1d64a03a24f8d998a9ab2a359127c":{
      "scriptId":"u2"},
    "d2d1714b49b74b3c97b1d781a16f6665":{
      "scriptId":"u3"},
    "1dd9612573b84b51adf2ebfdfdf84297":{
      "scriptId":"u4"},
    "873bd842fe3249959b96076b3381c2bb":{
      "scriptId":"u5"},
    "f111b769ab7749b38dd702b23f97b29f":{
      "scriptId":"u6"},
    "393179e0df8a4a89999ec3456416db1b":{
      "scriptId":"u7"},
    "f06c035480ab4fc28153d969ee38110d":{
      "scriptId":"u8"},
    "8d1f6cd04f67410cb9a53c4e5f5d0cc1":{
      "scriptId":"u9"},
    "1d621d2b2a5a4987b472076bd2ff2c71":{
      "scriptId":"u10"},
    "950895376603416494ac51d3fb0cb218":{
      "scriptId":"u11"},
    "d650f03794204de2b67ff6d6f52d9907":{
      "scriptId":"u12"},
    "6553ae8c75624b2280e202110c41dbfb":{
      "scriptId":"u13"},
    "cd6add0383434a0e8923040bae1ae2ce":{
      "scriptId":"u14"},
    "ec7185fadea74f78a22daa969b7bf5fa":{
      "scriptId":"u15"},
    "e66b7e627cf24ffa9e6e556bd526a372":{
      "scriptId":"u16"},
    "4f4e2a0450e24b8bb3577149772de93c":{
      "scriptId":"u17"},
    "9091e25d7cea43a6a975fe05de10a18c":{
      "scriptId":"u18"},
    "492dba51c95c4953bc50d6616af93c43":{
      "scriptId":"u19"},
    "3906e85454384192bbf0749687ff8fe5":{
      "scriptId":"u20"},
    "d09fc3fbfecb42ce843fc94dd7ac99dd":{
      "scriptId":"u21"},
    "722cca140b9d4d3bae70afb09550c6fe":{
      "scriptId":"u22"},
    "15d21163a0084e2aa0ce013338f43812":{
      "scriptId":"u23"},
    "a47ba583e859461caf14fef9897c0c1a":{
      "scriptId":"u24"},
    "3e990ca343d84cb0af1c4185e4f6a60d":{
      "scriptId":"u25"},
    "62846a875e9041f886078c46e4632689":{
      "scriptId":"u26"}}});