$axure.loadCurrentPage({
  "url":"授权码使用界面（有授权码）.html",
  "generationDate":new Date(1416631107546.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"15c316634a074ab3923c6f87eef5e6ec",
    "type":"Axure:Page",
    "name":"授权码使用界面（有授权码）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d686c9dc9d714a089eb1f4137b0f8a5b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":20},
            "size":{
              "width":380,
              "height":744},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36f421f727d34a5691eb188832976ea8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":20},
                "size":{
                  "width":380,
                  "height":744},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买授权码/u0.png"}},
{
          "id":"644b8dce9526495e992e0585e3b46568",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":163},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a44fdd9541574647868694ce09a7be7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":163},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买授权码/u2.png"}},
{
          "id":"ea60e4b22b714fbd8523cc16933840f9",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"center",
            "location":{
              "x":141,
              "y":193},
            "size":{
              "width":150,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"904cce76e2924f20a830ef4edccb9a4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"center",
                "location":{
                  "x":141,
                  "y":193},
                "size":{
                  "width":150,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8e6d4673b0dd460dbb7cee08df008725",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":70,
              "y":340},
            "size":{
              "width":300,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ad7426af08f4684ba0f47ca5cebd046",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":70,
                  "y":340},
                "size":{
                  "width":300,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买授权码/u8.png"}},
{
          "id":"0888ccbc3b3e4fe5823e162d429267b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":70,
              "y":520},
            "size":{
              "width":300,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"547fd2306537459fb6ff4c01e07ec1b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":70,
                  "y":520},
                "size":{
                  "width":300,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买授权码/u14.png"}},
{
          "id":"88de1b80aed14302a77c05d5ab96667c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":430,
              "y":250},
            "size":{
              "width":260,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6ef43fcf1754b39bb8a00c938fae526",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":430,
                  "y":250},
                "size":{
                  "width":260,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/授权码使用界面（有授权码）/u10.png"}},
{
          "id":"283998c94cdf43d9a6b8322959be2ce7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":70,
              "y":250},
            "size":{
              "width":300,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"73bc315d3bd74671bffdf4dc0a9c2979",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":70,
                  "y":250},
                "size":{
                  "width":300,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/授权码使用界面（有授权码）/u12.png"}},
{
          "id":"c7c0bb0e2bfd49ad9a289b7173bf6354",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":70,
              "y":301},
            "size":{
              "width":300,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a08956ce3c054e098f2edf8adf86088d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":70,
                  "y":301},
                "size":{
                  "width":300,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/授权码使用界面（有授权码）/u12.png"}},
{
          "id":"05610d51eba247f9bcdeca50c285259d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":430,
              "y":340},
            "size":{
              "width":260,
              "height":46}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7fee107a3f944ee0b732ffbfc5652f1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":430,
                  "y":340},
                "size":{
                  "width":260,
                  "height":46}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/授权码使用界面（有授权码）/u16.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d686c9dc9d714a089eb1f4137b0f8a5b":{
      "scriptId":"u0"},
    "36f421f727d34a5691eb188832976ea8":{
      "scriptId":"u1"},
    "644b8dce9526495e992e0585e3b46568":{
      "scriptId":"u2"},
    "a44fdd9541574647868694ce09a7be7f":{
      "scriptId":"u3"},
    "ea60e4b22b714fbd8523cc16933840f9":{
      "scriptId":"u4"},
    "904cce76e2924f20a830ef4edccb9a4b":{
      "scriptId":"u5"},
    "8e6d4673b0dd460dbb7cee08df008725":{
      "scriptId":"u6"},
    "3ad7426af08f4684ba0f47ca5cebd046":{
      "scriptId":"u7"},
    "0888ccbc3b3e4fe5823e162d429267b1":{
      "scriptId":"u8"},
    "547fd2306537459fb6ff4c01e07ec1b7":{
      "scriptId":"u9"},
    "88de1b80aed14302a77c05d5ab96667c":{
      "scriptId":"u10"},
    "f6ef43fcf1754b39bb8a00c938fae526":{
      "scriptId":"u11"},
    "283998c94cdf43d9a6b8322959be2ce7":{
      "scriptId":"u12"},
    "73bc315d3bd74671bffdf4dc0a9c2979":{
      "scriptId":"u13"},
    "c7c0bb0e2bfd49ad9a289b7173bf6354":{
      "scriptId":"u14"},
    "a08956ce3c054e098f2edf8adf86088d":{
      "scriptId":"u15"},
    "05610d51eba247f9bcdeca50c285259d":{
      "scriptId":"u16"},
    "7fee107a3f944ee0b732ffbfc5652f1d":{
      "scriptId":"u17"}}});