$axure.loadCurrentPage({
  "url":"支付页面.html",
  "generationDate":new Date(1405580874265.63),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b293a0e9fae2424b962207fd8592a205",
    "type":"Axure:Page",
    "name":"支付页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"a8c27754e13241d697415cc749e8a4a8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"611d1a99833a4c24a39f839a9575d3e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"moveWidget",
                      "description":"Move Widget",
                      "objectsToMoves":[]},
{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]},
{
                      "action":"moveWidget",
                      "description":"Move Widget",
                      "objectsToMoves":[]},
{
                      "action":"setPanelState",
                      "description":"Set Panel to State",
                      "panelsToStates":[]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/机票酒店预定/u0.png"}},
{
          "id":"e15b51cdc84e475b86d00dede27d992b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":33,
              "y":117},
            "size":{
              "width":320,
              "height":16},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ac42668389b448ea34f951bfa605a69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":33,
                  "y":117},
                "size":{
                  "width":320,
                  "height":16},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机票酒店预定/u2.png"}},
{
          "id":"4822bca34832412c851e36bbd161b638",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":33,
              "y":132},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5a2a684398c8498bb4d675f9eed7eaa6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":33,
                  "y":132},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/机票酒店预定/u4.png"}},
{
          "id":"36184846065f48d8a5ebcf6d6cdba857",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"21px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":145,
              "y":144},
            "size":{
              "width":95,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4d69d91bdbe84f42a964455928b43e3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"21px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":145,
                  "y":144},
                "size":{
                  "width":95,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"610d8c1e45ab4119a16a4a3474c74a92",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "location":{
              "x":44,
              "y":145},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"401683f743e1449e92ca9175ebf56e20",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "location":{
                  "x":44,
                  "y":145},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 购票订单",
                      "target":{
                        "targetType":"page",
                        "url":"购票订单.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/机票预定/u8.png"}},
{
          "id":"52d28b3c1ade4631ac51a6ccff2adf51",
          "label":"paragraph",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2087FC,
              "opacity":1},
            "location":{
              "x":61,
              "y":147},
            "size":{
              "width":39,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5c5071a7ff014eff8f0c9a49ecb147dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2087FC,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":147},
                "size":{
                  "width":39,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b22a95a80fda44d3a1fe0a3428fbd306",
          "label":"paragraph",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2087FC,
              "opacity":1},
            "location":{
              "x":293,
              "y":147},
            "size":{
              "width":47,
              "height":16},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ceb1e4c306254b379de29cd525bfea83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2087FC,
                  "opacity":1},
                "location":{
                  "x":293,
                  "y":147},
                "size":{
                  "width":47,
                  "height":16},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8ff49c860b5c48389913cd4f1fe61184",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "location":{
              "x":44,
              "y":225},
            "size":{
              "width":116,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a65984654c748b4803d2a76b176cb61",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "location":{
                  "x":44,
                  "y":225},
                "size":{
                  "width":116,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7ec8cc0248304a499888258ad9acb3cd",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"200",
            "location":{
              "x":250,
              "y":225},
            "size":{
              "width":97,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"142502a9dbec4c67a4abf510073c6965",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"200",
                "location":{
                  "x":250,
                  "y":225},
                "size":{
                  "width":97,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5cb96dace1b84523b17c9fca4140baa2",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"200",
            "location":{
              "x":44,
              "y":260},
            "size":{
              "width":116,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fba7433c39e54a579de434dfad80e284",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"200",
                "location":{
                  "x":44,
                  "y":260},
                "size":{
                  "width":116,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"08358b7b3f6d4b70aeb62f94ab6a0bc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"200",
            "location":{
              "x":250,
              "y":260},
            "size":{
              "width":90,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce431ba958c74fe2a1faf15813e2058d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"200",
                "location":{
                  "x":250,
                  "y":260},
                "size":{
                  "width":90,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1d57cda349684ef78b94736295f5d48e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"200",
            "location":{
              "x":44,
              "y":298},
            "size":{
              "width":136,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"db818643871c4619b0f408275d5b4ef8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"200",
                "location":{
                  "x":44,
                  "y":298},
                "size":{
                  "width":136,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6d18c193b4b745a99aca305a66bb6293",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"200",
            "location":{
              "x":237,
              "y":298},
            "size":{
              "width":103,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ba13434879c44b7d93d3e581d3d155c8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"200",
                "location":{
                  "x":237,
                  "y":298},
                "size":{
                  "width":103,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e337c9d70b164ea0a5c39f1e647bd7c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"48px",
            "fontWeight":"200",
            "location":{
              "x":120,
              "y":360},
            "size":{
              "width":227,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a301df9abc3e4a2383b604fea48ecdd1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"48px",
                "fontWeight":"200",
                "location":{
                  "x":120,
                  "y":360},
                "size":{
                  "width":227,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bf4dc15557d949c886bde380d9e332e0",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":44,
              "y":189},
            "size":{
              "width":136,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e663be005b00454f9e7b2a9f22138d43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":44,
                  "y":189},
                "size":{
                  "width":136,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"92b1616c42b24fdba974a9c9cbc8102c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":206},
            "size":{
              "width":296,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/支付页面/u30_line.png"}},
{
          "id":"1fa49d6074904aabae8a52af09ad8b93",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"200",
            "location":{
              "x":44,
              "y":332},
            "size":{
              "width":136,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a19e59721794ba5bb08f9d705f31c15",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"200",
                "location":{
                  "x":44,
                  "y":332},
                "size":{
                  "width":136,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7d355e231fc4e62a7f7c7d9eb98a8c1",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":450},
            "size":{
              "width":296,
              "height":10},
            "linePattern":"dashed"},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/支付页面/u30_line.png"}},
{
          "id":"5782bfbbaca943eb80ee1520e470197b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"200",
            "location":{
              "x":44,
              "y":430},
            "size":{
              "width":136,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"afd17af0ddbe4316847379d756ee5cc9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"200",
                "location":{
                  "x":44,
                  "y":430},
                "size":{
                  "width":136,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"204986ca338e42f2bd0467dcf684dfed",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":44,
              "y":470},
            "size":{
              "width":296,
              "height":50},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3973e38aeaab40808b704094275968fb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":44,
                  "y":470},
                "size":{
                  "width":296,
                  "height":50},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付页面/u36.png"}},
{
          "id":"03588912c0bf45b4aa59f0ad48042d3d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":61,
              "y":487},
            "size":{
              "width":136,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5d518c9d0ffd4099ba121a56c4db0be4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":61,
                  "y":487},
                "size":{
                  "width":136,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"39ea35d7fe8149f18e28f34dbad43b7a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"18px",
            "fontWeight":"200",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF,
              "opacity":1},
            "fill":{
              "fillType":"linearGradient",
              "colors":[{
                  "color":0xFF0099CC},
{
                  "color":0xFF0099CC},
{
                  "color":0xFF00CCFF},
{
                  "color":0xFF00CCFF}]},
            "location":{
              "x":44,
              "y":550},
            "size":{
              "width":296,
              "height":50},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"90e80095bdc14e78b233543b04a82de0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"18px",
                "fontWeight":"200",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF,
                  "opacity":1},
                "fill":{
                  "fillType":"linearGradient",
                  "colors":[{
                      "color":0xFF0099CC},
{
                      "color":0xFF0099CC},
{
                      "color":0xFF00CCFF},
{
                      "color":0xFF00CCFF}]},
                "location":{
                  "x":44,
                  "y":550},
                "size":{
                  "width":296,
                  "height":50},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/支付页面/u40.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "a8c27754e13241d697415cc749e8a4a8":{
      "scriptId":"u0"},
    "611d1a99833a4c24a39f839a9575d3e5":{
      "scriptId":"u1"},
    "e15b51cdc84e475b86d00dede27d992b":{
      "scriptId":"u2"},
    "8ac42668389b448ea34f951bfa605a69":{
      "scriptId":"u3"},
    "4822bca34832412c851e36bbd161b638":{
      "scriptId":"u4"},
    "5a2a684398c8498bb4d675f9eed7eaa6":{
      "scriptId":"u5"},
    "36184846065f48d8a5ebcf6d6cdba857":{
      "scriptId":"u6"},
    "4d69d91bdbe84f42a964455928b43e3e":{
      "scriptId":"u7"},
    "610d8c1e45ab4119a16a4a3474c74a92":{
      "scriptId":"u8"},
    "401683f743e1449e92ca9175ebf56e20":{
      "scriptId":"u9"},
    "52d28b3c1ade4631ac51a6ccff2adf51":{
      "scriptId":"u10"},
    "5c5071a7ff014eff8f0c9a49ecb147dd":{
      "scriptId":"u11"},
    "b22a95a80fda44d3a1fe0a3428fbd306":{
      "scriptId":"u12"},
    "ceb1e4c306254b379de29cd525bfea83":{
      "scriptId":"u13"},
    "8ff49c860b5c48389913cd4f1fe61184":{
      "scriptId":"u14"},
    "8a65984654c748b4803d2a76b176cb61":{
      "scriptId":"u15"},
    "7ec8cc0248304a499888258ad9acb3cd":{
      "scriptId":"u16"},
    "142502a9dbec4c67a4abf510073c6965":{
      "scriptId":"u17"},
    "5cb96dace1b84523b17c9fca4140baa2":{
      "scriptId":"u18"},
    "fba7433c39e54a579de434dfad80e284":{
      "scriptId":"u19"},
    "08358b7b3f6d4b70aeb62f94ab6a0bc8":{
      "scriptId":"u20"},
    "ce431ba958c74fe2a1faf15813e2058d":{
      "scriptId":"u21"},
    "1d57cda349684ef78b94736295f5d48e":{
      "scriptId":"u22"},
    "db818643871c4619b0f408275d5b4ef8":{
      "scriptId":"u23"},
    "6d18c193b4b745a99aca305a66bb6293":{
      "scriptId":"u24"},
    "ba13434879c44b7d93d3e581d3d155c8":{
      "scriptId":"u25"},
    "e337c9d70b164ea0a5c39f1e647bd7c6":{
      "scriptId":"u26"},
    "a301df9abc3e4a2383b604fea48ecdd1":{
      "scriptId":"u27"},
    "bf4dc15557d949c886bde380d9e332e0":{
      "scriptId":"u28"},
    "e663be005b00454f9e7b2a9f22138d43":{
      "scriptId":"u29"},
    "92b1616c42b24fdba974a9c9cbc8102c":{
      "scriptId":"u30"},
    "1fa49d6074904aabae8a52af09ad8b93":{
      "scriptId":"u31"},
    "8a19e59721794ba5bb08f9d705f31c15":{
      "scriptId":"u32"},
    "a7d355e231fc4e62a7f7c7d9eb98a8c1":{
      "scriptId":"u33"},
    "5782bfbbaca943eb80ee1520e470197b":{
      "scriptId":"u34"},
    "afd17af0ddbe4316847379d756ee5cc9":{
      "scriptId":"u35"},
    "204986ca338e42f2bd0467dcf684dfed":{
      "scriptId":"u36"},
    "3973e38aeaab40808b704094275968fb":{
      "scriptId":"u37"},
    "03588912c0bf45b4aa59f0ad48042d3d":{
      "scriptId":"u38"},
    "5d518c9d0ffd4099ba121a56c4db0be4":{
      "scriptId":"u39"},
    "39ea35d7fe8149f18e28f34dbad43b7a":{
      "scriptId":"u40"},
    "90e80095bdc14e78b233543b04a82de0":{
      "scriptId":"u41"}}});