$axure.loadCurrentPage({
  "url":"面额选择.html",
  "generationDate":new Date(1397786910360.28),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"55d5452ae0394dc185f2b3fe6953d082",
    "type":"Axure:Page",
    "name":"面额选择",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"555bf13abcd74eca9fe9c32ed8d2ce5a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":30},
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb051af2a0c344c2abd56495ee42b7b2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":30},
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机充值首页/u0.png"}},
{
          "id":"3085b95a820d48e2a9fdcd4a1e26a87f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":36,
              "y":150},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6f7037649eff4c9cbea914ac16c19db2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":36,
                  "y":150},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机充值首页/u2.png"}},
{
          "id":"4eabedc066a746cea4881a872a55ca08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":173},
            "size":{
              "width":200,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c190d255e5504e1d8b602104b4d6270d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":173},
                "size":{
                  "width":200,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机充值首页/u4.png"}},
{
          "id":"528d6d61d89b4017b531b53a17edeea5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":250},
            "size":{
              "width":269,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09056e6bc0df44198121166201e90ca5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":250},
                "size":{
                  "width":269,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机充值首页/u6.png"}},
{
          "id":"d8ae40f4dc6d4c688d812b19a4871b83",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"16px",
            "fontWeight":"400",
            "location":{
              "x":69,
              "y":312},
            "size":{
              "width":65,
              "height":19}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fcd310ab836a4d66b71e1a59fa66cc0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"16px",
                "fontWeight":"400",
                "location":{
                  "x":69,
                  "y":312},
                "size":{
                  "width":65,
                  "height":19}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c943e5005fc40eabfa43fc8b052ce25",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":61,
              "y":350},
            "size":{
              "width":269,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a04d1be7073f424480829eeaf1b5069a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":61,
                  "y":350},
                "size":{
                  "width":269,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机充值首页/u6.png"}},
{
          "id":"6d33978837f346f095bb6b71d203b6dc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":365},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"af7b570cf3d6420abcb94338b3b7a44d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":365},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机充值首页/u12.png"}},
{
          "id":"007e77fcbc2f4c7282f48a19136465a2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":262},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"77fc3f908de24208838dabb49453a296",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":262},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手机充值首页/u14.png"}},
{
          "id":"56b910e415a84581a3bc23f51389010d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":130,
              "y":440},
            "size":{
              "width":130,
              "height":40}},
          "adaptiveStyles":{
}},
{
          "id":"80913300f7bc4b069d8701e6c08d69d3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":163},
            "size":{
              "width":200,
              "height":478}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0a6bdeeaa0648a2a483e983653450fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":163},
                "size":{
                  "width":200,
                  "height":478}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/面额选择/u17.png"}},
{
          "id":"e00db2842d4943559dcf0de6141b5463",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF1E1E1E,
              "opacity":1},
            "location":{
              "x":100,
              "y":212},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f2f9b237165840068c0244ab4b244c84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF1E1E1E,
                  "opacity":1},
                "location":{
                  "x":100,
                  "y":212},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/面额选择/u19.png"}},
{
          "id":"9ba57e12cb1047d181bf2d35217fa50b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":252},
            "size":{
              "width":200,
              "height":38}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ade57563ffa74b37ab6b8b30e86b507f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":252},
                "size":{
                  "width":200,
                  "height":38}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/面额选择/u21.png"}},
{
          "id":"2c2f100f0fe34ed289bffeed988aec79",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":290},
            "size":{
              "width":200,
              "height":41}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec403b965483452da66f383f0e62a993",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":290},
                "size":{
                  "width":200,
                  "height":41}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/面额选择/u23.png"}},
{
          "id":"3640e0025337460091999a736bde7560",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFFF0000,
              "opacity":1},
            "location":{
              "x":100,
              "y":331},
            "size":{
              "width":200,
              "height":39}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c676c6e1aed34a2b8707fb19f6d93413",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFFFF0000,
                  "opacity":1},
                "location":{
                  "x":100,
                  "y":331},
                "size":{
                  "width":200,
                  "height":39}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 手机充值首页 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"手机充值首页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/面额选择/u25.png"}},
{
          "id":"48d11b62190c45bb8a876670b35e96c3",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":370},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6713ff24892d4380a8061406636619b0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":370},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/面额选择/u19.png"}},
{
          "id":"1d6a05f49f894f2eab1312a48af718d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":410},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"baa56a82b06945d68db0e701c8a3c78c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":410},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/面额选择/u19.png"}},
{
          "id":"da7bd885726b441f8271d2d9b37f9ae0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":450},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca108b3fad4f4d68b08d3d4cf0a9f7e2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":450},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/面额选择/u19.png"}},
{
          "id":"d47c2c2053c8400798a3a2bfd018a981",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":100,
              "y":490},
            "size":{
              "width":200,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3b78d3d995fa4d06b6ca161cac423ed2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":100,
                  "y":490},
                "size":{
                  "width":200,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/面额选择/u19.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "555bf13abcd74eca9fe9c32ed8d2ce5a":{
      "scriptId":"u0"},
    "bb051af2a0c344c2abd56495ee42b7b2":{
      "scriptId":"u1"},
    "3085b95a820d48e2a9fdcd4a1e26a87f":{
      "scriptId":"u2"},
    "6f7037649eff4c9cbea914ac16c19db2":{
      "scriptId":"u3"},
    "4eabedc066a746cea4881a872a55ca08":{
      "scriptId":"u4"},
    "c190d255e5504e1d8b602104b4d6270d":{
      "scriptId":"u5"},
    "528d6d61d89b4017b531b53a17edeea5":{
      "scriptId":"u6"},
    "09056e6bc0df44198121166201e90ca5":{
      "scriptId":"u7"},
    "d8ae40f4dc6d4c688d812b19a4871b83":{
      "scriptId":"u8"},
    "fcd310ab836a4d66b71e1a59fa66cc0f":{
      "scriptId":"u9"},
    "4c943e5005fc40eabfa43fc8b052ce25":{
      "scriptId":"u10"},
    "a04d1be7073f424480829eeaf1b5069a":{
      "scriptId":"u11"},
    "6d33978837f346f095bb6b71d203b6dc":{
      "scriptId":"u12"},
    "af7b570cf3d6420abcb94338b3b7a44d":{
      "scriptId":"u13"},
    "007e77fcbc2f4c7282f48a19136465a2":{
      "scriptId":"u14"},
    "77fc3f908de24208838dabb49453a296":{
      "scriptId":"u15"},
    "56b910e415a84581a3bc23f51389010d":{
      "scriptId":"u16"},
    "80913300f7bc4b069d8701e6c08d69d3":{
      "scriptId":"u17"},
    "c0a6bdeeaa0648a2a483e983653450fa":{
      "scriptId":"u18"},
    "e00db2842d4943559dcf0de6141b5463":{
      "scriptId":"u19"},
    "f2f9b237165840068c0244ab4b244c84":{
      "scriptId":"u20"},
    "9ba57e12cb1047d181bf2d35217fa50b":{
      "scriptId":"u21"},
    "ade57563ffa74b37ab6b8b30e86b507f":{
      "scriptId":"u22"},
    "2c2f100f0fe34ed289bffeed988aec79":{
      "scriptId":"u23"},
    "ec403b965483452da66f383f0e62a993":{
      "scriptId":"u24"},
    "3640e0025337460091999a736bde7560":{
      "scriptId":"u25"},
    "c676c6e1aed34a2b8707fb19f6d93413":{
      "scriptId":"u26"},
    "48d11b62190c45bb8a876670b35e96c3":{
      "scriptId":"u27"},
    "6713ff24892d4380a8061406636619b0":{
      "scriptId":"u28"},
    "1d6a05f49f894f2eab1312a48af718d6":{
      "scriptId":"u29"},
    "baa56a82b06945d68db0e701c8a3c78c":{
      "scriptId":"u30"},
    "da7bd885726b441f8271d2d9b37f9ae0":{
      "scriptId":"u31"},
    "ca108b3fad4f4d68b08d3d4cf0a9f7e2":{
      "scriptId":"u32"},
    "d47c2c2053c8400798a3a2bfd018a981":{
      "scriptId":"u33"},
    "3b78d3d995fa4d06b6ca161cac423ed2":{
      "scriptId":"u34"}}});