$axure.loadCurrentPage({
  "url":"q币充值.html",
  "generationDate":new Date(1409800780875),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"6de196a7b43b4980838e85b38682268a",
    "type":"Axure:Page",
    "name":"Q币充值",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"53f72e189ef54b5db3abca979828b220",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":26},
            "size":{
              "width":380,
              "height":664},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c9bb1ac908f34935b9aed91ae660e52a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":26},
                "size":{
                  "width":380,
                  "height":664},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息设置/u0.png"}},
{
          "id":"5be52423d4084a6394a98e8eb56d2dd3",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":51,
              "y":178},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a979eb88535042b99e3cb361f4468d73",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":51,
                  "y":178},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息设置/u2.png"}},
{
          "id":"1139f4df14c54b70b25944ee0952ff45",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":163},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00377660eef44703a2f7186cf0a9279e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":163},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息设置/u4.png"}},
{
          "id":"d5d9ba8e72254ba8af4867d3067fa229",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":142,
              "y":179},
            "size":{
              "width":168,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1a7cbec307f4e0caf01f28781bfa0e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":142,
                  "y":179},
                "size":{
                  "width":168,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2e83559f888f49319f110819db8ae27c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":151,
              "y":410},
            "size":{
              "width":90,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4b37d3f22154f0fa3edf40637ae2c0f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":151,
                  "y":410},
                "size":{
                  "width":90,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 充值订单（默认支付）",
                      "target":{
                        "targetType":"page",
                        "url":"充值订单（默认支付）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/话费充值/u8.png"}},
{
          "id":"b11c3eb19619470abe1aca9aac2de29e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":270},
            "size":{
              "width":260,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c6fc55256046405691b60f9c24f0f286",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":270},
                "size":{
                  "width":260,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息设置/u8.png"}},
{
          "id":"c424c1dfab3342f6aea08fc0fba8d0a1",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":280,
              "y":186},
            "size":{
              "width":80,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ea19617dba64b8dbb7daada85914a65",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":280,
                  "y":186},
                "size":{
                  "width":80,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/q币充值/u12.png"}},
{
          "id":"7b2b671ca04a49d0946fa2d095de0095",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":336},
            "size":{
              "width":260,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d337bdcbd7f5424e886a408d61556849",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":336},
                "size":{
                  "width":260,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息设置/u8.png"}},
{
          "id":"83c750e69a164a7e80917a2c2fdda38c",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":80,
              "y":310},
            "size":{
              "width":260,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"936e08f6b976493590d2b6cc5b7dad7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":80,
                  "y":310},
                "size":{
                  "width":260,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a83bb13c9ba9493a810989e90198bd8d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":80,
              "y":244},
            "size":{
              "width":220,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5d907aaa29a4aefb02e58448f3c1df2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":80,
                  "y":244},
                "size":{
                  "width":220,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "53f72e189ef54b5db3abca979828b220":{
      "scriptId":"u0"},
    "c9bb1ac908f34935b9aed91ae660e52a":{
      "scriptId":"u1"},
    "5be52423d4084a6394a98e8eb56d2dd3":{
      "scriptId":"u2"},
    "a979eb88535042b99e3cb361f4468d73":{
      "scriptId":"u3"},
    "1139f4df14c54b70b25944ee0952ff45":{
      "scriptId":"u4"},
    "00377660eef44703a2f7186cf0a9279e":{
      "scriptId":"u5"},
    "d5d9ba8e72254ba8af4867d3067fa229":{
      "scriptId":"u6"},
    "e1a7cbec307f4e0caf01f28781bfa0e1":{
      "scriptId":"u7"},
    "2e83559f888f49319f110819db8ae27c":{
      "scriptId":"u8"},
    "e4b37d3f22154f0fa3edf40637ae2c0f":{
      "scriptId":"u9"},
    "b11c3eb19619470abe1aca9aac2de29e":{
      "scriptId":"u10"},
    "c6fc55256046405691b60f9c24f0f286":{
      "scriptId":"u11"},
    "c424c1dfab3342f6aea08fc0fba8d0a1":{
      "scriptId":"u12"},
    "5ea19617dba64b8dbb7daada85914a65":{
      "scriptId":"u13"},
    "7b2b671ca04a49d0946fa2d095de0095":{
      "scriptId":"u14"},
    "d337bdcbd7f5424e886a408d61556849":{
      "scriptId":"u15"},
    "83c750e69a164a7e80917a2c2fdda38c":{
      "scriptId":"u16"},
    "936e08f6b976493590d2b6cc5b7dad7e":{
      "scriptId":"u17"},
    "a83bb13c9ba9493a810989e90198bd8d":{
      "scriptId":"u18"},
    "f5d907aaa29a4aefb02e58448f3c1df2":{
      "scriptId":"u19"}}});