$axure.loadCurrentPage({
  "url":"2、充值订单（信用卡-易宝）.html",
  "generationDate":new Date(1407924518296.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b72f5a4b737a4eefaa80f718195e7eaf",
    "type":"Axure:Page",
    "name":"2、充值订单（信用卡-易宝）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"719441878df54e40b6cce14fbce3048e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":26},
            "size":{
              "width":380,
              "height":704},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"353459d45e384035a5bb9cbb518c7b12",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":26},
                "size":{
                  "width":380,
                  "height":704},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/话费充值/u0.png"}},
{
          "id":"411a321f3fc34d6abc4c53a332b60bf8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":51,
              "y":178},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a056c43a151e43cbba86a2f3e15a5ac2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":51,
                  "y":178},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/话费充值/u2.png"}},
{
          "id":"a894a90689ec4992bc323e290a94548d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":163},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a7bb245fd144d99898c2c43e394e726",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":163},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/话费充值/u4.png"}},
{
          "id":"c852433f9eb442fbb00640c7a66d9d26",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":110,
              "y":182},
            "size":{
              "width":208,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d96776746bbb4e56abcc4d6523e38e69",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":110,
                  "y":182},
                "size":{
                  "width":208,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"28daaea2b489458c8691caad7519a67b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":160,
              "y":560},
            "size":{
              "width":90,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5aad7297915648ca81c70bac5f65f30f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":160,
                  "y":560},
                "size":{
                  "width":90,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 信用卡支付（易宝）",
                      "target":{
                        "targetType":"page",
                        "url":"信用卡支付（易宝）_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/话费充值/u8.png"}},
{
          "id":"76f04aa783d14bd0b86fc4ce5e1dc4dc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":280},
            "size":{
              "width":260,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"319017aea6314a3db6efc52c26a43945",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":280},
                "size":{
                  "width":260,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/话费充值/u10.png"}},
{
          "id":"165ef572ea59418c8572995f42247eab",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":250},
            "size":{
              "width":260,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11bec324f73f443fa6e1dd971a527d10",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":250},
                "size":{
                  "width":260,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/话费充值/u10.png"}},
{
          "id":"1420139d476a45e59f98e52e59587991",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":310},
            "size":{
              "width":260,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d9e3df484f54440b863b3dda03cd42a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":310},
                "size":{
                  "width":260,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/话费充值/u10.png"}},
{
          "id":"e4656eb6303a4b12b5cd7a2e96b1149b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":360},
            "size":{
              "width":260,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae0610b8c1b2493c83d668c99606624c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":360},
                "size":{
                  "width":260,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1、充值订单（默认支付）/u16.png"}},
{
          "id":"3eb21acb3f43491285fd5ea9c5f1b249",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":80,
              "y":390},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"66b0ec16dffd47a6959fb5f0c834de7e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":80,
                  "y":390},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"89adad03e1a34ef48dda0825829b86dd",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":80,
              "y":444},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce8cd90aebec488487ed2c02f35c6d22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":80,
                  "y":444},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"2cd9bc3d741949108714503401993453",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":198,
              "y":442},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5926cf4d5cbb4060940893e47df6cda4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":198,
                  "y":442},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的银行卡",
                      "target":{
                        "targetType":"page",
                        "url":"我的银行卡_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/1、选择支付（默认支付）/u12.png"}},
{
          "id":"d9d5129a84694bcb9ecd718365c408e7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":450,
              "y":343},
            "size":{
              "width":230,
              "height":158}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0e87d474e424e8b94ea8dbfed636ac8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":450,
                  "y":343},
                "size":{
                  "width":230,
                  "height":158}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/2、选择支付（信用卡-易宝）/u18.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "719441878df54e40b6cce14fbce3048e":{
      "scriptId":"u0"},
    "353459d45e384035a5bb9cbb518c7b12":{
      "scriptId":"u1"},
    "411a321f3fc34d6abc4c53a332b60bf8":{
      "scriptId":"u2"},
    "a056c43a151e43cbba86a2f3e15a5ac2":{
      "scriptId":"u3"},
    "a894a90689ec4992bc323e290a94548d":{
      "scriptId":"u4"},
    "9a7bb245fd144d99898c2c43e394e726":{
      "scriptId":"u5"},
    "c852433f9eb442fbb00640c7a66d9d26":{
      "scriptId":"u6"},
    "d96776746bbb4e56abcc4d6523e38e69":{
      "scriptId":"u7"},
    "28daaea2b489458c8691caad7519a67b":{
      "scriptId":"u8"},
    "5aad7297915648ca81c70bac5f65f30f":{
      "scriptId":"u9"},
    "76f04aa783d14bd0b86fc4ce5e1dc4dc":{
      "scriptId":"u10"},
    "319017aea6314a3db6efc52c26a43945":{
      "scriptId":"u11"},
    "165ef572ea59418c8572995f42247eab":{
      "scriptId":"u12"},
    "11bec324f73f443fa6e1dd971a527d10":{
      "scriptId":"u13"},
    "1420139d476a45e59f98e52e59587991":{
      "scriptId":"u14"},
    "7d9e3df484f54440b863b3dda03cd42a":{
      "scriptId":"u15"},
    "e4656eb6303a4b12b5cd7a2e96b1149b":{
      "scriptId":"u16"},
    "ae0610b8c1b2493c83d668c99606624c":{
      "scriptId":"u17"},
    "3eb21acb3f43491285fd5ea9c5f1b249":{
      "scriptId":"u18"},
    "66b0ec16dffd47a6959fb5f0c834de7e":{
      "scriptId":"u19"},
    "89adad03e1a34ef48dda0825829b86dd":{
      "scriptId":"u20"},
    "ce8cd90aebec488487ed2c02f35c6d22":{
      "scriptId":"u21"},
    "2cd9bc3d741949108714503401993453":{
      "scriptId":"u22"},
    "5926cf4d5cbb4060940893e47df6cda4":{
      "scriptId":"u23"},
    "d9d5129a84694bcb9ecd718365c408e7":{
      "scriptId":"u24"},
    "c0e87d474e424e8b94ea8dbfed636ac8":{
      "scriptId":"u25"}}});