$axure.loadCurrentPage({
  "url":"充值成功.html",
  "generationDate":new Date(1407924517093.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"606b38d6b8a7409692ef88b021481c00",
    "type":"Axure:Page",
    "name":"充值成功",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"5ff5aad2ceb5459baa42dec2b1b7ce8a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":26},
            "size":{
              "width":380,
              "height":744},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c5b66eb78b4c47f2bfe47d8c37ed4b23",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":26},
                "size":{
                  "width":380,
                  "height":744},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/话费充值/u0.png"}},
{
          "id":"c523968678424b47b533514dd789b29d",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":51,
              "y":178},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01974e333c15408c9b50c7b3c29c4a0c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":51,
                  "y":178},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/话费充值/u2.png"}},
{
          "id":"a89a316d4f384a048cfaa692a7ec80b7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":163},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d63c00207f294a19aad40a5503f0a98d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":163},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/话费充值/u4.png"}},
{
          "id":"5ccb37b93dc2400886c925c5fef8f55c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "location":{
              "x":62,
              "y":234},
            "size":{
              "width":298,
              "height":306}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"000ecac1ba324d9c91ccad08033cca9f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "location":{
                  "x":62,
                  "y":234},
                "size":{
                  "width":298,
                  "height":306}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1、选择支付（默认支付）/u6.png"}},
{
          "id":"2295799fd9124a80ac509aed077a0f86",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":150,
              "y":182},
            "size":{
              "width":168,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b94abeee91ee4cd99bb31dfb2bde1bde",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":150,
                  "y":182},
                "size":{
                  "width":168,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"98f8df10aefa424a8ea653eb7e083ce4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":165,
              "y":570},
            "size":{
              "width":90,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f20ed5e6cdf24fb19b7619ed7f103647",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":165,
                  "y":570},
                "size":{
                  "width":90,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 话费充值",
                      "target":{
                        "targetType":"page",
                        "url":"话费充值.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/话费充值/u8.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "5ff5aad2ceb5459baa42dec2b1b7ce8a":{
      "scriptId":"u0"},
    "c5b66eb78b4c47f2bfe47d8c37ed4b23":{
      "scriptId":"u1"},
    "c523968678424b47b533514dd789b29d":{
      "scriptId":"u2"},
    "01974e333c15408c9b50c7b3c29c4a0c":{
      "scriptId":"u3"},
    "a89a316d4f384a048cfaa692a7ec80b7":{
      "scriptId":"u4"},
    "d63c00207f294a19aad40a5503f0a98d":{
      "scriptId":"u5"},
    "5ccb37b93dc2400886c925c5fef8f55c":{
      "scriptId":"u6"},
    "000ecac1ba324d9c91ccad08033cca9f":{
      "scriptId":"u7"},
    "2295799fd9124a80ac509aed077a0f86":{
      "scriptId":"u8"},
    "b94abeee91ee4cd99bb31dfb2bde1bde":{
      "scriptId":"u9"},
    "98f8df10aefa424a8ea653eb7e083ce4":{
      "scriptId":"u10"},
    "f20ed5e6cdf24fb19b7619ed7f103647":{
      "scriptId":"u11"}}});