$axure.loadCurrentPage({
  "url":"确认收款（汇通宝）.html",
  "generationDate":new Date(1409653596718.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"cb4c5184ba30438d93b6d36b1d6c1419",
    "type":"Axure:Page",
    "name":"确认收款（汇通宝）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"e8fa4cc168864a8a9258508c85da02dc",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":26},
            "size":{
              "width":380,
              "height":704},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f8886b420faa43aba4174ae4351c64cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":26},
                "size":{
                  "width":380,
                  "height":704},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户收款/u0.png"}},
{
          "id":"6efdd3b655cf4d3d9c3f4a58905bdd4e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":51,
              "y":178},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d04339aae1c64bbf8f3bebb9756dce0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":51,
                  "y":178},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户收款/u2.png"}},
{
          "id":"e0f59a5f74e84889aa17d0b803e4d1de",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":163},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f37bd92451bd489397889d237af6e7d2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":163},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户收款/u4.png"}},
{
          "id":"ccf9fef36982486ca66326c9eb5c8870",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":150,
              "y":182},
            "size":{
              "width":168,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82da85c680c0444cb082c29d7a7e4994",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":150,
                  "y":182},
                "size":{
                  "width":168,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fde77a71b81340fd9f26a6105837c073",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":165,
              "y":550},
            "size":{
              "width":90,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eafd1684a3694edc8240c7006b211f4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":165,
                  "y":550},
                "size":{
                  "width":90,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 收款成功",
                      "target":{
                        "targetType":"page",
                        "url":"收款成功.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/商户收款/u8.png"}},
{
          "id":"b0fe173fe34b4cfb949f88ea0d0c9ab0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":280},
            "size":{
              "width":260,
              "height":230}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e23c336904424fdd9b9c419743e924cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":280},
                "size":{
                  "width":260,
                  "height":230}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/确认收款（汇通宝）/u10.png"}},
{
          "id":"c58f6720ba0b423f88b00e57abd7988a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":240},
            "size":{
              "width":260,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6c8ed6ea23a43a298ad3977be68c5d4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":240},
                "size":{
                  "width":260,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/商户收款/u10.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "e8fa4cc168864a8a9258508c85da02dc":{
      "scriptId":"u0"},
    "f8886b420faa43aba4174ae4351c64cc":{
      "scriptId":"u1"},
    "6efdd3b655cf4d3d9c3f4a58905bdd4e":{
      "scriptId":"u2"},
    "d04339aae1c64bbf8f3bebb9756dce0a":{
      "scriptId":"u3"},
    "e0f59a5f74e84889aa17d0b803e4d1de":{
      "scriptId":"u4"},
    "f37bd92451bd489397889d237af6e7d2":{
      "scriptId":"u5"},
    "ccf9fef36982486ca66326c9eb5c8870":{
      "scriptId":"u6"},
    "82da85c680c0444cb082c29d7a7e4994":{
      "scriptId":"u7"},
    "fde77a71b81340fd9f26a6105837c073":{
      "scriptId":"u8"},
    "eafd1684a3694edc8240c7006b211f4b":{
      "scriptId":"u9"},
    "b0fe173fe34b4cfb949f88ea0d0c9ab0":{
      "scriptId":"u10"},
    "e23c336904424fdd9b9c419743e924cb":{
      "scriptId":"u11"},
    "c58f6720ba0b423f88b00e57abd7988a":{
      "scriptId":"u12"},
    "d6c8ed6ea23a43a298ad3977be68c5d4":{
      "scriptId":"u13"}}});