$axure.loadCurrentPage({
  "url":"二次查询页面.html",
  "generationDate":new Date(1416378073546.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"rl_date",
"rl_day"],
  "page":{
    "packageId":"ca7e4af108a349fc937e2470179ee421",
    "type":"Axure:Page",
    "name":"二次查询页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"52b71416b79748cc91a5b0e497b04127",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":116},
            "size":{
              "width":8,
              "height":36},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e22a70495fd24d84abb85208efd7d1c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":116},
                "size":{
                  "width":8,
                  "height":36},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u0.png"}},
{
          "id":"b231891741ad47ffb5d5dc0fcd598469",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":192},
            "size":{
              "width":8,
              "height":27},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3211ee1c1e0f4b4ebebba8f7387940b6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":192},
                "size":{
                  "width":8,
                  "height":27},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u2.png"}},
{
          "id":"b8dd29d9dffd4ec897c4a4403715b3ff",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":255},
            "size":{
              "width":8,
              "height":27},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a4634bfd2c8b4995b7ea140a240d3221",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":255},
                "size":{
                  "width":8,
                  "height":27},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u2.png"}},
{
          "id":"fb1a06f7a73045d98ad44be9bba75b13",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":0},
            "size":{
              "width":60,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"09242bfda75c4a7cb436defee450d724",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":259,
                  "y":0},
                "size":{
                  "width":60,
                  "height":10},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u6.png"}},
{
          "id":"120f4810b4b7424ea20048464c27f133",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":6},
            "size":{
              "width":372,
              "height":796},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"52"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2474e13bc27e48cc8cb32c8c872be2bf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":6},
                "size":{
                  "width":372,
                  "height":796},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"52"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u8.png"}},
{
          "id":"d076d8a10c364c179f3f6fcab756dd98",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":32,
              "y":120},
            "size":{
              "width":320,
              "height":568},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83bb6635b6424e4b8b755569e2d30c7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":32,
                  "y":120},
                "size":{
                  "width":320,
                  "height":568},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店预订/u10.png"}},
{
          "id":"87602adeb9ab4b81a98f587ae0c361ae",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":157,
              "y":66},
            "size":{
              "width":70,
              "height":14},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"35"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37d4b7c0ce9146e3a11e22b0e7e5c374",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":157,
                  "y":66},
                "size":{
                  "width":70,
                  "height":14},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"35"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店预订/u12.png"}},
{
          "id":"6161cc2a1cdf44898e3bd96822e3617d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":185,
              "y":40},
            "size":{
              "width":14,
              "height":14},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"35"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d439168fef54699917dec0083e9b664",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":185,
                  "y":40},
                "size":{
                  "width":14,
                  "height":14},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"35"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店预订/u14.png"}},
{
          "id":"e428eb6e778743fa98e2716c049e2e08",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":156,
              "y":704},
            "size":{
              "width":72,
              "height":72},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"35"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ecbfc1d6e4064a3bb6051e01818ffcfb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":156,
                  "y":704},
                "size":{
                  "width":72,
                  "height":72},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"35"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店预订/u16.png"}},
{
          "id":"b4dc02637754409a9cf7a6f109788e41",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":44,
              "y":347},
            "size":{
              "width":288,
              "height":44}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 酒店列表页面",
                      "target":{
                        "targetType":"page",
                        "url":"酒店列表页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"4b828f122b6e46f59c74bf66ef655529",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":249},
            "size":{
              "width":288,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/酒店预订/u21_line.png"}},
{
          "id":"91ab1f09db5f402cb381e53b3f99a62e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":49,
              "y":226},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f0289f69169d498c92c77e14bea7179d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":49,
                  "y":226},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9b84a255be194c9780328f698fc23175",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":210},
            "size":{
              "width":288,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/酒店预订/u21_line.png"}},
{
          "id":"1ee5fd557ef640308df96505fb3d2665",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":327},
            "size":{
              "width":288,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/酒店预订/u21_line.png"}},
{
          "id":"6cfc34a0aac542e98dad3e92377b4d0e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":223},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1b5a6c2c12b94222924cc0a5cad75317",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":315,
                  "y":223},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店预订/u24.png"}},
{
          "id":"2dbc75212f164ffd893bd3b1f8b7bdd7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":49,
              "y":265},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d3f5e478822744579abab3e8a33c5db3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":49,
                  "y":265},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6c300d6aa0ee421f9f277890a01db0db",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":316,
              "y":262},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"17e972d8bbbc4f018158f393dc52ba47",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":316,
                  "y":262},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店预订/u24.png"}},
{
          "id":"677d2d7c809140529a7e355869bb5462",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":49,
              "y":306},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"285bf54334b74db08c3ed7f0f3f2f2a7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":49,
                  "y":306},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e58bf2aa0439413480d69d4e03c7b1b9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":316,
              "y":303},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"615c761eb8cc4ea7b6c64b58c25bc5dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":316,
                  "y":303},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店预订/u24.png"}},
{
          "id":"cdde7adc46f7484ca1c27f8117009824",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"700",
            "location":{
              "x":49,
              "y":184},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"136301e1664549bfb8849e98fbf18e5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"700",
                "location":{
                  "x":49,
                  "y":184},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1914546f82754d3bb4538abadddc24a7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":315,
              "y":181},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bb1bd84a3fa94677935b8a4e3d8cee58",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":315,
                  "y":181},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店预订/u24.png"}},
{
          "id":"fc8ecad6dc70485ea473300beda589d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":164,
              "y":180},
            "size":{
              "width":151,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2705cf8ae0f44c06b76c1dddcfff1735",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":164,
                  "y":180},
                "size":{
                  "width":151,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"450b550fb74c49d0934d3ea90dc5b297",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":46,
              "y":288},
            "size":{
              "width":288,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/酒店预订/u21_line.png"}},
{
          "id":"e49027d45b064e77b5defa2c31077b36",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":124},
            "size":{
              "width":318,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7be285011e844304855310702ee895d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":124},
                "size":{
                  "width":318,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店预订/u42.png"}},
{
          "id":"1d6fbb7fc96f409196856e44e1a357c6",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":144,
              "y":135},
            "size":{
              "width":94,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1dcad7b46abf41c38efecdab8a0648d8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":144,
                  "y":135},
                "size":{
                  "width":94,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30a4104fc9b8478599d8a06bafd6a24f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":137},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ff5fb10eae4481d8f1fbb01b1eb15f8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":137},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店预订/u46.png"}},
{
          "id":"378b8227551848b8a3ee66b227f3e4bc",
          "label":"paragraph",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"14px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2087FC,
              "opacity":1},
            "location":{
              "x":280,
              "y":137},
            "size":{
              "width":58,
              "height":17},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1e72d1bce39442e9ff18a4ed9c8d2fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"14px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2087FC,
                  "opacity":1},
                "location":{
                  "x":280,
                  "y":137},
                "size":{
                  "width":58,
                  "height":17},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"045613ecc883426eb04b140da74d1ed4",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":164,
              "y":221},
            "size":{
              "width":41,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a6b1da4c665475db4f803f02a09f6fc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":164,
                  "y":221},
                "size":{
                  "width":41,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"edb215eb6f5c4223afe7cb76feb41408",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":164,
              "y":261},
            "size":{
              "width":41,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8613174ef4b84cd5a94d8843bab48860",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":164,
                  "y":261},
                "size":{
                  "width":41,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0c3313afc1164443b1ce471b334c83ad",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":164,
              "y":301},
            "size":{
              "width":81,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56e339e0df4d4f16b628527553aceead",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":164,
                  "y":301},
                "size":{
                  "width":81,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "52b71416b79748cc91a5b0e497b04127":{
      "scriptId":"u0"},
    "e22a70495fd24d84abb85208efd7d1c3":{
      "scriptId":"u1"},
    "b231891741ad47ffb5d5dc0fcd598469":{
      "scriptId":"u2"},
    "3211ee1c1e0f4b4ebebba8f7387940b6":{
      "scriptId":"u3"},
    "b8dd29d9dffd4ec897c4a4403715b3ff":{
      "scriptId":"u4"},
    "a4634bfd2c8b4995b7ea140a240d3221":{
      "scriptId":"u5"},
    "fb1a06f7a73045d98ad44be9bba75b13":{
      "scriptId":"u6"},
    "09242bfda75c4a7cb436defee450d724":{
      "scriptId":"u7"},
    "120f4810b4b7424ea20048464c27f133":{
      "scriptId":"u8"},
    "2474e13bc27e48cc8cb32c8c872be2bf":{
      "scriptId":"u9"},
    "d076d8a10c364c179f3f6fcab756dd98":{
      "scriptId":"u10"},
    "83bb6635b6424e4b8b755569e2d30c7c":{
      "scriptId":"u11"},
    "87602adeb9ab4b81a98f587ae0c361ae":{
      "scriptId":"u12"},
    "37d4b7c0ce9146e3a11e22b0e7e5c374":{
      "scriptId":"u13"},
    "6161cc2a1cdf44898e3bd96822e3617d":{
      "scriptId":"u14"},
    "2d439168fef54699917dec0083e9b664":{
      "scriptId":"u15"},
    "e428eb6e778743fa98e2716c049e2e08":{
      "scriptId":"u16"},
    "ecbfc1d6e4064a3bb6051e01818ffcfb":{
      "scriptId":"u17"},
    "b4dc02637754409a9cf7a6f109788e41":{
      "scriptId":"u18"},
    "4b828f122b6e46f59c74bf66ef655529":{
      "scriptId":"u19"},
    "91ab1f09db5f402cb381e53b3f99a62e":{
      "scriptId":"u20"},
    "f0289f69169d498c92c77e14bea7179d":{
      "scriptId":"u21"},
    "9b84a255be194c9780328f698fc23175":{
      "scriptId":"u22"},
    "1ee5fd557ef640308df96505fb3d2665":{
      "scriptId":"u23"},
    "6cfc34a0aac542e98dad3e92377b4d0e":{
      "scriptId":"u24"},
    "1b5a6c2c12b94222924cc0a5cad75317":{
      "scriptId":"u25"},
    "2dbc75212f164ffd893bd3b1f8b7bdd7":{
      "scriptId":"u26"},
    "d3f5e478822744579abab3e8a33c5db3":{
      "scriptId":"u27"},
    "6c300d6aa0ee421f9f277890a01db0db":{
      "scriptId":"u28"},
    "17e972d8bbbc4f018158f393dc52ba47":{
      "scriptId":"u29"},
    "677d2d7c809140529a7e355869bb5462":{
      "scriptId":"u30"},
    "285bf54334b74db08c3ed7f0f3f2f2a7":{
      "scriptId":"u31"},
    "e58bf2aa0439413480d69d4e03c7b1b9":{
      "scriptId":"u32"},
    "615c761eb8cc4ea7b6c64b58c25bc5dd":{
      "scriptId":"u33"},
    "cdde7adc46f7484ca1c27f8117009824":{
      "scriptId":"u34"},
    "136301e1664549bfb8849e98fbf18e5e":{
      "scriptId":"u35"},
    "1914546f82754d3bb4538abadddc24a7":{
      "scriptId":"u36"},
    "bb1bd84a3fa94677935b8a4e3d8cee58":{
      "scriptId":"u37"},
    "fc8ecad6dc70485ea473300beda589d6":{
      "scriptId":"u38"},
    "2705cf8ae0f44c06b76c1dddcfff1735":{
      "scriptId":"u39"},
    "450b550fb74c49d0934d3ea90dc5b297":{
      "scriptId":"u40"},
    "e49027d45b064e77b5defa2c31077b36":{
      "scriptId":"u41"},
    "7be285011e844304855310702ee895d0":{
      "scriptId":"u42"},
    "1d6fbb7fc96f409196856e44e1a357c6":{
      "scriptId":"u43"},
    "1dcad7b46abf41c38efecdab8a0648d8":{
      "scriptId":"u44"},
    "30a4104fc9b8478599d8a06bafd6a24f":{
      "scriptId":"u45"},
    "4ff5fb10eae4481d8f1fbb01b1eb15f8":{
      "scriptId":"u46"},
    "378b8227551848b8a3ee66b227f3e4bc":{
      "scriptId":"u47"},
    "e1e72d1bce39442e9ff18a4ed9c8d2fc":{
      "scriptId":"u48"},
    "045613ecc883426eb04b140da74d1ed4":{
      "scriptId":"u49"},
    "7a6b1da4c665475db4f803f02a09f6fc":{
      "scriptId":"u50"},
    "edb215eb6f5c4223afe7cb76feb41408":{
      "scriptId":"u51"},
    "8613174ef4b84cd5a94d8843bab48860":{
      "scriptId":"u52"},
    "0c3313afc1164443b1ce471b334c83ad":{
      "scriptId":"u53"},
    "56e339e0df4d4f16b628527553aceead":{
      "scriptId":"u54"}}});