$axure.loadCurrentPage({
  "url":"收款银行卡（用户信息中）.html",
  "generationDate":new Date(1411007650906.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"82d78eeb886b40fc88658efba240cbc4",
    "type":"Axure:Page",
    "name":"收款银行卡（用户信息中）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"b3c26c0c7daa4f7ea6dd54af8ecebf37",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":36},
            "size":{
              "width":380,
              "height":744},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a037bb6676741899a298fe94bb700ab",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":36},
                "size":{
                  "width":380,
                  "height":744},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工资收发/u0.png"}},
{
          "id":"71ea09b643404b63b4f8537e5b8b1d2c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":61,
              "y":188},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b55726ac52c4b0eaec2eae96f6eb0d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":61,
                  "y":188},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工资收发/u2.png"}},
{
          "id":"be92eb9a8ca24b58a4e05989b4dad5f5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":72,
              "y":173},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"733f562cc5634deea0dabfe3face12e1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":72,
                  "y":173},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工资收发/u4.png"}},
{
          "id":"9231c7c1fd7d43709585de9fbef89b15",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":310,
              "y":192},
            "size":{
              "width":71,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"06a06c3becaa470fa89b89d8f1abff94",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":310,
                  "y":192},
                "size":{
                  "width":71,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工资收发/u6.png"}},
{
          "id":"a3cb953f93bc46c49633e8ad4ef0117d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":61,
              "y":191},
            "size":{
              "width":71,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d7b2161cf32e461eb353b203cf8c54d7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":61,
                  "y":191},
                "size":{
                  "width":71,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 工资签收",
                      "target":{
                        "targetType":"page",
                        "url":"工资签收.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/工资收发/u6.png"}},
{
          "id":"a63c88ad3c0b4b1ab87d86481299c514",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":142,
              "y":192.5},
            "size":{
              "width":168,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"124bf42deece4082b7f10d9b580253f3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":142,
                  "y":192.5},
                "size":{
                  "width":168,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb4fa012151f49898ab838c52083e5df",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":101,
              "y":261},
            "size":{
              "width":240,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccaa05b9f9654c63a9f53d7686ded096",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":101,
                  "y":261},
                "size":{
                  "width":240,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工资签收/u16.png"}},
{
          "id":"51813e595a554cd4b1250d5aae67fb64",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":101,
              "y":311},
            "size":{
              "width":240,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bdf26536595445918ab1c153a88ffd34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":101,
                  "y":311},
                "size":{
                  "width":240,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工资签收/u16.png"}},
{
          "id":"564f7563493d4afbb9dffac9ca5e6732",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":101,
              "y":370},
            "size":{
              "width":240,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"83fd481cf96640ba8c9c8ae6cd1f01e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":101,
                  "y":370},
                "size":{
                  "width":240,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工资签收/u16.png"}},
{
          "id":"6f873feb331848098fa762d1dc153be4",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":101,
              "y":430},
            "size":{
              "width":240,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86e4143a96904b8eb2860c8709c61e46",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":101,
                  "y":430},
                "size":{
                  "width":240,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/工资签收/u16.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "b3c26c0c7daa4f7ea6dd54af8ecebf37":{
      "scriptId":"u0"},
    "7a037bb6676741899a298fe94bb700ab":{
      "scriptId":"u1"},
    "71ea09b643404b63b4f8537e5b8b1d2c":{
      "scriptId":"u2"},
    "6b55726ac52c4b0eaec2eae96f6eb0d0":{
      "scriptId":"u3"},
    "be92eb9a8ca24b58a4e05989b4dad5f5":{
      "scriptId":"u4"},
    "733f562cc5634deea0dabfe3face12e1":{
      "scriptId":"u5"},
    "9231c7c1fd7d43709585de9fbef89b15":{
      "scriptId":"u6"},
    "06a06c3becaa470fa89b89d8f1abff94":{
      "scriptId":"u7"},
    "a3cb953f93bc46c49633e8ad4ef0117d":{
      "scriptId":"u8"},
    "d7b2161cf32e461eb353b203cf8c54d7":{
      "scriptId":"u9"},
    "a63c88ad3c0b4b1ab87d86481299c514":{
      "scriptId":"u10"},
    "124bf42deece4082b7f10d9b580253f3":{
      "scriptId":"u11"},
    "cb4fa012151f49898ab838c52083e5df":{
      "scriptId":"u12"},
    "ccaa05b9f9654c63a9f53d7686ded096":{
      "scriptId":"u13"},
    "51813e595a554cd4b1250d5aae67fb64":{
      "scriptId":"u14"},
    "bdf26536595445918ab1c153a88ffd34":{
      "scriptId":"u15"},
    "564f7563493d4afbb9dffac9ca5e6732":{
      "scriptId":"u16"},
    "83fd481cf96640ba8c9c8ae6cd1f01e8":{
      "scriptId":"u17"},
    "6f873feb331848098fa762d1dc153be4":{
      "scriptId":"u18"},
    "86e4143a96904b8eb2860c8709c61e46":{
      "scriptId":"u19"}}});