$axure.loadCurrentPage({
  "url":"使用授权码.html",
  "generationDate":new Date(1411108789718.75),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"dfdfdef68e9042e1800a5dcb5ab1ec5f",
    "type":"Axure:Page",
    "name":"使用授权码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"632876a88c394f4fa4b56c870db5cc17",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":26},
            "size":{
              "width":380,
              "height":744},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7965f7f43e454d8c805a701a5b50459a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":26},
                "size":{
                  "width":380,
                  "height":744},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝订单支付/u0.png"}},
{
          "id":"42cb6cdb5e06404a98bd96e3bc7a52bb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":51,
              "y":178},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ee4a8c5fb3f84b14855e52514210abdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":51,
                  "y":178},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/填写银行卡/u2.png"}},
{
          "id":"b7dd8088901547a3826185f8c8120f59",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":163},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"856b7b3c0bd544edb9d392eb630e2859",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":163},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝订单支付/u2.png"}},
{
          "id":"3c1a0ff7afad4fbfb0509472bedf2628",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":70,
              "y":354},
            "size":{
              "width":290,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"660eb83c57df4cfb8e8c93732a7a828d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":70,
                  "y":354},
                "size":{
                  "width":290,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/填写银行卡/u6.png"}},
{
          "id":"8b70f47171a542d8a446ec1f9e07582e",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":131,
              "y":187},
            "size":{
              "width":168,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"84a63cd999d646edbf35311970d98cd9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":131,
                  "y":187},
                "size":{
                  "width":168,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"415c7335b0e34a80a6e14c2e758da3de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":163,
              "y":410},
            "size":{
              "width":90,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"48e41061818e493994177f0c4941e556",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":163,
                  "y":410},
                "size":{
                  "width":90,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 信用卡支付",
                      "target":{
                        "targetType":"page",
                        "url":"信用卡支付_2.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/填写银行卡/u10.png"}},
{
          "id":"4cb67883a555438bbe8f9fd9f4cf9cea",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":61,
              "y":186},
            "size":{
              "width":39,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6dd9866bc8ba462780b65b9975dc6be7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":61,
                  "y":186},
                "size":{
                  "width":39,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 银行卡支付",
                      "target":{
                        "targetType":"page",
                        "url":"银行卡支付.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/填写银行卡/u12.png"}},
{
          "id":"71b1a860cac044ac8ce8e06bf388f292",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":71,
              "y":318},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"21a3dd3f89a245819dfdc729df876bd0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":71,
                  "y":318},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"146c7d065cf646b4aa148ce2ec5a4293",
          "label":"",
          "type":"radioButton",
          "styleType":"radioButton",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":163,
              "y":318},
            "size":{
              "width":92,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5bed20fdcb5c4e928679acef474c1834",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":163,
                  "y":318},
                "size":{
                  "width":92,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"56d352ca3ec7419b945968646b8ab3e9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":290,
              "y":354},
            "size":{
              "width":70,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"de85144525674bc08bd47654b9de9ce0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":290,
                  "y":354},
                "size":{
                  "width":70,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 我的银行卡",
                      "target":{
                        "targetType":"page",
                        "url":"我的银行卡.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/填写银行卡/u18.png"}},
{
          "id":"84c78ba1f9c94ac3af2e97c83ae924b2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":70,
              "y":254},
            "size":{
              "width":290,
              "height":36}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8f403fd115674aba89268379687dd894",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":70,
                  "y":254},
                "size":{
                  "width":290,
                  "height":36}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/填写银行卡/u6.png"}},
{
          "id":"3674719a953d46f99fd24f57fbc8229a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":410,
              "y":318},
            "size":{
              "width":390,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2bc7d84bf9cc4fb1b2da81d6fbc0b1e3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":410,
                  "y":318},
                "size":{
                  "width":390,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/填写银行卡/u20.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "632876a88c394f4fa4b56c870db5cc17":{
      "scriptId":"u0"},
    "7965f7f43e454d8c805a701a5b50459a":{
      "scriptId":"u1"},
    "42cb6cdb5e06404a98bd96e3bc7a52bb":{
      "scriptId":"u2"},
    "ee4a8c5fb3f84b14855e52514210abdd":{
      "scriptId":"u3"},
    "b7dd8088901547a3826185f8c8120f59":{
      "scriptId":"u4"},
    "856b7b3c0bd544edb9d392eb630e2859":{
      "scriptId":"u5"},
    "3c1a0ff7afad4fbfb0509472bedf2628":{
      "scriptId":"u6"},
    "660eb83c57df4cfb8e8c93732a7a828d":{
      "scriptId":"u7"},
    "8b70f47171a542d8a446ec1f9e07582e":{
      "scriptId":"u8"},
    "84a63cd999d646edbf35311970d98cd9":{
      "scriptId":"u9"},
    "415c7335b0e34a80a6e14c2e758da3de":{
      "scriptId":"u10"},
    "48e41061818e493994177f0c4941e556":{
      "scriptId":"u11"},
    "4cb67883a555438bbe8f9fd9f4cf9cea":{
      "scriptId":"u12"},
    "6dd9866bc8ba462780b65b9975dc6be7":{
      "scriptId":"u13"},
    "71b1a860cac044ac8ce8e06bf388f292":{
      "scriptId":"u14"},
    "21a3dd3f89a245819dfdc729df876bd0":{
      "scriptId":"u15"},
    "146c7d065cf646b4aa148ce2ec5a4293":{
      "scriptId":"u16"},
    "5bed20fdcb5c4e928679acef474c1834":{
      "scriptId":"u17"},
    "56d352ca3ec7419b945968646b8ab3e9":{
      "scriptId":"u18"},
    "de85144525674bc08bd47654b9de9ce0":{
      "scriptId":"u19"},
    "84c78ba1f9c94ac3af2e97c83ae924b2":{
      "scriptId":"u20"},
    "8f403fd115674aba89268379687dd894":{
      "scriptId":"u21"},
    "3674719a953d46f99fd24f57fbc8229a":{
      "scriptId":"u22"},
    "2bc7d84bf9cc4fb1b2da81d6fbc0b1e3":{
      "scriptId":"u23"}}});