$axure.loadCurrentPage({
  "url":"订单支付页.html",
  "generationDate":new Date(1416378074875),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"rl_date",
"rl_day"],
  "page":{
    "packageId":"0d61130f3c0141c49d5ad6da411e9593",
    "type":"Axure:Page",
    "name":"订单支付页",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"fb4682ea8b794b22b1a8187b9670a5f8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":116},
            "size":{
              "width":8,
              "height":36},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d8c25e4ded004e8c840e96cc9bc291ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":116},
                "size":{
                  "width":8,
                  "height":36},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u0.png"}},
{
          "id":"ee88cc802d0344908c9b5609ccc416c0",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":192},
            "size":{
              "width":8,
              "height":27},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9a06fbbbb57c43c7a2a36caf6588784e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":192},
                "size":{
                  "width":8,
                  "height":27},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u2.png"}},
{
          "id":"ce57103d4d60423aa379946b54822de7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":255},
            "size":{
              "width":8,
              "height":27},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd4e2571f01c43739d4aab6d7003756a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":255},
                "size":{
                  "width":8,
                  "height":27},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u2.png"}},
{
          "id":"28c41b5fb49f4ba2a6d33493cb78d1ba",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":0},
            "size":{
              "width":60,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"eedb1a0ee22e46d8b064b2f5eb2876a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":259,
                  "y":0},
                "size":{
                  "width":60,
                  "height":10},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u6.png"}},
{
          "id":"eb7aee999ba54bf1af749b4c0d51c7c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":6},
            "size":{
              "width":372,
              "height":796},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"52"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3f5d2e84dfcc4f48a3e9c2a731078e74",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":6},
                "size":{
                  "width":372,
                  "height":796},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"52"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u8.png"}},
{
          "id":"65cf68adbb9d41eb992b6f9ab4a70895",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":32,
              "y":120},
            "size":{
              "width":320,
              "height":568},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5889c9af84c84c4c91bbb5434a27f831",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":32,
                  "y":120},
                "size":{
                  "width":320,
                  "height":568},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单支付页/u10.png"}},
{
          "id":"7ab90e1f57ee4d54abe895d5d44baa57",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":157,
              "y":66},
            "size":{
              "width":70,
              "height":14},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"35"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"966ed103436840adbcfdb2d13e15be0a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":157,
                  "y":66},
                "size":{
                  "width":70,
                  "height":14},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"35"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u12.png"}},
{
          "id":"7a5cecdba8de46ac93578087121e866c",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":185,
              "y":40},
            "size":{
              "width":14,
              "height":14},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"35"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1060f4023f3c486794a77272ea54f293",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":185,
                  "y":40},
                "size":{
                  "width":14,
                  "height":14},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"35"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u14.png"}},
{
          "id":"397fd5cf559f43aea47e860c17a82632",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":156,
              "y":704},
            "size":{
              "width":72,
              "height":72},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"35"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0c71db0ca97b44bfa4211c1be39c7569",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":156,
                  "y":704},
                "size":{
                  "width":72,
                  "height":72},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"35"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u16.png"}},
{
          "id":"f00fad9abca943ebab29536bcde29d97",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":121},
            "size":{
              "width":318,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e3b266a760d0436e95d1dc75453d4e8d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":121},
                "size":{
                  "width":318,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店预订/u42.png"}},
{
          "id":"94102d2b8ccd40efae927ec7850e0dea",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":144,
              "y":132},
            "size":{
              "width":94,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dfb6d6de337c4d6cba7b5709280e46f1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":144,
                  "y":132},
                "size":{
                  "width":94,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bb2c9348a6984292a280f8002e62b54f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":134},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2d4cf2960fbb40f28eed3485690ae704",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":134},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"显示 退出支付提示",
                      "objectsToFades":[{
                          "objectPath":["6338fd0b50534e1d97106474f5c8cd26"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 是",
                      "objectsToFades":[{
                          "objectPath":["7e1c6d1830f94bbe9a810c99d5181c08"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]},
{
                      "action":"fadeWidget",
                      "description":"显示 否",
                      "objectsToFades":[{
                          "objectPath":["b9a6d340cf5343ebb553c27c8e183061"],
                          "fadeInfo":{
                            "fadeType":"show",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/酒店预订/u46.png"}},
{
          "id":"672e507f1e084cb1a760b5521d9d9001",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"18px",
            "location":{
              "x":50,
              "y":183},
            "size":{
              "width":73,
              "height":22}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"efdb551a9eb24916b0838c81ed38c984",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"18px",
                "location":{
                  "x":50,
                  "y":183},
                "size":{
                  "width":73,
                  "height":22}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7d165d07647b404989171c09b872b20b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"14px",
            "location":{
              "x":50,
              "y":220},
            "size":{
              "width":241,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9c9b985e867045af94507329922f49cf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"14px",
                "location":{
                  "x":50,
                  "y":220},
                "size":{
                  "width":241,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d3b5e66286cf4731876743e72a8bae48",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":205},
            "size":{
              "width":269,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/订单支付页/u28_line.png"}},
{
          "id":"274ac38301dc40d19679c9de88a80b73",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":246},
            "size":{
              "width":53,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"feb759d6906b4c0e9b6a4fbf2419c6a4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":246},
                "size":{
                  "width":53,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9758b3146a1d40ffa4902a54c1ab65de",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":120,
              "y":246},
            "size":{
              "width":46,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ce7df72d27dc40e6b4db9314c55faa84",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":120,
                  "y":246},
                "size":{
                  "width":46,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9e65137a702b49258223a0888c99e2f6",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":269},
            "size":{
              "width":269,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/订单支付页/u28_line.png"}},
{
          "id":"cce2c8688c78447c8675c6f9dc0f40d6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":50,
              "y":300},
            "size":{
              "width":274,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ae1fe38d9fa6463c8eae473074411583",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":50,
                  "y":300},
                "size":{
                  "width":274,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"8aced8ae407c465c832eaaed6b436f70",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":334},
            "size":{
              "width":27,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7d96524f0c854d1aa816d40d4f86e119",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":334},
                "size":{
                  "width":27,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"be16b505f57946319ca5523c518835c6",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":124,
              "y":330},
            "size":{
              "width":124,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"ea64f5103c804e45978f5d2dedeee97f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":374},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27915b72a7cf42f781c58df628dbbadd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":374},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"52097d1051534742a86281b1596670d2",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":124,
              "y":370},
            "size":{
              "width":42,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"3a81a7235956442d872e691fdac68a6a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":170,
              "y":374},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ec7cf0f414714b0a92edd3f6f021b84a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":170,
                  "y":374},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a5d31b76762c4c8d9a0dbab97cbac4f6",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":419},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2192f9df5dd42edadaea59345a4ef36",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":419},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bbf2c7b6cc6d43189c52b7ffdd90eb1a",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC,
              "opacity":1},
            "location":{
              "x":124,
              "y":415},
            "size":{
              "width":80,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"fd9314413c7f4e90ba8701e906d11f51",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":258,
              "y":330},
            "size":{
              "width":61,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"941f6cb10e574488a45ae71fb4c07ea3",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "location":{
              "x":186,
              "y":369.5},
            "size":{
              "width":42,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"9a12355fb73b4fec9921821f3cac9397",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":234,
              "y":374},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c13033e260f8471faff9247e6749623c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":234,
                  "y":374},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"d03309b28e5b40d582fa44c44296417d",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":630},
            "size":{
              "width":280,
              "height":40}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订单结果页面 - 预付",
                      "target":{
                        "targetType":"page",
                        "url":"订单结果页面_-_预付.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"6338fd0b50534e1d97106474f5c8cd26",
          "label":"退出支付提示",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":false,
          "style":{
            "location":{
              "x":60,
              "y":255},
            "size":{
              "width":250,
              "height":100},
            "visible":false},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1a202e1f76b34d1b99821496c087cc9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":false,
              "style":{
                "location":{
                  "x":60,
                  "y":255},
                "size":{
                  "width":250,
                  "height":100},
                "visible":false},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单支付页/退出支付提示_u52.png"}},
{
          "id":"7e1c6d1830f94bbe9a810c99d5181c08",
          "label":"是",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "location":{
              "x":80,
              "y":316},
            "size":{
              "width":100,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 订单确认页 - 预订",
                      "target":{
                        "targetType":"page",
                        "url":"订单确认页_-_预订.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"b9a6d340cf5343ebb553c27c8e183061",
          "label":"否",
          "type":"button",
          "styleType":"button",
          "visible":false,
          "style":{
            "location":{
              "x":200,
              "y":316},
            "size":{
              "width":100,
              "height":25},
            "visible":false},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"fadeWidget",
                      "description":"隐藏 退出支付提示,<br>是,<br>否",
                      "objectsToFades":[{
                          "objectPath":["6338fd0b50534e1d97106474f5c8cd26"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["7e1c6d1830f94bbe9a810c99d5181c08"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}},
{
                          "objectPath":["b9a6d340cf5343ebb553c27c8e183061"],
                          "fadeInfo":{
                            "fadeType":"hide",
                            "options":{
                              "showType":"none"}}}]}]}]}},
          "tabbable":true},
{
          "id":"fe4c1287ffff4667991e80f9e20afb2e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "horizontalAlignment":"left",
            "location":{
              "x":60,
              "y":470},
            "size":{
              "width":259,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2c1de10e742647329bedc7244df71f24",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "horizontalAlignment":"left",
                "location":{
                  "x":60,
                  "y":470},
                "size":{
                  "width":259,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/订单支付页/u56.png"}},
{
          "id":"f43dd3393ee74d499c38c494381ea391",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":60,
              "y":454},
            "size":{
              "width":40,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"16813ff177964061a06b2f41e3f7e753",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":60,
                  "y":454},
                "size":{
                  "width":40,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}}]}},
  "masters":{
},
  "objectPaths":{
    "fb4682ea8b794b22b1a8187b9670a5f8":{
      "scriptId":"u0"},
    "d8c25e4ded004e8c840e96cc9bc291ce":{
      "scriptId":"u1"},
    "ee88cc802d0344908c9b5609ccc416c0":{
      "scriptId":"u2"},
    "9a06fbbbb57c43c7a2a36caf6588784e":{
      "scriptId":"u3"},
    "ce57103d4d60423aa379946b54822de7":{
      "scriptId":"u4"},
    "cd4e2571f01c43739d4aab6d7003756a":{
      "scriptId":"u5"},
    "28c41b5fb49f4ba2a6d33493cb78d1ba":{
      "scriptId":"u6"},
    "eedb1a0ee22e46d8b064b2f5eb2876a4":{
      "scriptId":"u7"},
    "eb7aee999ba54bf1af749b4c0d51c7c8":{
      "scriptId":"u8"},
    "3f5d2e84dfcc4f48a3e9c2a731078e74":{
      "scriptId":"u9"},
    "65cf68adbb9d41eb992b6f9ab4a70895":{
      "scriptId":"u10"},
    "5889c9af84c84c4c91bbb5434a27f831":{
      "scriptId":"u11"},
    "7ab90e1f57ee4d54abe895d5d44baa57":{
      "scriptId":"u12"},
    "966ed103436840adbcfdb2d13e15be0a":{
      "scriptId":"u13"},
    "7a5cecdba8de46ac93578087121e866c":{
      "scriptId":"u14"},
    "1060f4023f3c486794a77272ea54f293":{
      "scriptId":"u15"},
    "397fd5cf559f43aea47e860c17a82632":{
      "scriptId":"u16"},
    "0c71db0ca97b44bfa4211c1be39c7569":{
      "scriptId":"u17"},
    "f00fad9abca943ebab29536bcde29d97":{
      "scriptId":"u18"},
    "e3b266a760d0436e95d1dc75453d4e8d":{
      "scriptId":"u19"},
    "94102d2b8ccd40efae927ec7850e0dea":{
      "scriptId":"u20"},
    "dfb6d6de337c4d6cba7b5709280e46f1":{
      "scriptId":"u21"},
    "bb2c9348a6984292a280f8002e62b54f":{
      "scriptId":"u22"},
    "2d4cf2960fbb40f28eed3485690ae704":{
      "scriptId":"u23"},
    "672e507f1e084cb1a760b5521d9d9001":{
      "scriptId":"u24"},
    "efdb551a9eb24916b0838c81ed38c984":{
      "scriptId":"u25"},
    "7d165d07647b404989171c09b872b20b":{
      "scriptId":"u26"},
    "9c9b985e867045af94507329922f49cf":{
      "scriptId":"u27"},
    "d3b5e66286cf4731876743e72a8bae48":{
      "scriptId":"u28"},
    "274ac38301dc40d19679c9de88a80b73":{
      "scriptId":"u29"},
    "feb759d6906b4c0e9b6a4fbf2419c6a4":{
      "scriptId":"u30"},
    "9758b3146a1d40ffa4902a54c1ab65de":{
      "scriptId":"u31"},
    "ce7df72d27dc40e6b4db9314c55faa84":{
      "scriptId":"u32"},
    "9e65137a702b49258223a0888c99e2f6":{
      "scriptId":"u33"},
    "cce2c8688c78447c8675c6f9dc0f40d6":{
      "scriptId":"u34"},
    "ae1fe38d9fa6463c8eae473074411583":{
      "scriptId":"u35"},
    "8aced8ae407c465c832eaaed6b436f70":{
      "scriptId":"u36"},
    "7d96524f0c854d1aa816d40d4f86e119":{
      "scriptId":"u37"},
    "be16b505f57946319ca5523c518835c6":{
      "scriptId":"u38"},
    "ea64f5103c804e45978f5d2dedeee97f":{
      "scriptId":"u39"},
    "27915b72a7cf42f781c58df628dbbadd":{
      "scriptId":"u40"},
    "52097d1051534742a86281b1596670d2":{
      "scriptId":"u41"},
    "3a81a7235956442d872e691fdac68a6a":{
      "scriptId":"u42"},
    "ec7cf0f414714b0a92edd3f6f021b84a":{
      "scriptId":"u43"},
    "a5d31b76762c4c8d9a0dbab97cbac4f6":{
      "scriptId":"u44"},
    "a2192f9df5dd42edadaea59345a4ef36":{
      "scriptId":"u45"},
    "bbf2c7b6cc6d43189c52b7ffdd90eb1a":{
      "scriptId":"u46"},
    "fd9314413c7f4e90ba8701e906d11f51":{
      "scriptId":"u47"},
    "941f6cb10e574488a45ae71fb4c07ea3":{
      "scriptId":"u48"},
    "9a12355fb73b4fec9921821f3cac9397":{
      "scriptId":"u49"},
    "c13033e260f8471faff9247e6749623c":{
      "scriptId":"u50"},
    "d03309b28e5b40d582fa44c44296417d":{
      "scriptId":"u51"},
    "6338fd0b50534e1d97106474f5c8cd26":{
      "scriptId":"u52"},
    "1a202e1f76b34d1b99821496c087cc9e":{
      "scriptId":"u53"},
    "7e1c6d1830f94bbe9a810c99d5181c08":{
      "scriptId":"u54"},
    "b9a6d340cf5343ebb553c27c8e183061":{
      "scriptId":"u55"},
    "fe4c1287ffff4667991e80f9e20afb2e":{
      "scriptId":"u56"},
    "2c1de10e742647329bedc7244df71f24":{
      "scriptId":"u57"},
    "f43dd3393ee74d499c38c494381ea391":{
      "scriptId":"u58"},
    "16813ff177964061a06b2f41e3f7e753":{
      "scriptId":"u59"}}});