$axure.loadCurrentPage({
  "url":"我的银行卡.html",
  "generationDate":new Date(1411119109437.5),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"961e2af7f0264e88a3507e71d38d8971",
    "type":"Axure:Page",
    "name":"我的银行卡",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"16baffdf95b1487bb59e582c4ef9493b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":26},
            "size":{
              "width":380,
              "height":744},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ef96b7a9dde04e0fb122cd09955562b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":26},
                "size":{
                  "width":380,
                  "height":744},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝订单支付/u0.png"}},
{
          "id":"ef5eb83ab96d43809645eaa3b5f0d697",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":51,
              "y":178},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dab6642618234c549c5c6caa516d0816",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":51,
                  "y":178},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/填写银行卡/u2.png"}},
{
          "id":"ec74bd0f4bbc41c7b198497b46913fa1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":163},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a35850f26caa4436a9648bde41248516",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":163},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/通付宝订单支付/u2.png"}},
{
          "id":"983189a7e8664c3ba3981864422b7424",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":122,
              "y":182},
            "size":{
              "width":168,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f21082f979854e339829e024a0a4e699",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":122,
                  "y":182},
                "size":{
                  "width":168,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a0055da8e72246aba6425e16d4f2e188",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":250},
            "size":{
              "width":260,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54573f6282c04a369d738caf23da9422",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":250},
                "size":{
                  "width":260,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 填写银行卡",
                      "target":{
                        "targetType":"page",
                        "url":"填写银行卡.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的银行卡/u8.png"}},
{
          "id":"5c9a1bbbfc0141f78b2885ca17eabffc",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":300,
              "y":186},
            "size":{
              "width":70,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6cfc8f4318a4186a1fd424d55b0050f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":300,
                  "y":186},
                "size":{
                  "width":70,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的银行卡/u10.png"}},
{
          "id":"5d65bb9721de4e78af5b4c1331715c97",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":330},
            "size":{
              "width":260,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"dc8ea6df566442f896795e2bf5d124f9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":330},
                "size":{
                  "width":260,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 填写银行卡",
                      "target":{
                        "targetType":"page",
                        "url":"填写银行卡.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/我的银行卡/u8.png"}},
{
          "id":"ec72557ea0e34a4bbd14cb900366df31",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":61,
              "y":186},
            "size":{
              "width":39,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"851f19978a624a28b7e5403237e9115a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":61,
                  "y":186},
                "size":{
                  "width":39,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 填写银行卡",
                      "target":{
                        "targetType":"page",
                        "url":"填写银行卡.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/填写银行卡/u12.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "16baffdf95b1487bb59e582c4ef9493b":{
      "scriptId":"u0"},
    "ef96b7a9dde04e0fb122cd09955562b7":{
      "scriptId":"u1"},
    "ef5eb83ab96d43809645eaa3b5f0d697":{
      "scriptId":"u2"},
    "dab6642618234c549c5c6caa516d0816":{
      "scriptId":"u3"},
    "ec74bd0f4bbc41c7b198497b46913fa1":{
      "scriptId":"u4"},
    "a35850f26caa4436a9648bde41248516":{
      "scriptId":"u5"},
    "983189a7e8664c3ba3981864422b7424":{
      "scriptId":"u6"},
    "f21082f979854e339829e024a0a4e699":{
      "scriptId":"u7"},
    "a0055da8e72246aba6425e16d4f2e188":{
      "scriptId":"u8"},
    "54573f6282c04a369d738caf23da9422":{
      "scriptId":"u9"},
    "5c9a1bbbfc0141f78b2885ca17eabffc":{
      "scriptId":"u10"},
    "b6cfc8f4318a4186a1fd424d55b0050f":{
      "scriptId":"u11"},
    "5d65bb9721de4e78af5b4c1331715c97":{
      "scriptId":"u12"},
    "dc8ea6df566442f896795e2bf5d124f9":{
      "scriptId":"u13"},
    "ec72557ea0e34a4bbd14cb900366df31":{
      "scriptId":"u14"},
    "851f19978a624a28b7e5403237e9115a":{
      "scriptId":"u15"}}});