$axure.loadCurrentPage({
  "url":"当面支付（发起支付）.html",
  "generationDate":new Date(1399184856394.64),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"9fb8b67b76e844dca989cf3d64cf3ab8",
    "type":"Axure:Page",
    "name":"当面支付（发起支付）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"d39ec885d8fa4482974355949a2ccb7c",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":94,
              "y":208},
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d16486053ae2439eaba0f39639ef1b7c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":94,
                  "y":208},
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u0.png"}},
{
          "id":"22153e04bb97450abad78823353692a0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":132,
              "y":329},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1f4e7a0d7e1841ae8aff1a537fdd6398",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":132,
                  "y":329},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u2.png"}},
{
          "id":"cba753b8f962417a8887c0347ac5657b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":160,
              "y":349},
            "size":{
              "width":250,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"00d56ebfdcbc4680acd784af7a517c06",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":160,
                  "y":349},
                "size":{
                  "width":250,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当面支付（响应支付）/u4.png"}},
{
          "id":"f37748a870fa449e899a6e68aacef006",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":136,
              "y":798},
            "size":{
              "width":189,
              "height":78}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"349082356db843fcafc824fda15cf11a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":136,
                  "y":798},
                "size":{
                  "width":189,
                  "height":78}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当面支付（发起支付）/u6.png"}},
{
          "id":"7f168cc7c67e49918f6fd5941981fba9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":788},
            "size":{
              "width":108,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36aa4eca0a3f41bba971a3d9b57f6f48",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":325,
                  "y":788},
                "size":{
                  "width":108,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当面支付（发起支付）/u8.jpg"}},
{
          "id":"f9ae406bc62a4ebf92e753619c51e74f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":370},
            "size":{
              "width":200,
              "height":150}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e7dbedf7ca12484587afda5d21e58cb8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":370},
                "size":{
                  "width":200,
                  "height":150}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当面支付（发起支付）/u10.png"}},
{
          "id":"f64443fa75a44619a37886f4ef53b8a6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":545},
            "size":{
              "width":200,
              "height":64}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"76e067d0ae594669b1a55091daac49cc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":545},
                "size":{
                  "width":200,
                  "height":64}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当面支付（发起支付）/u12.png"}},
{
          "id":"f5d495f506684a2494f685070490facb",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":132,
              "y":422},
            "size":{
              "width":308,
              "height":310}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37ced3e9e94345d083192ce966a904e7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":132,
                  "y":422},
                "size":{
                  "width":308,
                  "height":310}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当面支付（发起支付）/u14.png"}},
{
          "id":"a3b034f84183490f9cc849a21921b1bb",
          "label":"",
          "type":"flowShape",
          "styleType":"flowShape",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":525},
            "size":{
              "width":25,
              "height":35}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4a65a4086d72430a8a72f9da559d6bea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":525},
                "size":{
                  "width":25,
                  "height":35}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当面支付（发起支付）/u16.png"}},
{
          "id":"2165ac1c271e48d9a02017cac9842c52",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":165,
              "y":538},
            "size":{
              "width":45,
              "height":42},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b15cc6be50204329ae75e0cf5993b9b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":165,
                  "y":538},
                "size":{
                  "width":45,
                  "height":42},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/当面支付（发起支付）/u18.png"}},
{
          "id":"03aa6870f593424997d462d19c3604cf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":540,
              "y":640},
            "size":{
              "width":200,
              "height":100}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bfb9faeabb394d589ba12014413fced4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":540,
                  "y":640},
                "size":{
                  "width":200,
                  "height":100}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u18.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "d39ec885d8fa4482974355949a2ccb7c":{
      "scriptId":"u0"},
    "d16486053ae2439eaba0f39639ef1b7c":{
      "scriptId":"u1"},
    "22153e04bb97450abad78823353692a0":{
      "scriptId":"u2"},
    "1f4e7a0d7e1841ae8aff1a537fdd6398":{
      "scriptId":"u3"},
    "cba753b8f962417a8887c0347ac5657b":{
      "scriptId":"u4"},
    "00d56ebfdcbc4680acd784af7a517c06":{
      "scriptId":"u5"},
    "f37748a870fa449e899a6e68aacef006":{
      "scriptId":"u6"},
    "349082356db843fcafc824fda15cf11a":{
      "scriptId":"u7"},
    "7f168cc7c67e49918f6fd5941981fba9":{
      "scriptId":"u8"},
    "36aa4eca0a3f41bba971a3d9b57f6f48":{
      "scriptId":"u9"},
    "f9ae406bc62a4ebf92e753619c51e74f":{
      "scriptId":"u10"},
    "e7dbedf7ca12484587afda5d21e58cb8":{
      "scriptId":"u11"},
    "f64443fa75a44619a37886f4ef53b8a6":{
      "scriptId":"u12"},
    "76e067d0ae594669b1a55091daac49cc":{
      "scriptId":"u13"},
    "f5d495f506684a2494f685070490facb":{
      "scriptId":"u14"},
    "37ced3e9e94345d083192ce966a904e7":{
      "scriptId":"u15"},
    "a3b034f84183490f9cc849a21921b1bb":{
      "scriptId":"u16"},
    "4a65a4086d72430a8a72f9da559d6bea":{
      "scriptId":"u17"},
    "2165ac1c271e48d9a02017cac9842c52":{
      "scriptId":"u18"},
    "b15cc6be50204329ae75e0cf5993b9b3":{
      "scriptId":"u19"},
    "03aa6870f593424997d462d19c3604cf":{
      "scriptId":"u20"},
    "bfb9faeabb394d589ba12014413fced4":{
      "scriptId":"u21"}}});