$axure.loadCurrentPage({
  "url":"核对手势密码.html",
  "generationDate":new Date(1399184855106.56),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"c48287bea44d4804aab3b60c0518f924",
    "type":"Axure:Page",
    "name":"核对手势密码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"48854de159b14ab38a830b039c741b5b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":80},
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b6026d47dd904bb4b872d121af1d7831",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":80},
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u0.png"}},
{
          "id":"63721c09f4504c2cb1360ccd20fa23a8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":202},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4795e7fa357b4170a486b38fb2e08104",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":202},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u2.png"}},
{
          "id":"8e462c7ae64d48dbbff6480dfe0b6fb2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":233},
            "size":{
              "width":270,
              "height":47}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"627b977a4a5946d4912710957735ac82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":233},
                "size":{
                  "width":270,
                  "height":47}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手势密码设定一/u4.png"}},
{
          "id":"34bc9c2b94a24ec6962d984acfd41013",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":365},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"620d27e860644cf7a223d59301d80a59",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":365},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手势密码设定一/u6.png"}},
{
          "id":"3331dc57a0794d7a95cba3ac23820e5a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":202.5,
              "y":365},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c00e3fac957d46ca9c7ae7edd1be48c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":202.5,
                  "y":365},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手势密码设定一/u6.png"}},
{
          "id":"2081902832b24ae8b3390eb5844fe548",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":365},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a87d6eccd694bca8a9eeac336a616cb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":325,
                  "y":365},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手势密码设定一/u6.png"}},
{
          "id":"7c0ea5ea0dcf4c8fa025b33297091a9e",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":467.5},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8493333999b346169c4cb08fb4bcde1e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":467.5},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手势密码设定一/u6.png"}},
{
          "id":"337fa82db82d4adebc740190b79633cf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":202,
              "y":468},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"56a4719dd88a4da1bd4bd8fc5c7c25ee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":202,
                  "y":468},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手势密码设定一/u6.png"}},
{
          "id":"40b7d3e9a65a47018a2871c7254b42b5",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":468},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f41657dacd4d4e849c6dc1060b183b5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":325,
                  "y":468},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手势密码设定一/u6.png"}},
{
          "id":"317eefac99f14d478599982a68465ed9",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":585},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ccb6a2e872a54f9d9b899f708ec04fdd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":585},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手势密码设定一/u6.png"}},
{
          "id":"dbda2094340e496bb3578694df294290",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":202,
              "y":585},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f5589eb5d38a41da93831f640a21bf99",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":202,
                  "y":585},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/手势密码设定一/u6.png"}},
{
          "id":"7f3451eb3df445ed93e38647cf0053b1",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":325,
              "y":585},
            "size":{
              "width":25,
              "height":25},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1355321213c4479da0ed162e73c0bb32",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":325,
                  "y":585},
                "size":{
                  "width":25,
                  "height":25},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open 功能列表（新）支付 in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"功能列表（新）支付.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/手势密码设定一/u6.png"}},
{
          "id":"11394977d4b4414f8b74e3f33aac1e9d",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":270},
            "size":{
              "width":200,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3481cd6a2df54f0187e1da9702b077ce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":270},
                "size":{
                  "width":200,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/核对手势密码/u24.png"}},
{
          "id":"31c8c37137dc4f07b615d4d094ffe768",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":420,
              "y":360},
            "size":{
              "width":200,
              "height":60}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7467d67cc8374e33900af48e12a09523",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":420,
                  "y":360},
                "size":{
                  "width":200,
                  "height":60}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u20.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "48854de159b14ab38a830b039c741b5b":{
      "scriptId":"u0"},
    "b6026d47dd904bb4b872d121af1d7831":{
      "scriptId":"u1"},
    "63721c09f4504c2cb1360ccd20fa23a8":{
      "scriptId":"u2"},
    "4795e7fa357b4170a486b38fb2e08104":{
      "scriptId":"u3"},
    "8e462c7ae64d48dbbff6480dfe0b6fb2":{
      "scriptId":"u4"},
    "627b977a4a5946d4912710957735ac82":{
      "scriptId":"u5"},
    "34bc9c2b94a24ec6962d984acfd41013":{
      "scriptId":"u6"},
    "620d27e860644cf7a223d59301d80a59":{
      "scriptId":"u7"},
    "3331dc57a0794d7a95cba3ac23820e5a":{
      "scriptId":"u8"},
    "c00e3fac957d46ca9c7ae7edd1be48c0":{
      "scriptId":"u9"},
    "2081902832b24ae8b3390eb5844fe548":{
      "scriptId":"u10"},
    "7a87d6eccd694bca8a9eeac336a616cb":{
      "scriptId":"u11"},
    "7c0ea5ea0dcf4c8fa025b33297091a9e":{
      "scriptId":"u12"},
    "8493333999b346169c4cb08fb4bcde1e":{
      "scriptId":"u13"},
    "337fa82db82d4adebc740190b79633cf":{
      "scriptId":"u14"},
    "56a4719dd88a4da1bd4bd8fc5c7c25ee":{
      "scriptId":"u15"},
    "40b7d3e9a65a47018a2871c7254b42b5":{
      "scriptId":"u16"},
    "f41657dacd4d4e849c6dc1060b183b5a":{
      "scriptId":"u17"},
    "317eefac99f14d478599982a68465ed9":{
      "scriptId":"u18"},
    "ccb6a2e872a54f9d9b899f708ec04fdd":{
      "scriptId":"u19"},
    "dbda2094340e496bb3578694df294290":{
      "scriptId":"u20"},
    "f5589eb5d38a41da93831f640a21bf99":{
      "scriptId":"u21"},
    "7f3451eb3df445ed93e38647cf0053b1":{
      "scriptId":"u22"},
    "1355321213c4479da0ed162e73c0bb32":{
      "scriptId":"u23"},
    "11394977d4b4414f8b74e3f33aac1e9d":{
      "scriptId":"u24"},
    "3481cd6a2df54f0187e1da9702b077ce":{
      "scriptId":"u25"},
    "31c8c37137dc4f07b615d4d094ffe768":{
      "scriptId":"u26"},
    "7467d67cc8374e33900af48e12a09523":{
      "scriptId":"u27"}}});