$axure.loadCurrentPage({
  "url":"系统重新登陆.html",
  "generationDate":new Date(1398151328992.32),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7c7a9383ad00446098db2646529cc510",
    "type":"Axure:Page",
    "name":"系统重新登陆",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bdd27477b3f1496bae7eed96a60dc5f2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":80},
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b4e7599bfa8d40c7bda1cf12cd80b9d3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":80},
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u0.png"}},
{
          "id":"499a551e68854e4f85c02eac90da28c6",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":202},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a50d161c2e864ee09e43b01c630c2b18",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":202},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u2.png"}},
{
          "id":"5d69baa8a8b94eefa15dbbacac41accb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":233},
            "size":{
              "width":270,
              "height":77}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8703e2ca41ac4e37bcb71fb4d8c0097f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":233},
                "size":{
                  "width":270,
                  "height":77}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u4.png"}},
{
          "id":"cd5f6d9508c7423aa1d101e47a02d743",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":220,
              "y":463},
            "size":{
              "width":130,
              "height":47}},
          "adaptiveStyles":{
}},
{
          "id":"2e9598c9094243f286a210870b065031",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":53,
              "y":545},
            "size":{
              "width":320,
              "height":216},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e0359fcf128b4f93af461d26027b3050",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":53,
                  "y":545},
                "size":{
                  "width":320,
                  "height":216},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u9.png"}},
{
          "id":"aa9fe74755b941d79ac4affa6c1b49bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":80,
              "y":326},
            "size":{
              "width":270,
              "height":44}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4ee0518d63e74d3f9614e0c9c56da1dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":80,
                  "y":326},
                "size":{
                  "width":270,
                  "height":44}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u11.png"}},
{
          "id":"2f06d3ab30e54adcb414fed8d8711576",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontWeight":"bold",
            "location":{
              "x":450,
              "y":363},
            "size":{
              "width":270,
              "height":179},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"378f682e67a34a818ee821b5f0c16764",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontWeight":"bold",
                "location":{
                  "x":450,
                  "y":363},
                "size":{
                  "width":270,
                  "height":179},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u15.png"}},
{
          "id":"948efcb22a244301b14993b0fd1bf41d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"24px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":499,
              "y":393},
            "size":{
              "width":182,
              "height":29},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"038eb0985ddc4d3bac0cc411b841b2b4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"24px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":499,
                  "y":393},
                "size":{
                  "width":182,
                  "height":29},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a85e1631dae54c46b443f7ce7d6389ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":467,
              "y":440},
            "size":{
              "width":243,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54c373b7a36147078f9a9bd5651e7393",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":467,
                  "y":440},
                "size":{
                  "width":243,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3a81e44b151f43c9a7cc8d0ddc0971d0",
          "label":"paragraph",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Bold', 'Helvetica Neue'",
            "fontSize":"20px",
            "fontWeight":"bold",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2087FC,
              "opacity":1},
            "location":{
              "x":636,
              "y":509},
            "size":{
              "width":39,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b82ddc7bf81f4dd888868018fea7f6a2",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Bold', 'Helvetica Neue'",
                "fontSize":"20px",
                "fontWeight":"bold",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2087FC,
                  "opacity":1},
                "location":{
                  "x":636,
                  "y":509},
                "size":{
                  "width":39,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"991e453d662e4cd3861f7d287a66eee6",
          "label":"paragraph",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"20px",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF2087FC,
              "opacity":1},
            "location":{
              "x":488,
              "y":509},
            "size":{
              "width":78,
              "height":24},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e13ac4205ce34a0ab898a1dc8ad82a00",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"20px",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF2087FC,
                  "opacity":1},
                "location":{
                  "x":488,
                  "y":509},
                "size":{
                  "width":78,
                  "height":24},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"403b610d21cf479faca1816b257e44ec",
          "label":"",
          "type":"button",
          "styleType":"button",
          "visible":true,
          "style":{
            "location":{
              "x":83,
              "y":463},
            "size":{
              "width":117,
              "height":47}},
          "adaptiveStyles":{
}},
{
          "id":"6f091bae39124f6da9a955acee645d9a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":481,
              "y":128},
            "size":{
              "width":200,
              "height":62}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"755c67c4c98a4b75adeff22d24547e57",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":481,
                  "y":128},
                "size":{
                  "width":200,
                  "height":62}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u26.png"}},
{
          "id":"5843260bd4cf42c596a279a5597348e6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":481,
              "y":211},
            "size":{
              "width":200,
              "height":49}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8d41a51c556e432787c861aeeb8e1b8c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":481,
                  "y":211},
                "size":{
                  "width":200,
                  "height":49}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u28.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "bdd27477b3f1496bae7eed96a60dc5f2":{
      "scriptId":"u0"},
    "b4e7599bfa8d40c7bda1cf12cd80b9d3":{
      "scriptId":"u1"},
    "499a551e68854e4f85c02eac90da28c6":{
      "scriptId":"u2"},
    "a50d161c2e864ee09e43b01c630c2b18":{
      "scriptId":"u3"},
    "5d69baa8a8b94eefa15dbbacac41accb":{
      "scriptId":"u4"},
    "8703e2ca41ac4e37bcb71fb4d8c0097f":{
      "scriptId":"u5"},
    "cd5f6d9508c7423aa1d101e47a02d743":{
      "scriptId":"u6"},
    "2e9598c9094243f286a210870b065031":{
      "scriptId":"u7"},
    "e0359fcf128b4f93af461d26027b3050":{
      "scriptId":"u8"},
    "aa9fe74755b941d79ac4affa6c1b49bf":{
      "scriptId":"u9"},
    "4ee0518d63e74d3f9614e0c9c56da1dc":{
      "scriptId":"u10"},
    "2f06d3ab30e54adcb414fed8d8711576":{
      "scriptId":"u11"},
    "378f682e67a34a818ee821b5f0c16764":{
      "scriptId":"u12"},
    "948efcb22a244301b14993b0fd1bf41d":{
      "scriptId":"u13"},
    "038eb0985ddc4d3bac0cc411b841b2b4":{
      "scriptId":"u14"},
    "a85e1631dae54c46b443f7ce7d6389ef":{
      "scriptId":"u15"},
    "54c373b7a36147078f9a9bd5651e7393":{
      "scriptId":"u16"},
    "3a81e44b151f43c9a7cc8d0ddc0971d0":{
      "scriptId":"u17"},
    "b82ddc7bf81f4dd888868018fea7f6a2":{
      "scriptId":"u18"},
    "991e453d662e4cd3861f7d287a66eee6":{
      "scriptId":"u19"},
    "e13ac4205ce34a0ab898a1dc8ad82a00":{
      "scriptId":"u20"},
    "403b610d21cf479faca1816b257e44ec":{
      "scriptId":"u21"},
    "6f091bae39124f6da9a955acee645d9a":{
      "scriptId":"u22"},
    "755c67c4c98a4b75adeff22d24547e57":{
      "scriptId":"u23"},
    "5843260bd4cf42c596a279a5597348e6":{
      "scriptId":"u24"},
    "8d41a51c556e432787c861aeeb8e1b8c":{
      "scriptId":"u25"}}});