$axure.loadCurrentPage({
  "url":"酒店列表页面.html",
  "generationDate":new Date(1416378073296.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable",
"rl_date",
"rl_day"],
  "page":{
    "packageId":"dd9bd7d3546d48c69cd41547cb6c9f38",
    "type":"Axure:Page",
    "name":"酒店列表页面",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"应用字体",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"0b45123d05c64e658b57a4d3da00892e",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":116},
            "size":{
              "width":8,
              "height":36},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65acb8d2b47c441da525417224f26553",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":116},
                "size":{
                  "width":8,
                  "height":36},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u0.png"}},
{
          "id":"5fe6c75503ef464db75d915620ca0b24",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":192},
            "size":{
              "width":8,
              "height":27},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b859d2ef9e1a4ec2853ed8636a26a10b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":192},
                "size":{
                  "width":8,
                  "height":27},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u2.png"}},
{
          "id":"a9130a63bf27468494e42563f95a5579",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":255},
            "size":{
              "width":8,
              "height":27},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"1"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70ff0e62b5524952b2c20cb36e5874c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":0,
                  "y":255},
                "size":{
                  "width":8,
                  "height":27},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"1"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u2.png"}},
{
          "id":"eac163fc6b7d491c9ce02013f78d82e8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":259,
              "y":0},
            "size":{
              "width":60,
              "height":10},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"5"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"36393678c390418794c898daee8bde14",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":259,
                  "y":0},
                "size":{
                  "width":60,
                  "height":10},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"5"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u6.png"}},
{
          "id":"dea78c9910d9405b8b33c10dc9743dc8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":6,
              "y":6},
            "size":{
              "width":372,
              "height":796},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"52"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8ef0731662a243c091503574fb8a708a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":6,
                  "y":6},
                "size":{
                  "width":372,
                  "height":796},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"52"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/首页面/u8.png"}},
{
          "id":"07fbfdec451f459ead5ffa24c266b7d7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":32,
              "y":120},
            "size":{
              "width":320,
              "height":568},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cf95eda3d3eb400c90f7da5446f67f5a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":32,
                  "y":120},
                "size":{
                  "width":320,
                  "height":568},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店预订/u10.png"}},
{
          "id":"42f582fbaf8341c8ade18000532ba7c5",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":157,
              "y":66},
            "size":{
              "width":70,
              "height":14},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"35"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1bf35dbeb9df484285c1e6dd5a0b8f22",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":157,
                  "y":66},
                "size":{
                  "width":70,
                  "height":14},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"35"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店预订/u12.png"}},
{
          "id":"fa8aa18396184e16b544a552993290fb",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":185,
              "y":40},
            "size":{
              "width":14,
              "height":14},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"35"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fe52fa808f6f41b486b4cd316bc5fae3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":185,
                  "y":40},
                "size":{
                  "width":14,
                  "height":14},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"35"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店预订/u14.png"}},
{
          "id":"3a18542396ac463a89cbd3b673137bec",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fill":{
              "fillType":"solid",
              "color":0xFFFFFF},
            "location":{
              "x":156,
              "y":704},
            "size":{
              "width":72,
              "height":72},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999},
            "cornerRadiusTopLeft":"35"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6cb16b8329eb40608299550658e401b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFFFFF},
                "location":{
                  "x":156,
                  "y":704},
                "size":{
                  "width":72,
                  "height":72},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999},
                "cornerRadiusTopLeft":"35"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店预订/u16.png"}},
{
          "id":"02782a44f9c046f79589b5c5fdb29d7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":500,
              "y":860},
            "size":{
              "width":50,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"943ef0e55ad845d0aabd408a99aef36a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":500,
                  "y":860},
                "size":{
                  "width":50,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFFFF}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店列表页面/u18.png"}},
{
          "id":"701cb7c14dff4c9ebacc8cc665904f22",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":122},
            "size":{
              "width":318,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5441152b528649c58c75f77ad8276432",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":122},
                "size":{
                  "width":318,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店预订/u42.png"}},
{
          "id":"16f0b0e1e0734171abf329f3611512f7",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":33,
              "y":122},
            "size":{
              "width":318,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7679a63e498145aabae035dfc17c1df1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":33,
                  "y":122},
                "size":{
                  "width":318,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店预订/u42.png"}},
{
          "id":"50656467df674bd082ad6ec52d2e1490",
          "label":"text - h2",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
            "fontSize":"21px",
            "horizontalAlignment":"center",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF000000,
              "opacity":1},
            "location":{
              "x":144,
              "y":133},
            "size":{
              "width":94,
              "height":25},
            "rotation":"0",
            "textRotation":"0"},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"71e24802a5ab4f4b96477de0d8025fc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Helvetica Neue Regular', 'Helvetica Neue'",
                "fontSize":"21px",
                "horizontalAlignment":"center",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF000000,
                  "opacity":1},
                "location":{
                  "x":144,
                  "y":133},
                "size":{
                  "width":94,
                  "height":25},
                "rotation":"0",
                "textRotation":"0"},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bfe442bff86b42e8a90797c42d9e27ba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":135},
            "size":{
              "width":12,
              "height":20},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a2c404b6146244b1b30d4a8aa5746d7f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":44,
                  "y":135},
                "size":{
                  "width":12,
                  "height":20},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店预订/u46.png"}},
{
          "id":"cbfa0b7fa81b4b6b93ab7afb7ad8059f",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":273},
            "size":{
              "width":277,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/酒店列表页面/u28_line.png"}},
{
          "id":"c731f7d0cadd455e9c92ad18eaa65762",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":192},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2b3f1599d928442ab658e6c7e5701217",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":49,
                  "y":192},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店列表页面/u29.png"}},
{
          "id":"fbb4ce093f5d47bbbf2cea0b1fdb5f21",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "location":{
              "x":139,
              "y":192},
            "size":{
              "width":166,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"598dd5dfd3b645fc89805dfa79d184b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "location":{
                  "x":139,
                  "y":192},
                "size":{
                  "width":166,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b61dedfaa25749e294ed09ecc62cfb50",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":139,
              "y":214},
            "size":{
              "width":21,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8fe387e88cfc4fc5807e7ddf9c0150d0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":139,
                  "y":214},
                "size":{
                  "width":21,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"df4cfe0a3c0f4a4a9a662f2e03c0e025",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":139,
              "y":235},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c84f7fbc9f45414693599ac5b3286cce",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":139,
                  "y":235},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3392f135b4304aaabcc89fb71292725f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":243,
              "y":238},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b530486fe77a468dada64a24d408017d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":238},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3eccd2b0f85b41eab396adeaae7172c8",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":255,
              "y":231},
            "size":{
              "width":45,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f97886065d2545799b625b482ce6b8a0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":255,
                  "y":231},
                "size":{
                  "width":45,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f81b2ccc9ccb4fe590f7553a0b91a74e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":159,
              "y":217},
            "size":{
              "width":11,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5958f952207b4729aa621b3f33a8ff39",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":159,
                  "y":217},
                "size":{
                  "width":11,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ec1890cf28094f7fab8867c5b8631653",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"10px",
            "location":{
              "x":300,
              "y":238},
            "size":{
              "width":11,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"70e25b3953c1435eb5ba4f3aec2e3cb1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"10px",
                "location":{
                  "x":300,
                  "y":238},
                "size":{
                  "width":11,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a1c39a11a63e4e4b9727f6d1c6e19259",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"10px",
            "location":{
              "x":139,
              "y":257},
            "size":{
              "width":119,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"42ac3eeaa58f460894d6f2dddbe25104",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"10px",
                "location":{
                  "x":139,
                  "y":257},
                "size":{
                  "width":119,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"19096f81345c4b8ea72436d61e88c35c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":364},
            "size":{
              "width":277,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/酒店列表页面/u28_line.png"}},
{
          "id":"a7bf4cb21abe4b74b4b845eb235b3525",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":283},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"638de1f5dda44a679f304db3b187fac0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":49,
                  "y":283},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店列表页面/u29.png"}},
{
          "id":"b3bb77eec44d40f4bd9a87a329fe0e6e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "location":{
              "x":139,
              "y":283},
            "size":{
              "width":166,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b8f825361dfb427a8c6b2bfca9cf13b9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "location":{
                  "x":139,
                  "y":283},
                "size":{
                  "width":166,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03fe015c286f46dcb7f41842ff39aebc",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":139,
              "y":305},
            "size":{
              "width":21,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"27bcd7214d134bee9e5f307abac906b8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":139,
                  "y":305},
                "size":{
                  "width":21,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"3416e21ae9e0443b9bc8d1fd92d02fa7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":139,
              "y":326},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"687bcef2272c4f7d894260f79c8335b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":139,
                  "y":326},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"448504d8b30d4dd9bc4b543e892bc603",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":243,
              "y":329},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8a8d26ce867c4380b4629d5b94a52927",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":329},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7fc8b4355efd435086dc2ada43a5b365",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":255,
              "y":322},
            "size":{
              "width":45,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c938e58a8181445785153e042ad84366",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":255,
                  "y":322},
                "size":{
                  "width":45,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5fb402005c8c4df0b9caa6a1e9a50c00",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":159,
              "y":308},
            "size":{
              "width":11,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"81e6df26e65a4658b8e94c8bc3e08d43",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":159,
                  "y":308},
                "size":{
                  "width":11,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"85cd576138b8419fbb302a78b07a23ea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"10px",
            "location":{
              "x":300,
              "y":329},
            "size":{
              "width":11,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cd470807f0c245fdb2c2e1ef9dc338b7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"10px",
                "location":{
                  "x":300,
                  "y":329},
                "size":{
                  "width":11,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"03582df1b7494e288d6f51e50ee7e326",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"10px",
            "location":{
              "x":139,
              "y":348},
            "size":{
              "width":119,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"32083f75d68641419e8276cc374975fd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"10px",
                "location":{
                  "x":139,
                  "y":348},
                "size":{
                  "width":119,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"590462e71e3343ab816f9847f053d494",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":455},
            "size":{
              "width":277,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/酒店列表页面/u28_line.png"}},
{
          "id":"ef32b95ae98e42c5a83bf85f8428f5bf",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":374},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e1c85655f2f24621aa07a78ba3b9eaaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":49,
                  "y":374},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店列表页面/u29.png"}},
{
          "id":"77eff39f45a84e8f948596d7120ea14e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "location":{
              "x":139,
              "y":374},
            "size":{
              "width":166,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f6c4e7a10de346638a9a2f5b4efc799f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "location":{
                  "x":139,
                  "y":374},
                "size":{
                  "width":166,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"69d544a2fd9c4447bc63d1fa340b989e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":139,
              "y":396},
            "size":{
              "width":21,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ca914f9d0d254b8a9f67091cf25bff82",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":139,
                  "y":396},
                "size":{
                  "width":21,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"046457645bf4447c8e521fe598f39f6b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":139,
              "y":417},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"45406e8b12cb4316b10573cfb6a42626",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":139,
                  "y":417},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"bfd84343678a46d493fc9d69601eb0a7",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":243,
              "y":420},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"47e21c4714ce4d3c8c14adede57cab34",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":420},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7e01ae2a5806434db78ccec555ea3a4e",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":255,
              "y":413},
            "size":{
              "width":45,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b08943b3ab5e41b18f8fef4e31f5d35e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":255,
                  "y":413},
                "size":{
                  "width":45,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b6132c4e06d4bd7ba2d7abc14c5186a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":159,
              "y":399},
            "size":{
              "width":11,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c20d8341f9b440c5a128dafe26eaaf9d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":159,
                  "y":399},
                "size":{
                  "width":11,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"04317e841f754f2b9d2f9a1d2aebdeea",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"10px",
            "location":{
              "x":300,
              "y":420},
            "size":{
              "width":11,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0fb933c301f4aed804b6233ae39d852",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"10px",
                "location":{
                  "x":300,
                  "y":420},
                "size":{
                  "width":11,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cd4293be86c74659817328296b1288ac",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"10px",
            "location":{
              "x":139,
              "y":439},
            "size":{
              "width":119,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"bbc9431d36884afb86cb00aba9e4d4e8",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"10px",
                "location":{
                  "x":139,
                  "y":439},
                "size":{
                  "width":119,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"9002c255a2c445a086c4620c06189076",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":546},
            "size":{
              "width":277,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/酒店列表页面/u28_line.png"}},
{
          "id":"f78d6cd2c59848ed869e9f3598cd2b91",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":465},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d6f1a3b879fb48bb8fd802b6fd7f33bd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":49,
                  "y":465},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店列表页面/u29.png"}},
{
          "id":"5770a4585404461290347bfdc5c14f8f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "location":{
              "x":139,
              "y":465},
            "size":{
              "width":166,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"ace10d979a5f4c90bd2301e2416d2de7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "location":{
                  "x":139,
                  "y":465},
                "size":{
                  "width":166,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"99dd2a26614546c98db8dbf731bda33c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":139,
              "y":487},
            "size":{
              "width":21,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"14a12d9aed3a490f893f4b67ec435399",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":139,
                  "y":487},
                "size":{
                  "width":21,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"5528504fb3b945fbac0bf622f57d027f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":139,
              "y":508},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6b8492a12f3f4ef39876b127f9ccd246",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":139,
                  "y":508},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"0bd86c9047dd47ddaa1b5d8a3c477d56",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":243,
              "y":511},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2880b964e258486497402b580982c28a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":511},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"7535161388dd4d1ebf8ff565ff7f412c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":255,
              "y":504},
            "size":{
              "width":45,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c2f162128a94ebbb1a59bc016ec61dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":255,
                  "y":504},
                "size":{
                  "width":45,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"cb4c6948e7e24274a18dbd6f04e5415b",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":159,
              "y":490},
            "size":{
              "width":11,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4f54a96d86224f7f90a5ffaa82d90af1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":159,
                  "y":490},
                "size":{
                  "width":11,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"38382656e6454e9bb2d16934d6bdef8a",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"10px",
            "location":{
              "x":300,
              "y":511},
            "size":{
              "width":11,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a9daf063c4194c5b86d5b843a96ddb4e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"10px",
                "location":{
                  "x":300,
                  "y":511},
                "size":{
                  "width":11,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"96220fe339ea426481e3bdb2cd97944f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"10px",
            "location":{
              "x":139,
              "y":530},
            "size":{
              "width":119,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6de97c5b9efc4fa28554f51967d2e95e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"10px",
                "location":{
                  "x":139,
                  "y":530},
                "size":{
                  "width":119,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"133d3e6a92814b1e99a752d6780607a2",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":637},
            "size":{
              "width":277,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/酒店列表页面/u28_line.png"}},
{
          "id":"9448b9a6050e4ea99e868bfcfb330d63",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":556},
            "size":{
              "width":80,
              "height":80}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2770959e557d4ffb96d87735320edb79",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":49,
                  "y":556},
                "size":{
                  "width":80,
                  "height":80}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店列表页面/u29.png"}},
{
          "id":"83900075530e47b4b52a87b170c57d20",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"15px",
            "fontWeight":"700",
            "location":{
              "x":139,
              "y":556},
            "size":{
              "width":166,
              "height":17}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d52877a8ccc040778eceef6ec69d4548",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"15px",
                "fontWeight":"700",
                "location":{
                  "x":139,
                  "y":556},
                "size":{
                  "width":166,
                  "height":17}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"db34488cc4b948c49f695e8782df52db",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'Arial Negreta', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"700",
            "foreGroundFill":{
              "fillType":"solid",
              "color":0xFF999999,
              "opacity":1},
            "location":{
              "x":139,
              "y":578},
            "size":{
              "width":21,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9abb859f4cb54e2a9124331a13dd8321",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Negreta', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"700",
                "foreGroundFill":{
                  "fillType":"solid",
                  "color":0xFF999999,
                  "opacity":1},
                "location":{
                  "x":139,
                  "y":578},
                "size":{
                  "width":21,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"1a68ce59d56b4ecf862817779ca24b7f",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":139,
              "y":599},
            "size":{
              "width":66,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2212709646094a1a9ff65d276b48258a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":139,
                  "y":599},
                "size":{
                  "width":66,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"30c0b22a6baf4664a92a66123c260d2c",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "location":{
              "x":243,
              "y":602},
            "size":{
              "width":14,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"1ba597e02322430495adac143eb62492",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":243,
                  "y":602},
                "size":{
                  "width":14,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"87c83f0b362643b89711bc115dc7299d",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"20px",
            "location":{
              "x":255,
              "y":595},
            "size":{
              "width":45,
              "height":24}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5ee21b3920c246e89bf099a9a401be8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"20px",
                "location":{
                  "x":255,
                  "y":595},
                "size":{
                  "width":45,
                  "height":24}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"fcb00d2075e94c56bd905ef9336a8461",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontSize":"10px",
            "location":{
              "x":159,
              "y":581},
            "size":{
              "width":11,
              "height":13}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"85a415064d7641f8b447cf5cb78bb3a5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontSize":"10px",
                "location":{
                  "x":159,
                  "y":581},
                "size":{
                  "width":11,
                  "height":13}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b7b672fa48f24e5fb2a93be955769b82",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"10px",
            "location":{
              "x":300,
              "y":602},
            "size":{
              "width":11,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"410b982f3ab2487b88015eb62adee75a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"10px",
                "location":{
                  "x":300,
                  "y":602},
                "size":{
                  "width":11,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"2194ca4a62a2488ab9d621eee92be879",
          "label":"",
          "type":"buttonShape",
          "styleType":"paragraph",
          "visible":true,
          "style":{
            "fontName":"'微软雅黑 Regular', '微软雅黑'",
            "fontSize":"10px",
            "location":{
              "x":139,
              "y":621},
            "size":{
              "width":119,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12a1e2b7e92248ccbc033646fc9be365",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'微软雅黑 Regular', '微软雅黑'",
                "fontSize":"10px",
                "location":{
                  "x":139,
                  "y":621},
                "size":{
                  "width":119,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"42e5cb8d21e34150b01f8d5d2a4a9cee",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":644},
            "size":{
              "width":282,
              "height":28}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b2408963d4a24b3ca707481095099094",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":49,
                  "y":644},
                "size":{
                  "width":282,
                  "height":28}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/酒店列表页面/u123.png"}},
{
          "id":"d8cd6a7d39d140f68fdf56e8c1d54d12",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":44,
              "y":132},
            "size":{
              "width":66,
              "height":26}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 二次查询页面",
                      "target":{
                        "targetType":"page",
                        "url":"二次查询页面.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true},
{
          "id":"acb5edeaaafa4dbebcfbe0322998b87a",
          "label":"",
          "type":"imageMapRegion",
          "styleType":"imageMapRegion",
          "visible":true,
          "style":{
            "location":{
              "x":49,
              "y":178},
            "size":{
              "width":286,
              "height":95}},
          "adaptiveStyles":{
},
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 酒店详情页",
                      "target":{
                        "targetType":"page",
                        "url":"酒店详情页.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true}]}},
  "masters":{
},
  "objectPaths":{
    "0b45123d05c64e658b57a4d3da00892e":{
      "scriptId":"u0"},
    "65acb8d2b47c441da525417224f26553":{
      "scriptId":"u1"},
    "5fe6c75503ef464db75d915620ca0b24":{
      "scriptId":"u2"},
    "b859d2ef9e1a4ec2853ed8636a26a10b":{
      "scriptId":"u3"},
    "a9130a63bf27468494e42563f95a5579":{
      "scriptId":"u4"},
    "70ff0e62b5524952b2c20cb36e5874c0":{
      "scriptId":"u5"},
    "eac163fc6b7d491c9ce02013f78d82e8":{
      "scriptId":"u6"},
    "36393678c390418794c898daee8bde14":{
      "scriptId":"u7"},
    "dea78c9910d9405b8b33c10dc9743dc8":{
      "scriptId":"u8"},
    "8ef0731662a243c091503574fb8a708a":{
      "scriptId":"u9"},
    "07fbfdec451f459ead5ffa24c266b7d7":{
      "scriptId":"u10"},
    "cf95eda3d3eb400c90f7da5446f67f5a":{
      "scriptId":"u11"},
    "42f582fbaf8341c8ade18000532ba7c5":{
      "scriptId":"u12"},
    "1bf35dbeb9df484285c1e6dd5a0b8f22":{
      "scriptId":"u13"},
    "fa8aa18396184e16b544a552993290fb":{
      "scriptId":"u14"},
    "fe52fa808f6f41b486b4cd316bc5fae3":{
      "scriptId":"u15"},
    "3a18542396ac463a89cbd3b673137bec":{
      "scriptId":"u16"},
    "6cb16b8329eb40608299550658e401b7":{
      "scriptId":"u17"},
    "02782a44f9c046f79589b5c5fdb29d7b":{
      "scriptId":"u18"},
    "943ef0e55ad845d0aabd408a99aef36a":{
      "scriptId":"u19"},
    "701cb7c14dff4c9ebacc8cc665904f22":{
      "scriptId":"u20"},
    "5441152b528649c58c75f77ad8276432":{
      "scriptId":"u21"},
    "16f0b0e1e0734171abf329f3611512f7":{
      "scriptId":"u22"},
    "7679a63e498145aabae035dfc17c1df1":{
      "scriptId":"u23"},
    "50656467df674bd082ad6ec52d2e1490":{
      "scriptId":"u24"},
    "71e24802a5ab4f4b96477de0d8025fc6":{
      "scriptId":"u25"},
    "bfe442bff86b42e8a90797c42d9e27ba":{
      "scriptId":"u26"},
    "a2c404b6146244b1b30d4a8aa5746d7f":{
      "scriptId":"u27"},
    "cbfa0b7fa81b4b6b93ab7afb7ad8059f":{
      "scriptId":"u28"},
    "c731f7d0cadd455e9c92ad18eaa65762":{
      "scriptId":"u29"},
    "2b3f1599d928442ab658e6c7e5701217":{
      "scriptId":"u30"},
    "fbb4ce093f5d47bbbf2cea0b1fdb5f21":{
      "scriptId":"u31"},
    "598dd5dfd3b645fc89805dfa79d184b3":{
      "scriptId":"u32"},
    "b61dedfaa25749e294ed09ecc62cfb50":{
      "scriptId":"u33"},
    "8fe387e88cfc4fc5807e7ddf9c0150d0":{
      "scriptId":"u34"},
    "df4cfe0a3c0f4a4a9a662f2e03c0e025":{
      "scriptId":"u35"},
    "c84f7fbc9f45414693599ac5b3286cce":{
      "scriptId":"u36"},
    "3392f135b4304aaabcc89fb71292725f":{
      "scriptId":"u37"},
    "b530486fe77a468dada64a24d408017d":{
      "scriptId":"u38"},
    "3eccd2b0f85b41eab396adeaae7172c8":{
      "scriptId":"u39"},
    "f97886065d2545799b625b482ce6b8a0":{
      "scriptId":"u40"},
    "f81b2ccc9ccb4fe590f7553a0b91a74e":{
      "scriptId":"u41"},
    "5958f952207b4729aa621b3f33a8ff39":{
      "scriptId":"u42"},
    "ec1890cf28094f7fab8867c5b8631653":{
      "scriptId":"u43"},
    "70e25b3953c1435eb5ba4f3aec2e3cb1":{
      "scriptId":"u44"},
    "a1c39a11a63e4e4b9727f6d1c6e19259":{
      "scriptId":"u45"},
    "42ac3eeaa58f460894d6f2dddbe25104":{
      "scriptId":"u46"},
    "19096f81345c4b8ea72436d61e88c35c":{
      "scriptId":"u47"},
    "a7bf4cb21abe4b74b4b845eb235b3525":{
      "scriptId":"u48"},
    "638de1f5dda44a679f304db3b187fac0":{
      "scriptId":"u49"},
    "b3bb77eec44d40f4bd9a87a329fe0e6e":{
      "scriptId":"u50"},
    "b8f825361dfb427a8c6b2bfca9cf13b9":{
      "scriptId":"u51"},
    "03fe015c286f46dcb7f41842ff39aebc":{
      "scriptId":"u52"},
    "27bcd7214d134bee9e5f307abac906b8":{
      "scriptId":"u53"},
    "3416e21ae9e0443b9bc8d1fd92d02fa7":{
      "scriptId":"u54"},
    "687bcef2272c4f7d894260f79c8335b7":{
      "scriptId":"u55"},
    "448504d8b30d4dd9bc4b543e892bc603":{
      "scriptId":"u56"},
    "8a8d26ce867c4380b4629d5b94a52927":{
      "scriptId":"u57"},
    "7fc8b4355efd435086dc2ada43a5b365":{
      "scriptId":"u58"},
    "c938e58a8181445785153e042ad84366":{
      "scriptId":"u59"},
    "5fb402005c8c4df0b9caa6a1e9a50c00":{
      "scriptId":"u60"},
    "81e6df26e65a4658b8e94c8bc3e08d43":{
      "scriptId":"u61"},
    "85cd576138b8419fbb302a78b07a23ea":{
      "scriptId":"u62"},
    "cd470807f0c245fdb2c2e1ef9dc338b7":{
      "scriptId":"u63"},
    "03582df1b7494e288d6f51e50ee7e326":{
      "scriptId":"u64"},
    "32083f75d68641419e8276cc374975fd":{
      "scriptId":"u65"},
    "590462e71e3343ab816f9847f053d494":{
      "scriptId":"u66"},
    "ef32b95ae98e42c5a83bf85f8428f5bf":{
      "scriptId":"u67"},
    "e1c85655f2f24621aa07a78ba3b9eaaa":{
      "scriptId":"u68"},
    "77eff39f45a84e8f948596d7120ea14e":{
      "scriptId":"u69"},
    "f6c4e7a10de346638a9a2f5b4efc799f":{
      "scriptId":"u70"},
    "69d544a2fd9c4447bc63d1fa340b989e":{
      "scriptId":"u71"},
    "ca914f9d0d254b8a9f67091cf25bff82":{
      "scriptId":"u72"},
    "046457645bf4447c8e521fe598f39f6b":{
      "scriptId":"u73"},
    "45406e8b12cb4316b10573cfb6a42626":{
      "scriptId":"u74"},
    "bfd84343678a46d493fc9d69601eb0a7":{
      "scriptId":"u75"},
    "47e21c4714ce4d3c8c14adede57cab34":{
      "scriptId":"u76"},
    "7e01ae2a5806434db78ccec555ea3a4e":{
      "scriptId":"u77"},
    "b08943b3ab5e41b18f8fef4e31f5d35e":{
      "scriptId":"u78"},
    "6b6132c4e06d4bd7ba2d7abc14c5186a":{
      "scriptId":"u79"},
    "c20d8341f9b440c5a128dafe26eaaf9d":{
      "scriptId":"u80"},
    "04317e841f754f2b9d2f9a1d2aebdeea":{
      "scriptId":"u81"},
    "c0fb933c301f4aed804b6233ae39d852":{
      "scriptId":"u82"},
    "cd4293be86c74659817328296b1288ac":{
      "scriptId":"u83"},
    "bbc9431d36884afb86cb00aba9e4d4e8":{
      "scriptId":"u84"},
    "9002c255a2c445a086c4620c06189076":{
      "scriptId":"u85"},
    "f78d6cd2c59848ed869e9f3598cd2b91":{
      "scriptId":"u86"},
    "d6f1a3b879fb48bb8fd802b6fd7f33bd":{
      "scriptId":"u87"},
    "5770a4585404461290347bfdc5c14f8f":{
      "scriptId":"u88"},
    "ace10d979a5f4c90bd2301e2416d2de7":{
      "scriptId":"u89"},
    "99dd2a26614546c98db8dbf731bda33c":{
      "scriptId":"u90"},
    "14a12d9aed3a490f893f4b67ec435399":{
      "scriptId":"u91"},
    "5528504fb3b945fbac0bf622f57d027f":{
      "scriptId":"u92"},
    "6b8492a12f3f4ef39876b127f9ccd246":{
      "scriptId":"u93"},
    "0bd86c9047dd47ddaa1b5d8a3c477d56":{
      "scriptId":"u94"},
    "2880b964e258486497402b580982c28a":{
      "scriptId":"u95"},
    "7535161388dd4d1ebf8ff565ff7f412c":{
      "scriptId":"u96"},
    "3c2f162128a94ebbb1a59bc016ec61dd":{
      "scriptId":"u97"},
    "cb4c6948e7e24274a18dbd6f04e5415b":{
      "scriptId":"u98"},
    "4f54a96d86224f7f90a5ffaa82d90af1":{
      "scriptId":"u99"},
    "38382656e6454e9bb2d16934d6bdef8a":{
      "scriptId":"u100"},
    "a9daf063c4194c5b86d5b843a96ddb4e":{
      "scriptId":"u101"},
    "96220fe339ea426481e3bdb2cd97944f":{
      "scriptId":"u102"},
    "6de97c5b9efc4fa28554f51967d2e95e":{
      "scriptId":"u103"},
    "133d3e6a92814b1e99a752d6780607a2":{
      "scriptId":"u104"},
    "9448b9a6050e4ea99e868bfcfb330d63":{
      "scriptId":"u105"},
    "2770959e557d4ffb96d87735320edb79":{
      "scriptId":"u106"},
    "83900075530e47b4b52a87b170c57d20":{
      "scriptId":"u107"},
    "d52877a8ccc040778eceef6ec69d4548":{
      "scriptId":"u108"},
    "db34488cc4b948c49f695e8782df52db":{
      "scriptId":"u109"},
    "9abb859f4cb54e2a9124331a13dd8321":{
      "scriptId":"u110"},
    "1a68ce59d56b4ecf862817779ca24b7f":{
      "scriptId":"u111"},
    "2212709646094a1a9ff65d276b48258a":{
      "scriptId":"u112"},
    "30c0b22a6baf4664a92a66123c260d2c":{
      "scriptId":"u113"},
    "1ba597e02322430495adac143eb62492":{
      "scriptId":"u114"},
    "87c83f0b362643b89711bc115dc7299d":{
      "scriptId":"u115"},
    "5ee21b3920c246e89bf099a9a401be8b":{
      "scriptId":"u116"},
    "fcb00d2075e94c56bd905ef9336a8461":{
      "scriptId":"u117"},
    "85a415064d7641f8b447cf5cb78bb3a5":{
      "scriptId":"u118"},
    "b7b672fa48f24e5fb2a93be955769b82":{
      "scriptId":"u119"},
    "410b982f3ab2487b88015eb62adee75a":{
      "scriptId":"u120"},
    "2194ca4a62a2488ab9d621eee92be879":{
      "scriptId":"u121"},
    "12a1e2b7e92248ccbc033646fc9be365":{
      "scriptId":"u122"},
    "42e5cb8d21e34150b01f8d5d2a4a9cee":{
      "scriptId":"u123"},
    "b2408963d4a24b3ca707481095099094":{
      "scriptId":"u124"},
    "d8cd6a7d39d140f68fdf56e8c1d54d12":{
      "scriptId":"u125"},
    "acb5edeaaafa4dbebcfbe0322998b87a":{
      "scriptId":"u126"}}});