$axure.loadCurrentPage({
  "url":"信用卡支付（易宝）.html",
  "generationDate":new Date(1407924516906.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"719ffe600444453199f9e9d09e364529",
    "type":"Axure:Page",
    "name":"信用卡支付（易宝）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"1527a72671994c838ba7b6199e51ce46",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":26},
            "size":{
              "width":380,
              "height":744},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d9f9e4bc19b54880960212b0d683cd8f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":26},
                "size":{
                  "width":380,
                  "height":744},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/话费充值/u0.png"}},
{
          "id":"e33355824a1b471e8caf3f2f0b2ef697",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":51,
              "y":178},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7a19e4d0d8af45d8b4c79cf28b2b4c4f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":51,
                  "y":178},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/话费充值/u2.png"}},
{
          "id":"5bba2c9c5b2046a4addc0bb097c9495b",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":163},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0d10fac227b54cf89965bebafa0a7a8b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":163},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/话费充值/u4.png"}},
{
          "id":"7c917957254949f8a11b563a0f290fcf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"16px",
            "horizontalAlignment":"left",
            "location":{
              "x":70,
              "y":234},
            "size":{
              "width":290,
              "height":186}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"01f1da4236d14f99bd7b3ef2c128b1a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"16px",
                "horizontalAlignment":"left",
                "location":{
                  "x":70,
                  "y":234},
                "size":{
                  "width":290,
                  "height":186}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/信用卡支付（易宝）/u6.png"}},
{
          "id":"9f157bd7aa9344fd86f3be3d80271efc",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":150,
              "y":182},
            "size":{
              "width":168,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b644df2876ed4b18805b6f15db295fbf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":150,
                  "y":182},
                "size":{
                  "width":168,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"81848db576204722a6a78d8468ca4a58",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":165,
              "y":570},
            "size":{
              "width":90,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9a25a1b24b646058eeed20578b8154b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":165,
                  "y":570},
                "size":{
                  "width":90,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 手机验证（易宝）",
                      "target":{
                        "targetType":"page",
                        "url":"手机验证（易宝）.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/话费充值/u8.png"}},
{
          "id":"33437ee449b84a15837a8e5787ad8057",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":70,
              "y":480},
            "size":{
              "width":290,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e562da95189f4c3f986d3421eed9efaa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":70,
                  "y":480},
                "size":{
                  "width":290,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"f163c96a3fb542ba84e8f018a5b8c59b",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":70,
              "y":510},
            "size":{
              "width":290,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"7ba104f58a1743cb901791beedde2f91",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":70,
                  "y":510},
                "size":{
                  "width":290,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"3310628a368d4b77997c20e568a785be",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":70,
              "y":455},
            "size":{
              "width":290,
              "height":25}},
          "adaptiveStyles":{
}},
{
          "id":"aa5d32a440214a629ddbf5bc85652571",
          "label":"",
          "type":"textBox",
          "styleType":"textBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":70,
              "y":430},
            "size":{
              "width":210,
              "height":25}},
          "adaptiveStyles":{
}}]}},
  "masters":{
},
  "objectPaths":{
    "1527a72671994c838ba7b6199e51ce46":{
      "scriptId":"u0"},
    "d9f9e4bc19b54880960212b0d683cd8f":{
      "scriptId":"u1"},
    "e33355824a1b471e8caf3f2f0b2ef697":{
      "scriptId":"u2"},
    "7a19e4d0d8af45d8b4c79cf28b2b4c4f":{
      "scriptId":"u3"},
    "5bba2c9c5b2046a4addc0bb097c9495b":{
      "scriptId":"u4"},
    "0d10fac227b54cf89965bebafa0a7a8b":{
      "scriptId":"u5"},
    "7c917957254949f8a11b563a0f290fcf":{
      "scriptId":"u6"},
    "01f1da4236d14f99bd7b3ef2c128b1a1":{
      "scriptId":"u7"},
    "9f157bd7aa9344fd86f3be3d80271efc":{
      "scriptId":"u8"},
    "b644df2876ed4b18805b6f15db295fbf":{
      "scriptId":"u9"},
    "81848db576204722a6a78d8468ca4a58":{
      "scriptId":"u10"},
    "b9a25a1b24b646058eeed20578b8154b":{
      "scriptId":"u11"},
    "33437ee449b84a15837a8e5787ad8057":{
      "scriptId":"u12"},
    "e562da95189f4c3f986d3421eed9efaa":{
      "scriptId":"u13"},
    "f163c96a3fb542ba84e8f018a5b8c59b":{
      "scriptId":"u14"},
    "7ba104f58a1743cb901791beedde2f91":{
      "scriptId":"u15"},
    "3310628a368d4b77997c20e568a785be":{
      "scriptId":"u16"},
    "aa5d32a440214a629ddbf5bc85652571":{
      "scriptId":"u17"}}});