$axure.loadCurrentPage({
  "url":"充值订单（默认支付）.html",
  "generationDate":new Date(1409800780921.88),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"b4350b09a39e4ba2be3a12dac92f32cc",
    "type":"Axure:Page",
    "name":"充值订单（默认支付）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"8866837b9a844753be11dbc197709564",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":26},
            "size":{
              "width":380,
              "height":704},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c4f872feed064ecaad560e517344708b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":26},
                "size":{
                  "width":380,
                  "height":704},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息设置/u0.png"}},
{
          "id":"004d4246a4094a75ac3c276dbd220ed8",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":51,
              "y":178},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3ccf0f65cbbd4ff0b339a997196327d6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":51,
                  "y":178},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息设置/u2.png"}},
{
          "id":"3ea7dda675ee448d8ad7aa8173c6c065",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":163},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0f0e8730278d4cc597ce2a81ed8171b3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":163},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息设置/u4.png"}},
{
          "id":"ef07a488eb1c469497fc80fc8e836575",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":110,
              "y":182},
            "size":{
              "width":208,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"8c671f906bbd45f99b55769773622f4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":110,
                  "y":182},
                "size":{
                  "width":208,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"e1efaf0bc7d144caa9a897c4f6741509",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":160,
              "y":560},
            "size":{
              "width":90,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa134f49785e46ddb4bd35b263d08b83",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":160,
                  "y":560},
                "size":{
                  "width":90,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 手机验证（默认支付）",
                      "target":{
                        "targetType":"page",
                        "url":"手机验证（默认支付）_1.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/话费充值/u8.png"}},
{
          "id":"71ae8ec5b8834b8db1347422cf674d2f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":280},
            "size":{
              "width":260,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2458b5c4814e40ab88271eecd7587bc6",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":280},
                "size":{
                  "width":260,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息设置/u8.png"}},
{
          "id":"a0a39a25d68b473abb04c67035574784",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":250},
            "size":{
              "width":260,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"cbb4e5b1aaaf48309adfed60b76bf06d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":250},
                "size":{
                  "width":260,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息设置/u8.png"}},
{
          "id":"941076a66e244b7a81e0e5f7dc1da9fe",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":310},
            "size":{
              "width":260,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"416b3ccc71b040f5afc2e414749ea637",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":310},
                "size":{
                  "width":260,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/用户信息设置/u8.png"}},
{
          "id":"4e4e1b2875da4662a6efaca44d41cae2",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":80,
              "y":360},
            "size":{
              "width":260,
              "height":120}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a829c2da353a4dcb9bceade52de77fee",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":80,
                  "y":360},
                "size":{
                  "width":260,
                  "height":120}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/充值订单（默认支付）/u16.png"}},
{
          "id":"04371eb5a987434ab9d16a19f633b8b2",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":80,
              "y":390},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0e5b9ffc2d0c4162b3b3d5aedb46d9be",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":80,
                  "y":390},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"c0eb453d59414d25aa09dcfa2219c5ce",
          "label":"",
          "type":"checkbox",
          "styleType":"checkbox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":80,
              "y":444},
            "size":{
              "width":100,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aa0362880adc4f598500ae93a64336db",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":80,
                  "y":444},
                "size":{
                  "width":100,
                  "height":16}},
              "adaptiveStyles":{
}}]},
{
          "id":"e2be05638f664e02ab6af09bc9032568",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":198,
              "y":442},
            "size":{
              "width":120,
              "height":20}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"65a738dc492e4567816a1163145ec0d9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":198,
                  "y":442},
                "size":{
                  "width":120,
                  "height":20}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/选择支付（默认支付）/u12.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "8866837b9a844753be11dbc197709564":{
      "scriptId":"u0"},
    "c4f872feed064ecaad560e517344708b":{
      "scriptId":"u1"},
    "004d4246a4094a75ac3c276dbd220ed8":{
      "scriptId":"u2"},
    "3ccf0f65cbbd4ff0b339a997196327d6":{
      "scriptId":"u3"},
    "3ea7dda675ee448d8ad7aa8173c6c065":{
      "scriptId":"u4"},
    "0f0e8730278d4cc597ce2a81ed8171b3":{
      "scriptId":"u5"},
    "ef07a488eb1c469497fc80fc8e836575":{
      "scriptId":"u6"},
    "8c671f906bbd45f99b55769773622f4d":{
      "scriptId":"u7"},
    "e1efaf0bc7d144caa9a897c4f6741509":{
      "scriptId":"u8"},
    "aa134f49785e46ddb4bd35b263d08b83":{
      "scriptId":"u9"},
    "71ae8ec5b8834b8db1347422cf674d2f":{
      "scriptId":"u10"},
    "2458b5c4814e40ab88271eecd7587bc6":{
      "scriptId":"u11"},
    "a0a39a25d68b473abb04c67035574784":{
      "scriptId":"u12"},
    "cbb4e5b1aaaf48309adfed60b76bf06d":{
      "scriptId":"u13"},
    "941076a66e244b7a81e0e5f7dc1da9fe":{
      "scriptId":"u14"},
    "416b3ccc71b040f5afc2e414749ea637":{
      "scriptId":"u15"},
    "4e4e1b2875da4662a6efaca44d41cae2":{
      "scriptId":"u16"},
    "a829c2da353a4dcb9bceade52de77fee":{
      "scriptId":"u17"},
    "04371eb5a987434ab9d16a19f633b8b2":{
      "scriptId":"u18"},
    "0e5b9ffc2d0c4162b3b3d5aedb46d9be":{
      "scriptId":"u19"},
    "c0eb453d59414d25aa09dcfa2219c5ce":{
      "scriptId":"u20"},
    "aa0362880adc4f598500ae93a64336db":{
      "scriptId":"u21"},
    "e2be05638f664e02ab6af09bc9032568":{
      "scriptId":"u22"},
    "65a738dc492e4567816a1163145ec0d9":{
      "scriptId":"u23"}}});