$axure.loadCurrentPage({
  "url":"我的授权码.html",
  "generationDate":new Date(1416631106703.13),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"54dc0a273ca14ae7be3fb97c7698a77b",
    "type":"Axure:Page",
    "name":"我的授权码",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"dd5a9da2b3e6420ebdd9b0d99f56c911",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":30,
              "y":20},
            "size":{
              "width":380,
              "height":744},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"11c34f3d5fd84340a25bf7ccb5101199",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":30,
                  "y":20},
                "size":{
                  "width":380,
                  "height":744},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买授权码/u0.png"}},
{
          "id":"7bc8d26a9edc485e80bea32115963ff0",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":163},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c0f4aa884d194b5b895439a54eb4f2dc",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":163},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买授权码/u2.png"}},
{
          "id":"c70317f3bea7496a80ebe93f15d58f0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":143,
              "y":194},
            "size":{
              "width":177,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"175a0e558c3643df8da1f4bfde2c42a1",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":143,
                  "y":194},
                "size":{
                  "width":177,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"4c26824c71a54c6288265cdc0452896f",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":90,
              "y":250},
            "size":{
              "width":260,
              "height":70}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0595aa2ebcda4fc381b1494a75b7bd86",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":90,
                  "y":250},
                "size":{
                  "width":260,
                  "height":70}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/我的授权码/u6.png"}},
{
          "id":"a9cb2ac2cc0c4f5c8c3f5e206a3f5fe9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "horizontalAlignment":"left",
            "location":{
              "x":90,
              "y":198},
            "size":{
              "width":30,
              "height":29}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"82f288f17cd445d7a52618ebd1dc6caf",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "horizontalAlignment":"left",
                "location":{
                  "x":90,
                  "y":198},
                "size":{
                  "width":30,
                  "height":29}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 购买授权码",
                      "target":{
                        "targetType":"page",
                        "url":"购买授权码.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/购买授权码/u21.png"}},
{
          "id":"c4b6abbe3b674e6da15bf5dd1f79b2f7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":420,
              "y":265},
            "size":{
              "width":300,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"036b05867bc642be975a80886a7253ea",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":420,
                  "y":265},
                "size":{
                  "width":300,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/购买授权码/u14.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "dd5a9da2b3e6420ebdd9b0d99f56c911":{
      "scriptId":"u0"},
    "11c34f3d5fd84340a25bf7ccb5101199":{
      "scriptId":"u1"},
    "7bc8d26a9edc485e80bea32115963ff0":{
      "scriptId":"u2"},
    "c0f4aa884d194b5b895439a54eb4f2dc":{
      "scriptId":"u3"},
    "c70317f3bea7496a80ebe93f15d58f0a":{
      "scriptId":"u4"},
    "175a0e558c3643df8da1f4bfde2c42a1":{
      "scriptId":"u5"},
    "4c26824c71a54c6288265cdc0452896f":{
      "scriptId":"u6"},
    "0595aa2ebcda4fc381b1494a75b7bd86":{
      "scriptId":"u7"},
    "a9cb2ac2cc0c4f5c8c3f5e206a3f5fe9":{
      "scriptId":"u8"},
    "82f288f17cd445d7a52618ebd1dc6caf":{
      "scriptId":"u9"},
    "c4b6abbe3b674e6da15bf5dd1f79b2f7":{
      "scriptId":"u10"},
    "036b05867bc642be975a80886a7253ea":{
      "scriptId":"u11"}}});