$axure.loadCurrentPage({
  "url":"收款账户设定（银行卡_设定）.html",
  "generationDate":new Date(1398151328431.28),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"bacc814a6e03415a9ae442cce295eb82",
    "type":"Axure:Page",
    "name":"收款账户设定（银行卡 设定）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"3427889edf93403bba0aca3b94f17456",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":80},
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"12cab039173d4728be267c8b43dd89e5",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":80},
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u0.png"}},
{
          "id":"b67282894859497c9b7ac4d53e6f67d2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":202},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a34e850cb3f74b3487c674b1d7b94039",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":202},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u2.png"}},
{
          "id":"e300ae68ac364c1fbbd05ad84db433de",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":230},
            "size":{
              "width":280,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"367d03131bc14313b88885988878621c",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":230},
                "size":{
                  "width":280,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收款账户设定（银行卡_设定）/u4.png"}},
{
          "id":"5e56c920d7f8454d9917f5291ec609b7",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":287},
            "size":{
              "width":160,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"54f282c282904785bbcc29d75bdcff4b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":287},
                "size":{
                  "width":160,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收款账户设定（银行卡_设定）/u6.png"}},
{
          "id":"0c38a54326ba4aa69bf74c510967dc76",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":335},
            "size":{
              "width":280,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"86265a08199d4d5c92530e5b9d516f62",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":335},
                "size":{
                  "width":280,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收款账户设定（银行卡_设定）/u8.png"}},
{
          "id":"0ce56aaf9ec8416b9f3c5b839d8e094a",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":386},
            "size":{
              "width":280,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4f55dadbf824b568159496c66555b04",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":386},
                "size":{
                  "width":280,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收款账户设定（银行卡_设定）/u8.png"}},
{
          "id":"8dba00483d5f4a038607e4fe0bdb82ef",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":265,
              "y":291},
            "size":{
              "width":81,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"aeefbca9102f4e22af37a0729d75d97f",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":265,
                  "y":291},
                "size":{
                  "width":81,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"540fb895ab1f4636b3f579da232db704",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":318,
              "y":244},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"529ccec48348490a8a20d7735e3b4e1d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":318,
                  "y":244},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收款账户设定（银行卡_设定）/u14.png"}},
{
          "id":"5d60c2183e8a4212ace5a095f2b6b18b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":211,
              "y":500},
            "size":{
              "width":139,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9078d3b0f06945c7bb709848e15d6cad",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":211,
                  "y":500},
                "size":{
                  "width":139,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收款账户设定（银行卡_设定）/u16.png"}},
{
          "id":"20fbf7453f3940568e30b8e3aab13aba",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":550},
            "size":{
              "width":320,
              "height":216},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d85a7eeaf8e14bd598ccc35bd9d4c509",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":52,
                  "y":550},
                "size":{
                  "width":320,
                  "height":216},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收款账户设定（银行卡_设定）/u18.png"}},
{
          "id":"64bc001f099747318648d879eab639c9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":440},
            "size":{
              "width":280,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"24bb00a2f9644b9892d1c0c1176aa2bb",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":440},
                "size":{
                  "width":280,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收款账户设定（银行卡_设定）/u8.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "3427889edf93403bba0aca3b94f17456":{
      "scriptId":"u0"},
    "12cab039173d4728be267c8b43dd89e5":{
      "scriptId":"u1"},
    "b67282894859497c9b7ac4d53e6f67d2":{
      "scriptId":"u2"},
    "a34e850cb3f74b3487c674b1d7b94039":{
      "scriptId":"u3"},
    "e300ae68ac364c1fbbd05ad84db433de":{
      "scriptId":"u4"},
    "367d03131bc14313b88885988878621c":{
      "scriptId":"u5"},
    "5e56c920d7f8454d9917f5291ec609b7":{
      "scriptId":"u6"},
    "54f282c282904785bbcc29d75bdcff4b":{
      "scriptId":"u7"},
    "0c38a54326ba4aa69bf74c510967dc76":{
      "scriptId":"u8"},
    "86265a08199d4d5c92530e5b9d516f62":{
      "scriptId":"u9"},
    "0ce56aaf9ec8416b9f3c5b839d8e094a":{
      "scriptId":"u10"},
    "e4f55dadbf824b568159496c66555b04":{
      "scriptId":"u11"},
    "8dba00483d5f4a038607e4fe0bdb82ef":{
      "scriptId":"u12"},
    "aeefbca9102f4e22af37a0729d75d97f":{
      "scriptId":"u13"},
    "540fb895ab1f4636b3f579da232db704":{
      "scriptId":"u14"},
    "529ccec48348490a8a20d7735e3b4e1d":{
      "scriptId":"u15"},
    "5d60c2183e8a4212ace5a095f2b6b18b":{
      "scriptId":"u16"},
    "9078d3b0f06945c7bb709848e15d6cad":{
      "scriptId":"u17"},
    "20fbf7453f3940568e30b8e3aab13aba":{
      "scriptId":"u18"},
    "d85a7eeaf8e14bd598ccc35bd9d4c509":{
      "scriptId":"u19"},
    "64bc001f099747318648d879eab639c9":{
      "scriptId":"u20"},
    "24bb00a2f9644b9892d1c0c1176aa2bb":{
      "scriptId":"u21"}}});