$axure.loadCurrentPage({
  "url":"收款账户设定（支付宝_设定）.html",
  "generationDate":new Date(1398151328494.29),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5470ad7b451041bdb0c6679999540bb0",
    "type":"Axure:Page",
    "name":"收款账户设定（支付宝 设定）",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"7bc08185bc9f498aa89056a4785aa273",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":20,
              "y":80},
            "size":{
              "width":380,
              "height":800},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"0443017f386b4b5fa24a07eb89dae85a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":20,
                  "y":80},
                "size":{
                  "width":380,
                  "height":800},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u0.png"}},
{
          "id":"0223ab09dd8d489480a16c1c7e463d4a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":58,
              "y":202},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"38c810a67c4744fcbd86c6413494d831",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":58,
                  "y":202},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/认证注册（基础设定）/u2.png"}},
{
          "id":"5b345f28c9e74784ae8ec399bc8b4a7b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":230},
            "size":{
              "width":280,
              "height":50}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e727e6daf9324f5b9d130894656894dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":230},
                "size":{
                  "width":280,
                  "height":50}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收款账户设定（银行卡_设定）/u4.png"}},
{
          "id":"232e1dc6b3504d3b9e6a213a18879b8b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":300},
            "size":{
              "width":160,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fdc4705e054a4f98b060cc785ace1488",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":300},
                "size":{
                  "width":160,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收款账户设定（银行卡_设定）/u6.png"}},
{
          "id":"5ede91566bab40469792652b1e26812b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":350},
            "size":{
              "width":280,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"3c55d4d9cac1402fa07f9edce87a2cca",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":350},
                "size":{
                  "width":280,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收款账户设定（银行卡_设定）/u8.png"}},
{
          "id":"98cb814b832d4c3eb40ccc925f5096c6",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":70,
              "y":410},
            "size":{
              "width":280,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a5f441ee637b4cd3bc3448945db78f3a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":70,
                  "y":410},
                "size":{
                  "width":280,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收款账户设定（银行卡_设定）/u8.png"}},
{
          "id":"6788190657ba4916b0a180b5c6c18119",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Normal', 'Arial'",
            "fontSize":"20px",
            "fontWeight":"400",
            "location":{
              "x":265,
              "y":306},
            "size":{
              "width":61,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"a0a2065df57a4b1a9df98be18cdeb9fa",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Normal', 'Arial'",
                "fontSize":"20px",
                "fontWeight":"400",
                "location":{
                  "x":265,
                  "y":306},
                "size":{
                  "width":61,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ab8efc905d1345738658a55bbcac21bd",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":318,
              "y":244},
            "size":{
              "width":22,
              "height":22},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"736b965bd00c442188b79b7d673f282b",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":318,
                  "y":244},
                "size":{
                  "width":22,
                  "height":22},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收款账户设定（银行卡_设定）/u14.png"}},
{
          "id":"a4944c43c278490f9a49618e30ced199",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "location":{
              "x":210,
              "y":480},
            "size":{
              "width":139,
              "height":40}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"10a885114b224f75815da5af2eb1b8f0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":210,
                  "y":480},
                "size":{
                  "width":139,
                  "height":40}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收款账户设定（银行卡_设定）/u16.png"}},
{
          "id":"6d0a04acfa8f4e36859624bfda8d8088",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":52,
              "y":550},
            "size":{
              "width":320,
              "height":216},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"2a231ae279b849e7a3af25af811c3f5e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":52,
                  "y":550},
                "size":{
                  "width":320,
                  "height":216},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/收款账户设定（银行卡_设定）/u18.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "7bc08185bc9f498aa89056a4785aa273":{
      "scriptId":"u0"},
    "0443017f386b4b5fa24a07eb89dae85a":{
      "scriptId":"u1"},
    "0223ab09dd8d489480a16c1c7e463d4a":{
      "scriptId":"u2"},
    "38c810a67c4744fcbd86c6413494d831":{
      "scriptId":"u3"},
    "5b345f28c9e74784ae8ec399bc8b4a7b":{
      "scriptId":"u4"},
    "e727e6daf9324f5b9d130894656894dd":{
      "scriptId":"u5"},
    "232e1dc6b3504d3b9e6a213a18879b8b":{
      "scriptId":"u6"},
    "fdc4705e054a4f98b060cc785ace1488":{
      "scriptId":"u7"},
    "5ede91566bab40469792652b1e26812b":{
      "scriptId":"u8"},
    "3c55d4d9cac1402fa07f9edce87a2cca":{
      "scriptId":"u9"},
    "98cb814b832d4c3eb40ccc925f5096c6":{
      "scriptId":"u10"},
    "a5f441ee637b4cd3bc3448945db78f3a":{
      "scriptId":"u11"},
    "6788190657ba4916b0a180b5c6c18119":{
      "scriptId":"u12"},
    "a0a2065df57a4b1a9df98be18cdeb9fa":{
      "scriptId":"u13"},
    "ab8efc905d1345738658a55bbcac21bd":{
      "scriptId":"u14"},
    "736b965bd00c442188b79b7d673f282b":{
      "scriptId":"u15"},
    "a4944c43c278490f9a49618e30ced199":{
      "scriptId":"u16"},
    "10a885114b224f75815da5af2eb1b8f0":{
      "scriptId":"u17"},
    "6d0a04acfa8f4e36859624bfda8d8088":{
      "scriptId":"u18"},
    "2a231ae279b849e7a3af25af811c3f5e":{
      "scriptId":"u19"}}});