$axure.loadCurrentPage({
  "url":"充值成功_1.html",
  "generationDate":new Date(1407924518531.25),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"eb1023ef29ab4593bf276edb684edf80",
    "type":"Axure:Page",
    "name":"充值成功",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"2685a455608c4862bce60297f9dfaa39",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":20,
              "y":26},
            "size":{
              "width":380,
              "height":744},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"c53ac513f3c04435af2a76f5fd0c5542",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":20,
                  "y":26},
                "size":{
                  "width":380,
                  "height":744},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/话费充值/u0.png"}},
{
          "id":"178d3a6c8192411d9e22fdf7e2abacdb",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":51,
              "y":178},
            "size":{
              "width":320,
              "height":46},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"15b86fed556c42b4bdd5767366b94299",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":51,
                  "y":178},
                "size":{
                  "width":320,
                  "height":46},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/话费充值/u2.png"}},
{
          "id":"880f646efc174070ae9dc4f802f2b109",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":62,
              "y":163},
            "size":{
              "width":308,
              "height":13},
            "borderWidth":"-1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b9fd390ab8544f8c91a0e45b0917578e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":62,
                  "y":163},
                "size":{
                  "width":308,
                  "height":13},
                "borderWidth":"-1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/话费充值/u4.png"}},
{
          "id":"98e68e4542da40b2b3d91dcb8b90bd10",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "fontSize":"20px",
            "horizontalAlignment":"left",
            "location":{
              "x":62,
              "y":234},
            "size":{
              "width":298,
              "height":306}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9b8cd03c24c24c17b5990e315940ee28",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "fontSize":"20px",
                "horizontalAlignment":"left",
                "location":{
                  "x":62,
                  "y":234},
                "size":{
                  "width":298,
                  "height":306}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/1、选择支付（默认支付）/u6.png"}},
{
          "id":"33c3018efd8c474b93559321740f13a8",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":150,
              "y":182},
            "size":{
              "width":168,
              "height":37}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d93fe063dd894f70b842d7f0d2d7142a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":150,
                  "y":182},
                "size":{
                  "width":168,
                  "height":37}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"c87c2d9732df46b9817e823b3e2528bf",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "fontName":"'Applied Font Regular', 'Applied Font'",
            "location":{
              "x":165,
              "y":570},
            "size":{
              "width":90,
              "height":30}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"f29e0de4380840f0a3fc8663a8651285",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Applied Font Regular', 'Applied Font'",
                "location":{
                  "x":165,
                  "y":570},
                "size":{
                  "width":90,
                  "height":30}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"用例 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"在 当前窗口 打开 Q币充值",
                      "target":{
                        "targetType":"page",
                        "url":"q币充值.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/话费充值/u8.png"}}]}},
  "masters":{
},
  "objectPaths":{
    "2685a455608c4862bce60297f9dfaa39":{
      "scriptId":"u0"},
    "c53ac513f3c04435af2a76f5fd0c5542":{
      "scriptId":"u1"},
    "178d3a6c8192411d9e22fdf7e2abacdb":{
      "scriptId":"u2"},
    "15b86fed556c42b4bdd5767366b94299":{
      "scriptId":"u3"},
    "880f646efc174070ae9dc4f802f2b109":{
      "scriptId":"u4"},
    "b9fd390ab8544f8c91a0e45b0917578e":{
      "scriptId":"u5"},
    "98e68e4542da40b2b3d91dcb8b90bd10":{
      "scriptId":"u6"},
    "9b8cd03c24c24c17b5990e315940ee28":{
      "scriptId":"u7"},
    "33c3018efd8c474b93559321740f13a8":{
      "scriptId":"u8"},
    "d93fe063dd894f70b842d7f0d2d7142a":{
      "scriptId":"u9"},
    "c87c2d9732df46b9817e823b3e2528bf":{
      "scriptId":"u10"},
    "f29e0de4380840f0a3fc8663a8651285":{
      "scriptId":"u11"}}});